/**
 * Model of a WorkEffort.
 */
export class WorkEffort {
  workEffortParent?: WorkEffort;

  constructor(
    public workEffortId?: string,
    public workEffortName?: string,
    public workEffortNameLang?: string,
    public workEffortTypeId?: string,
    public sourceReferenceId?: string,
    public currentStatusId?: string,
    public lastStatusUpdate?: Date,
    public workEffortPurposeTypeId?: string,
    public workEffortParentId?: string,
    public scopeEnumId?: string,
    public priority?: Number,
    public percentComplete?: Number,
    public showAsEnumId?: string,
    public sendNotificationEmail?: string,
    public description?: string,
    public locationDesc?: string,
    public estimatedStartDate?: Date,
    public estimatedCompletionDate?: Date,
    public actualStartDate?: Date,
    public actualCompletionDate?: Date,
    public estimatedMilliSeconds?: Number,
    public estimatedSetupMillis?: Number,
    public estimateCalcMethod?: string,
    public actualMilliSeconds?: Number,
    public actualSetupMillis?: Number,
    public totalMilliSecondsAllowed?: Number,
    public totalMoneyAllowed?: Number,
    public moneyUomId?: string,
    public specialTerms?: string,
    public timeTransparency?: Number,
    public universalId?: string,
    public fixedAssetId?: string,
    public facilityId?: string,
    public infoUrl?: string,
    public recurrenceInfoId?: string,
    public tempExprId?: string,
    public runtimeDataId?: string,
    public noteId?: string,
    public serviceLoaderName?: string,
    public quantityToProduce?: Number,
    public quantityProduced?: Number,
    public quantityRejected?: Number,
    public reservPersons?: Number,
    public reserv2ndPPPerc?: Number,
    public reservNthPPPerc?: Number,
    public accommodationMapId?: string,
    public accommodationSpotId?: string,
    public revisionNumber?: Number,
    public organizationId?: string,
    public effortUomId?: string,
    public productId?: string,
    public emplPositionTypeId?: string,
    public localNameContentId?: string,
    public estimatedTotalEffort?: Number,
    public weightKpi?: Number,
    public weightReview?: Number,
    public weightSons?: Number,
    public orgUnitRoleTypeId?: string,
    public orgUnitId?: string,
    public weightAssocWorkEffort?: string,
    public workEffortAssocTypeId?: Number,
    public lastCorrectScoreDate?: Date,
    public totalEnumIdKpi?: string,
    public totalEnumIdSons?: string,
    public totalEnumIdAssoc?: string,
    public processId?: string,
    public isPosted?: string,
    public etch?: string,
    public workEffortTypePeriodId?: string,
    public snapShotDate?: Date,
    public snapShotDescription?: string,
    public workEffortSnapshotId?: string,
    public uomRangeScoreId?: string,
    public workEffortRevisionId?: string,
    public scheduledStartDate?: Date,
    public scheduledCompletionDate?: Date,
    public descriptionLang?: string,
    public dataSoll?: Date,
    public sequenceNum?: Number,
  ) { }
}
