#userLogin.gzoom.alemai=Alessandro|Mariucci|alessandro.mariucci@mapsgroup.it
#userLogin.gzoom.aletiv=Alex|Tivoli|Alex.Tivoli@mapsgroup.it
userLogin.gzoom.anddel=Andrea|Delfi|Andrea.Delfi@mapsgroup.it
#userLogin.gzoom.andnie=Andrea|Nieddu|Andrea.Nieddu@mapsgroup.it
userLogin.gzoom.anin=Anna|Indolfi|Anna.Indolfi@mapsgroup.it
#userLogin.gzoom.antcal=Antonio|Cal&#242;|Antonio.Calo@mapsgroup.it
userLogin.gzoom.cada=Carla|Dall'Aglio|carla.dallaglio@mapsgroup.it
#userLogin.gzoom.cricol=Cristiano|Colaluca|Cristiano.Colaluca@mapsgroup.it
userLogin.gzoom.dain=Daina|Interrante|daina.interrante@mapsgroup.it
#userLogin.gzoom.dancor=Daniela|Corda|Daniela.Corda@mapsgroup.it
userLogin.gzoom.elma=Elisa|Maghenzani|Elisa.Maghenzani@mapsgroup.it
#userLogin.gzoom.leomia=Leonardo|Minaudo|Leonardo.Minaudo@mapsgroup.it
userLogin.gzoom.giaval=Giancarlo|Valeri|giancarlo.valeri@mapsgroup.it
userLogin.gzoom.mardom=Martina|Dominici|Martina.Dominici@mapsgroup.it
userLogin.gzoom.maru=Marco|Ruocco|Marco.Ruocco@mapsgroup.it
userLogin.gzoom.matcos=Matteo|Costella|matteo.costella@mapsgroup.it
userLogin.gzoom.paca=Paolo|Catellani|Paolo.Catellani@mapsgroup.it
userLogin.gzoom.pimi=Pietro|Minicelli|Pietro.Minicelli@mapsgroup.it
userLogin.gzoom.rodo=Roberto|Dondi|RobertoDondi@mapsgroup.it
userLogin.gzoom.stbe=Stefano|Benfenati|Stefano.Benfenati@mapsgroup.it
userLogin.gzoom.svje=Svetlana|Jechiu|Svetlana.Jechiu@mapsgroup.it
userLogin.gzoom.yanpro=Yanina|Protskaya|Yanina.Protskaya@mapsgroup.it
userLogin.gzoom.vano=Valeria|Nobile|Valeria.Nobile@mapsgroup.it
userLogin.gzoom.gipi=Giuseppe|Pirruccio|Giuseppe.Pirruccio@mapsgroup.it
userLogin.gzoom.stma=Stefano|Magistrali|Stefano.Magistrali@mapsgroup.it
userLogin.gzoom.riru=Riccardo|Ruffilli|Riccardo.Ruffilli@mapsgroup.it
userLogin.gzoom.musben=Ben|Saied|Ben.Saied@mapsgroup.it
userLogin.gzoom.enizez=Eni|Zeza|Eni.Zeza@mapsgroup.it