#     ______________________
#    / Build artifact Stage \
#  _/________________________\_______________________________________
# /                                                                  \
FROM  amazoncorretto:21 AS builder

#
# Build artefect
#
COPY rest-boot.jar /rest-boot.jar
# --------------------------------------------------------------------


#
# Create slim jre
#
RUN yum install -y binutils
RUN jlink --strip-java-debug-attributes \
          --strip-debug \
          --no-header-files \
          --no-man-pages \
          --compress=2 \
          --add-modules $(jdeps --recursive --ignore-missing-deps --print-module-deps /rest-boot.jar),java.xml,jdk.unsupported,java.sql,java.desktop,java.naming,java.management,java.security.jgss,java.instrument,jdk.dynalink,java.rmi,jdk.crypto.ec,jdk.crypto.cryptoki,jdk.localedata \
          --output customjre
# --------------------------------------------------------------------

#     ___________________
#    / Build Image Stage \
#  _/_____________________\__________________________________________
# /                                                                  \
FROM debian:12-slim

RUN groupadd -r gzoom && useradd -r -g gzoom gzoom
RUN mkdir -p /etc/gzoom-be && chown -R gzoom:gzoom /etc/gzoom-be
RUN mkdir -p /var/log/gzoom-be && chown -R gzoom:gzoom /var/log/gzoom-be
RUN apt-get update
RUN apt-get install -y fontconfig
RUN apt-get install -y ttf-dejavu-*
RUN apt-get install -y fonts-dejavu

# -------------------------------------------------------------------
# PATCH: GENERAZIONE LOCALE ITALIANA (fondamentale per BIRT + ICU)
# -------------------------------------------------------------------
RUN apt-get update && apt-get install -y locales && \
    locale-gen C.UTF-8

ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8
ENV LC_ALL=C.UTF-8
# -------------------------------------------------------------------

COPY --from=builder /rest-boot.jar /usr/bin/rest-boot.jar
COPY --from=builder /customjre /customjre

USER gzoom

CMD ["/bin/sh", "-c", "\
     /customjre/bin/java \
     -Dgzoom.conf.dir=/etc/gzoom-be \
     -Duser.language=${USER_LANGUAGE} \
     -Duser.country=${USER_COUNTRY} \
     -jar \
     /usr/bin/rest-boot.jar \
     --spring.config.additional-location=/etc/gzoom-be/gzoom-be.properties \
     --logging.config=/etc/gzoom-be/logback.xml \
     --logging.file=/var/log/gzoom-be/gzoom-be.log \
     " ]

# \                                                                  /
#  ------------------------------------------------------------------
