package it.mapsgroup.gzoom.mybatis.dto;

import java.math.BigDecimal;
import java.time.Instant;

public class AcctgTransInterface {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.stato
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String stato;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.data_source
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String dataSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.voucher_ref
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String voucherRef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.uom_descr
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String uomDescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.ref_date
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant refDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.gl_account_type_enum_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String glAccountTypeEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.gl_account_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String glAccountCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.amount
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.amount_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String amountCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.gl_fiscal_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String glFiscalTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.uorg_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String uorgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.uorg_role_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String uorgRoleTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.note
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.comments
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.product_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.work_effort_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String workEffortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.party_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String partyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.role_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String roleTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.from_date_competence
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant fromDateCompetence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.to_date_competence
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant toDateCompetence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.note_lang
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String noteLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.comments_lang
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String commentsLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_text01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String customText01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_text02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String customText02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_text03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String customText03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_text04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String customText04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_text05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private String customText05;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_date01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant customDate01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_date02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant customDate02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_date03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant customDate03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_date04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant customDate04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_date05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Instant customDate05;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_value01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Double customValue01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_value02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Double customValue02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_value03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Double customValue03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_value04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Double customValue04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.custom_value05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private Double customValue05;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_interface.seq
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    private BigDecimal seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.id
     *
     * @return the value of acctg_trans_interface.id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.id
     *
     * @param id the value for acctg_trans_interface.id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.stato
     *
     * @return the value of acctg_trans_interface.stato
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getStato() {
        return stato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.stato
     *
     * @param stato the value for acctg_trans_interface.stato
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setStato(String stato) {
        this.stato = stato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.data_source
     *
     * @return the value of acctg_trans_interface.data_source
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.data_source
     *
     * @param dataSource the value for acctg_trans_interface.data_source
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.voucher_ref
     *
     * @return the value of acctg_trans_interface.voucher_ref
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getVoucherRef() {
        return voucherRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.voucher_ref
     *
     * @param voucherRef the value for acctg_trans_interface.voucher_ref
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setVoucherRef(String voucherRef) {
        this.voucherRef = voucherRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.uom_descr
     *
     * @return the value of acctg_trans_interface.uom_descr
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getUomDescr() {
        return uomDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.uom_descr
     *
     * @param uomDescr the value for acctg_trans_interface.uom_descr
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setUomDescr(String uomDescr) {
        this.uomDescr = uomDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.ref_date
     *
     * @return the value of acctg_trans_interface.ref_date
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getRefDate() {
        return refDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.ref_date
     *
     * @param refDate the value for acctg_trans_interface.ref_date
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setRefDate(Instant refDate) {
        this.refDate = refDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.gl_account_type_enum_id
     *
     * @return the value of acctg_trans_interface.gl_account_type_enum_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getGlAccountTypeEnumId() {
        return glAccountTypeEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.gl_account_type_enum_id
     *
     * @param glAccountTypeEnumId the value for acctg_trans_interface.gl_account_type_enum_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setGlAccountTypeEnumId(String glAccountTypeEnumId) {
        this.glAccountTypeEnumId = glAccountTypeEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.gl_account_code
     *
     * @return the value of acctg_trans_interface.gl_account_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getGlAccountCode() {
        return glAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.gl_account_code
     *
     * @param glAccountCode the value for acctg_trans_interface.gl_account_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setGlAccountCode(String glAccountCode) {
        this.glAccountCode = glAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.amount
     *
     * @return the value of acctg_trans_interface.amount
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.amount
     *
     * @param amount the value for acctg_trans_interface.amount
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.amount_code
     *
     * @return the value of acctg_trans_interface.amount_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getAmountCode() {
        return amountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.amount_code
     *
     * @param amountCode the value for acctg_trans_interface.amount_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setAmountCode(String amountCode) {
        this.amountCode = amountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.gl_fiscal_type_id
     *
     * @return the value of acctg_trans_interface.gl_fiscal_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getGlFiscalTypeId() {
        return glFiscalTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.gl_fiscal_type_id
     *
     * @param glFiscalTypeId the value for acctg_trans_interface.gl_fiscal_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setGlFiscalTypeId(String glFiscalTypeId) {
        this.glFiscalTypeId = glFiscalTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.uorg_code
     *
     * @return the value of acctg_trans_interface.uorg_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getUorgCode() {
        return uorgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.uorg_code
     *
     * @param uorgCode the value for acctg_trans_interface.uorg_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setUorgCode(String uorgCode) {
        this.uorgCode = uorgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.uorg_role_type_id
     *
     * @return the value of acctg_trans_interface.uorg_role_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getUorgRoleTypeId() {
        return uorgRoleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.uorg_role_type_id
     *
     * @param uorgRoleTypeId the value for acctg_trans_interface.uorg_role_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setUorgRoleTypeId(String uorgRoleTypeId) {
        this.uorgRoleTypeId = uorgRoleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.note
     *
     * @return the value of acctg_trans_interface.note
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.note
     *
     * @param note the value for acctg_trans_interface.note
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.comments
     *
     * @return the value of acctg_trans_interface.comments
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.comments
     *
     * @param comments the value for acctg_trans_interface.comments
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.product_code
     *
     * @return the value of acctg_trans_interface.product_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.product_code
     *
     * @param productCode the value for acctg_trans_interface.product_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.work_effort_code
     *
     * @return the value of acctg_trans_interface.work_effort_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getWorkEffortCode() {
        return workEffortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.work_effort_code
     *
     * @param workEffortCode the value for acctg_trans_interface.work_effort_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setWorkEffortCode(String workEffortCode) {
        this.workEffortCode = workEffortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.party_code
     *
     * @return the value of acctg_trans_interface.party_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getPartyCode() {
        return partyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.party_code
     *
     * @param partyCode the value for acctg_trans_interface.party_code
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setPartyCode(String partyCode) {
        this.partyCode = partyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.role_type_id
     *
     * @return the value of acctg_trans_interface.role_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getRoleTypeId() {
        return roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.role_type_id
     *
     * @param roleTypeId the value for acctg_trans_interface.role_type_id
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setRoleTypeId(String roleTypeId) {
        this.roleTypeId = roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.from_date_competence
     *
     * @return the value of acctg_trans_interface.from_date_competence
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getFromDateCompetence() {
        return fromDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.from_date_competence
     *
     * @param fromDateCompetence the value for acctg_trans_interface.from_date_competence
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setFromDateCompetence(Instant fromDateCompetence) {
        this.fromDateCompetence = fromDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.to_date_competence
     *
     * @return the value of acctg_trans_interface.to_date_competence
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getToDateCompetence() {
        return toDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.to_date_competence
     *
     * @param toDateCompetence the value for acctg_trans_interface.to_date_competence
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setToDateCompetence(Instant toDateCompetence) {
        this.toDateCompetence = toDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.note_lang
     *
     * @return the value of acctg_trans_interface.note_lang
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getNoteLang() {
        return noteLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.note_lang
     *
     * @param noteLang the value for acctg_trans_interface.note_lang
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setNoteLang(String noteLang) {
        this.noteLang = noteLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.comments_lang
     *
     * @return the value of acctg_trans_interface.comments_lang
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getCommentsLang() {
        return commentsLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.comments_lang
     *
     * @param commentsLang the value for acctg_trans_interface.comments_lang
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCommentsLang(String commentsLang) {
        this.commentsLang = commentsLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_text01
     *
     * @return the value of acctg_trans_interface.custom_text01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getCustomText01() {
        return customText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_text01
     *
     * @param customText01 the value for acctg_trans_interface.custom_text01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomText01(String customText01) {
        this.customText01 = customText01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_text02
     *
     * @return the value of acctg_trans_interface.custom_text02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getCustomText02() {
        return customText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_text02
     *
     * @param customText02 the value for acctg_trans_interface.custom_text02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomText02(String customText02) {
        this.customText02 = customText02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_text03
     *
     * @return the value of acctg_trans_interface.custom_text03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getCustomText03() {
        return customText03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_text03
     *
     * @param customText03 the value for acctg_trans_interface.custom_text03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomText03(String customText03) {
        this.customText03 = customText03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_text04
     *
     * @return the value of acctg_trans_interface.custom_text04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getCustomText04() {
        return customText04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_text04
     *
     * @param customText04 the value for acctg_trans_interface.custom_text04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomText04(String customText04) {
        this.customText04 = customText04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_text05
     *
     * @return the value of acctg_trans_interface.custom_text05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public String getCustomText05() {
        return customText05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_text05
     *
     * @param customText05 the value for acctg_trans_interface.custom_text05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomText05(String customText05) {
        this.customText05 = customText05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_date01
     *
     * @return the value of acctg_trans_interface.custom_date01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getCustomDate01() {
        return customDate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_date01
     *
     * @param customDate01 the value for acctg_trans_interface.custom_date01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomDate01(Instant customDate01) {
        this.customDate01 = customDate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_date02
     *
     * @return the value of acctg_trans_interface.custom_date02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getCustomDate02() {
        return customDate02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_date02
     *
     * @param customDate02 the value for acctg_trans_interface.custom_date02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomDate02(Instant customDate02) {
        this.customDate02 = customDate02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_date03
     *
     * @return the value of acctg_trans_interface.custom_date03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getCustomDate03() {
        return customDate03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_date03
     *
     * @param customDate03 the value for acctg_trans_interface.custom_date03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomDate03(Instant customDate03) {
        this.customDate03 = customDate03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_date04
     *
     * @return the value of acctg_trans_interface.custom_date04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getCustomDate04() {
        return customDate04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_date04
     *
     * @param customDate04 the value for acctg_trans_interface.custom_date04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomDate04(Instant customDate04) {
        this.customDate04 = customDate04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_date05
     *
     * @return the value of acctg_trans_interface.custom_date05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Instant getCustomDate05() {
        return customDate05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_date05
     *
     * @param customDate05 the value for acctg_trans_interface.custom_date05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomDate05(Instant customDate05) {
        this.customDate05 = customDate05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_value01
     *
     * @return the value of acctg_trans_interface.custom_value01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Double getCustomValue01() {
        return customValue01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_value01
     *
     * @param customValue01 the value for acctg_trans_interface.custom_value01
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomValue01(Double customValue01) {
        this.customValue01 = customValue01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_value02
     *
     * @return the value of acctg_trans_interface.custom_value02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Double getCustomValue02() {
        return customValue02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_value02
     *
     * @param customValue02 the value for acctg_trans_interface.custom_value02
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomValue02(Double customValue02) {
        this.customValue02 = customValue02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_value03
     *
     * @return the value of acctg_trans_interface.custom_value03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Double getCustomValue03() {
        return customValue03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_value03
     *
     * @param customValue03 the value for acctg_trans_interface.custom_value03
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomValue03(Double customValue03) {
        this.customValue03 = customValue03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_value04
     *
     * @return the value of acctg_trans_interface.custom_value04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Double getCustomValue04() {
        return customValue04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_value04
     *
     * @param customValue04 the value for acctg_trans_interface.custom_value04
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomValue04(Double customValue04) {
        this.customValue04 = customValue04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.custom_value05
     *
     * @return the value of acctg_trans_interface.custom_value05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public Double getCustomValue05() {
        return customValue05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.custom_value05
     *
     * @param customValue05 the value for acctg_trans_interface.custom_value05
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setCustomValue05(Double customValue05) {
        this.customValue05 = customValue05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_interface.seq
     *
     * @return the value of acctg_trans_interface.seq
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public BigDecimal getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_interface.seq
     *
     * @param seq the value for acctg_trans_interface.seq
     *
     * @mbg.generated Wed Nov 29 12:00:22 CET 2023
     */
    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }
}