package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.LocalDate;
import java.time.Instant;

public class AcctgTransEntry implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.acctg_trans_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String acctgTransId;
    private AcctgTrans acctgTrans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.acctg_trans_entry_seq_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String acctgTransEntrySeqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.acctg_trans_entry_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String acctgTransEntryTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.description
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.voucher_ref
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String voucherRef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.role_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String roleTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.their_party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String theirPartyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.product_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.their_product_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String theirProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.inventory_item_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String inventoryItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.gl_account_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String glAccountTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.gl_account_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String glAccountId;
    private GlAccount glAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.organization_party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String organizationPartyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.amount
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.currency_uom_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String currencyUomId;
    private Uom currencyUom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.orig_amount
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double origAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.orig_currency_uom_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String origCurrencyUomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.debit_credit_flag
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String debitCreditFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.due_date
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private LocalDate dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.group_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.tax_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.reconcile_status_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String reconcileStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.settlement_term_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String settlementTermId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.is_summary
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String isSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.last_updated_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.last_updated_tx_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.created_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.created_tx_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.perf_amount_calc
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double perfAmountCalc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.amount_locked
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String amountLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.work_effort_snapshot_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String workEffortSnapshotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.snapshot_date
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant snapshotDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.work_effort_revision_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String workEffortRevisionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.description_lang
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String descriptionLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.last_modified_by_user_login
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.created_by_user_login
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.gl_fiscal_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String glFiscalTypeId;
    private GlFiscalType glFiscalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.from_date_competence
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant fromDateCompetence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.to_date_competence
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Instant toDateCompetence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.gl_account_fin_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String glAccountFinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.empl_position_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String emplPositionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.has_score_alert
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String hasScoreAlert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.perf_amount_target
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double perfAmountTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.perf_amount_actual
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double perfAmountActual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.perf_amount_min
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double perfAmountMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.perf_amount_max
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private Double perfAmountMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.check_amount1
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String checkAmount1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.check_amount2
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String checkAmount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.check_amount3
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String checkAmount3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acctg_trans_entry.text_value1
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    private String textValue1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.acctg_trans_id
     *
     * @return the value of acctg_trans_entry.acctg_trans_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getAcctgTransId() {
        return acctgTransId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.acctg_trans_id
     *
     * @param acctgTransId the value for acctg_trans_entry.acctg_trans_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setAcctgTransId(String acctgTransId) {
        this.acctgTransId = acctgTransId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.acctg_trans_entry_seq_id
     *
     * @return the value of acctg_trans_entry.acctg_trans_entry_seq_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getAcctgTransEntrySeqId() {
        return acctgTransEntrySeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.acctg_trans_entry_seq_id
     *
     * @param acctgTransEntrySeqId the value for acctg_trans_entry.acctg_trans_entry_seq_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setAcctgTransEntrySeqId(String acctgTransEntrySeqId) {
        this.acctgTransEntrySeqId = acctgTransEntrySeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.acctg_trans_entry_type_id
     *
     * @return the value of acctg_trans_entry.acctg_trans_entry_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getAcctgTransEntryTypeId() {
        return acctgTransEntryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.acctg_trans_entry_type_id
     *
     * @param acctgTransEntryTypeId the value for acctg_trans_entry.acctg_trans_entry_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setAcctgTransEntryTypeId(String acctgTransEntryTypeId) {
        this.acctgTransEntryTypeId = acctgTransEntryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.description
     *
     * @return the value of acctg_trans_entry.description
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.description
     *
     * @param description the value for acctg_trans_entry.description
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.voucher_ref
     *
     * @return the value of acctg_trans_entry.voucher_ref
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getVoucherRef() {
        return voucherRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.voucher_ref
     *
     * @param voucherRef the value for acctg_trans_entry.voucher_ref
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setVoucherRef(String voucherRef) {
        this.voucherRef = voucherRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.party_id
     *
     * @return the value of acctg_trans_entry.party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.party_id
     *
     * @param partyId the value for acctg_trans_entry.party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.role_type_id
     *
     * @return the value of acctg_trans_entry.role_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getRoleTypeId() {
        return roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.role_type_id
     *
     * @param roleTypeId the value for acctg_trans_entry.role_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setRoleTypeId(String roleTypeId) {
        this.roleTypeId = roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.their_party_id
     *
     * @return the value of acctg_trans_entry.their_party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getTheirPartyId() {
        return theirPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.their_party_id
     *
     * @param theirPartyId the value for acctg_trans_entry.their_party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setTheirPartyId(String theirPartyId) {
        this.theirPartyId = theirPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.product_id
     *
     * @return the value of acctg_trans_entry.product_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.product_id
     *
     * @param productId the value for acctg_trans_entry.product_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.their_product_id
     *
     * @return the value of acctg_trans_entry.their_product_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getTheirProductId() {
        return theirProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.their_product_id
     *
     * @param theirProductId the value for acctg_trans_entry.their_product_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setTheirProductId(String theirProductId) {
        this.theirProductId = theirProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.inventory_item_id
     *
     * @return the value of acctg_trans_entry.inventory_item_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getInventoryItemId() {
        return inventoryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.inventory_item_id
     *
     * @param inventoryItemId the value for acctg_trans_entry.inventory_item_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setInventoryItemId(String inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.gl_account_type_id
     *
     * @return the value of acctg_trans_entry.gl_account_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getGlAccountTypeId() {
        return glAccountTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.gl_account_type_id
     *
     * @param glAccountTypeId the value for acctg_trans_entry.gl_account_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setGlAccountTypeId(String glAccountTypeId) {
        this.glAccountTypeId = glAccountTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.gl_account_id
     *
     * @return the value of acctg_trans_entry.gl_account_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getGlAccountId() {
        return glAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.gl_account_id
     *
     * @param glAccountId the value for acctg_trans_entry.gl_account_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setGlAccountId(String glAccountId) {
        this.glAccountId = glAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.organization_party_id
     *
     * @return the value of acctg_trans_entry.organization_party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getOrganizationPartyId() {
        return organizationPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.organization_party_id
     *
     * @param organizationPartyId the value for acctg_trans_entry.organization_party_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setOrganizationPartyId(String organizationPartyId) {
        this.organizationPartyId = organizationPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.amount
     *
     * @return the value of acctg_trans_entry.amount
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.amount
     *
     * @param amount the value for acctg_trans_entry.amount
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.currency_uom_id
     *
     * @return the value of acctg_trans_entry.currency_uom_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getCurrencyUomId() {
        return currencyUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.currency_uom_id
     *
     * @param currencyUomId the value for acctg_trans_entry.currency_uom_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCurrencyUomId(String currencyUomId) {
        this.currencyUomId = currencyUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.orig_amount
     *
     * @return the value of acctg_trans_entry.orig_amount
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getOrigAmount() {
        return origAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.orig_amount
     *
     * @param origAmount the value for acctg_trans_entry.orig_amount
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setOrigAmount(Double origAmount) {
        this.origAmount = origAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.orig_currency_uom_id
     *
     * @return the value of acctg_trans_entry.orig_currency_uom_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getOrigCurrencyUomId() {
        return origCurrencyUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.orig_currency_uom_id
     *
     * @param origCurrencyUomId the value for acctg_trans_entry.orig_currency_uom_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setOrigCurrencyUomId(String origCurrencyUomId) {
        this.origCurrencyUomId = origCurrencyUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.debit_credit_flag
     *
     * @return the value of acctg_trans_entry.debit_credit_flag
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getDebitCreditFlag() {
        return debitCreditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.debit_credit_flag
     *
     * @param debitCreditFlag the value for acctg_trans_entry.debit_credit_flag
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setDebitCreditFlag(String debitCreditFlag) {
        this.debitCreditFlag = debitCreditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.due_date
     *
     * @return the value of acctg_trans_entry.due_date
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.due_date
     *
     * @param dueDate the value for acctg_trans_entry.due_date
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.group_id
     *
     * @return the value of acctg_trans_entry.group_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.group_id
     *
     * @param groupId the value for acctg_trans_entry.group_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.tax_id
     *
     * @return the value of acctg_trans_entry.tax_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.tax_id
     *
     * @param taxId the value for acctg_trans_entry.tax_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setTaxId(String taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.reconcile_status_id
     *
     * @return the value of acctg_trans_entry.reconcile_status_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getReconcileStatusId() {
        return reconcileStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.reconcile_status_id
     *
     * @param reconcileStatusId the value for acctg_trans_entry.reconcile_status_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setReconcileStatusId(String reconcileStatusId) {
        this.reconcileStatusId = reconcileStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.settlement_term_id
     *
     * @return the value of acctg_trans_entry.settlement_term_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getSettlementTermId() {
        return settlementTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.settlement_term_id
     *
     * @param settlementTermId the value for acctg_trans_entry.settlement_term_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setSettlementTermId(String settlementTermId) {
        this.settlementTermId = settlementTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.is_summary
     *
     * @return the value of acctg_trans_entry.is_summary
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getIsSummary() {
        return isSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.is_summary
     *
     * @param isSummary the value for acctg_trans_entry.is_summary
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setIsSummary(String isSummary) {
        this.isSummary = isSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.last_updated_stamp
     *
     * @return the value of acctg_trans_entry.last_updated_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for acctg_trans_entry.last_updated_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.last_updated_tx_stamp
     *
     * @return the value of acctg_trans_entry.last_updated_tx_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for acctg_trans_entry.last_updated_tx_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.created_stamp
     *
     * @return the value of acctg_trans_entry.created_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.created_stamp
     *
     * @param createdStamp the value for acctg_trans_entry.created_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.created_tx_stamp
     *
     * @return the value of acctg_trans_entry.created_tx_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.created_tx_stamp
     *
     * @param createdTxStamp the value for acctg_trans_entry.created_tx_stamp
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.perf_amount_calc
     *
     * @return the value of acctg_trans_entry.perf_amount_calc
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getPerfAmountCalc() {
        return perfAmountCalc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.perf_amount_calc
     *
     * @param perfAmountCalc the value for acctg_trans_entry.perf_amount_calc
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setPerfAmountCalc(Double perfAmountCalc) {
        this.perfAmountCalc = perfAmountCalc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.amount_locked
     *
     * @return the value of acctg_trans_entry.amount_locked
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getAmountLocked() {
        return amountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.amount_locked
     *
     * @param amountLocked the value for acctg_trans_entry.amount_locked
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setAmountLocked(String amountLocked) {
        this.amountLocked = amountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.work_effort_snapshot_id
     *
     * @return the value of acctg_trans_entry.work_effort_snapshot_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getWorkEffortSnapshotId() {
        return workEffortSnapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.work_effort_snapshot_id
     *
     * @param workEffortSnapshotId the value for acctg_trans_entry.work_effort_snapshot_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setWorkEffortSnapshotId(String workEffortSnapshotId) {
        this.workEffortSnapshotId = workEffortSnapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.snapshot_date
     *
     * @return the value of acctg_trans_entry.snapshot_date
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getSnapshotDate() {
        return snapshotDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.snapshot_date
     *
     * @param snapshotDate the value for acctg_trans_entry.snapshot_date
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setSnapshotDate(Instant snapshotDate) {
        this.snapshotDate = snapshotDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.work_effort_revision_id
     *
     * @return the value of acctg_trans_entry.work_effort_revision_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getWorkEffortRevisionId() {
        return workEffortRevisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.work_effort_revision_id
     *
     * @param workEffortRevisionId the value for acctg_trans_entry.work_effort_revision_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setWorkEffortRevisionId(String workEffortRevisionId) {
        this.workEffortRevisionId = workEffortRevisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.description_lang
     *
     * @return the value of acctg_trans_entry.description_lang
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getDescriptionLang() {
        return descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.description_lang
     *
     * @param descriptionLang the value for acctg_trans_entry.description_lang
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setDescriptionLang(String descriptionLang) {
        this.descriptionLang = descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.last_modified_by_user_login
     *
     * @return the value of acctg_trans_entry.last_modified_by_user_login
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for acctg_trans_entry.last_modified_by_user_login
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.created_by_user_login
     *
     * @return the value of acctg_trans_entry.created_by_user_login
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.created_by_user_login
     *
     * @param createdByUserLogin the value for acctg_trans_entry.created_by_user_login
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.gl_fiscal_type_id
     *
     * @return the value of acctg_trans_entry.gl_fiscal_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getGlFiscalTypeId() {
        return glFiscalTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.gl_fiscal_type_id
     *
     * @param glFiscalTypeId the value for acctg_trans_entry.gl_fiscal_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setGlFiscalTypeId(String glFiscalTypeId) {
        this.glFiscalTypeId = glFiscalTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.from_date_competence
     *
     * @return the value of acctg_trans_entry.from_date_competence
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getFromDateCompetence() {
        return fromDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.from_date_competence
     *
     * @param fromDateCompetence the value for acctg_trans_entry.from_date_competence
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setFromDateCompetence(Instant fromDateCompetence) {
        this.fromDateCompetence = fromDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.to_date_competence
     *
     * @return the value of acctg_trans_entry.to_date_competence
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Instant getToDateCompetence() {
        return toDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.to_date_competence
     *
     * @param toDateCompetence the value for acctg_trans_entry.to_date_competence
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setToDateCompetence(Instant toDateCompetence) {
        this.toDateCompetence = toDateCompetence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.gl_account_fin_id
     *
     * @return the value of acctg_trans_entry.gl_account_fin_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getGlAccountFinId() {
        return glAccountFinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.gl_account_fin_id
     *
     * @param glAccountFinId the value for acctg_trans_entry.gl_account_fin_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setGlAccountFinId(String glAccountFinId) {
        this.glAccountFinId = glAccountFinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.empl_position_type_id
     *
     * @return the value of acctg_trans_entry.empl_position_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getEmplPositionTypeId() {
        return emplPositionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.empl_position_type_id
     *
     * @param emplPositionTypeId the value for acctg_trans_entry.empl_position_type_id
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setEmplPositionTypeId(String emplPositionTypeId) {
        this.emplPositionTypeId = emplPositionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.has_score_alert
     *
     * @return the value of acctg_trans_entry.has_score_alert
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getHasScoreAlert() {
        return hasScoreAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.has_score_alert
     *
     * @param hasScoreAlert the value for acctg_trans_entry.has_score_alert
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setHasScoreAlert(String hasScoreAlert) {
        this.hasScoreAlert = hasScoreAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.perf_amount_target
     *
     * @return the value of acctg_trans_entry.perf_amount_target
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getPerfAmountTarget() {
        return perfAmountTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.perf_amount_target
     *
     * @param perfAmountTarget the value for acctg_trans_entry.perf_amount_target
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setPerfAmountTarget(Double perfAmountTarget) {
        this.perfAmountTarget = perfAmountTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.perf_amount_actual
     *
     * @return the value of acctg_trans_entry.perf_amount_actual
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getPerfAmountActual() {
        return perfAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.perf_amount_actual
     *
     * @param perfAmountActual the value for acctg_trans_entry.perf_amount_actual
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setPerfAmountActual(Double perfAmountActual) {
        this.perfAmountActual = perfAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.perf_amount_min
     *
     * @return the value of acctg_trans_entry.perf_amount_min
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getPerfAmountMin() {
        return perfAmountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.perf_amount_min
     *
     * @param perfAmountMin the value for acctg_trans_entry.perf_amount_min
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setPerfAmountMin(Double perfAmountMin) {
        this.perfAmountMin = perfAmountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.perf_amount_max
     *
     * @return the value of acctg_trans_entry.perf_amount_max
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public Double getPerfAmountMax() {
        return perfAmountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.perf_amount_max
     *
     * @param perfAmountMax the value for acctg_trans_entry.perf_amount_max
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setPerfAmountMax(Double perfAmountMax) {
        this.perfAmountMax = perfAmountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.check_amount1
     *
     * @return the value of acctg_trans_entry.check_amount1
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getCheckAmount1() {
        return checkAmount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.check_amount1
     *
     * @param checkAmount1 the value for acctg_trans_entry.check_amount1
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCheckAmount1(String checkAmount1) {
        this.checkAmount1 = checkAmount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.check_amount2
     *
     * @return the value of acctg_trans_entry.check_amount2
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getCheckAmount2() {
        return checkAmount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.check_amount2
     *
     * @param checkAmount2 the value for acctg_trans_entry.check_amount2
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCheckAmount2(String checkAmount2) {
        this.checkAmount2 = checkAmount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.check_amount3
     *
     * @return the value of acctg_trans_entry.check_amount3
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getCheckAmount3() {
        return checkAmount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.check_amount3
     *
     * @param checkAmount3 the value for acctg_trans_entry.check_amount3
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setCheckAmount3(String checkAmount3) {
        this.checkAmount3 = checkAmount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acctg_trans_entry.text_value1
     *
     * @return the value of acctg_trans_entry.text_value1
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public String getTextValue1() {
        return textValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acctg_trans_entry.text_value1
     *
     * @param textValue1 the value for acctg_trans_entry.text_value1
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    public void setTextValue1(String textValue1) {
        this.textValue1 = textValue1;
    }

    public GlAccount getGlAccount() {
        return glAccount;
    }

    public void setGlAccount(GlAccount glAccount) {
        this.glAccount = glAccount;
    }

    public AcctgTrans getAcctgTrans() {
        return acctgTrans;
    }

    public void setAcctgTrans(AcctgTrans acctgTrans) {
        this.acctgTrans = acctgTrans;
    }

    public Uom getCurrencyUom() {
        return currencyUom;
    }

    public void setCurrencyUom(Uom currencyUom) {
        this.currencyUom = currencyUom;
    }

    public GlFiscalType getGlFiscalType() {
        return glFiscalType;
    }

    public void setGlFiscalType(GlFiscalType glFiscalType) {
        this.glFiscalType = glFiscalType;
    }
}