package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class ContentType implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String contentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.parent_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String parentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.has_table
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String hasTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.description
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.created_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.content_type_id
     *
     * @return the value of content_type.content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getContentTypeId() {
        return contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.content_type_id
     *
     * @param contentTypeId the value for content_type.content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setContentTypeId(String contentTypeId) {
        this.contentTypeId = contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.parent_type_id
     *
     * @return the value of content_type.parent_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getParentTypeId() {
        return parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.parent_type_id
     *
     * @param parentTypeId the value for content_type.parent_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setParentTypeId(String parentTypeId) {
        this.parentTypeId = parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.has_table
     *
     * @return the value of content_type.has_table
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getHasTable() {
        return hasTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.has_table
     *
     * @param hasTable the value for content_type.has_table
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setHasTable(String hasTable) {
        this.hasTable = hasTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.description
     *
     * @return the value of content_type.description
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.description
     *
     * @param description the value for content_type.description
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.last_updated_stamp
     *
     * @return the value of content_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for content_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.last_updated_tx_stamp
     *
     * @return the value of content_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for content_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.created_stamp
     *
     * @return the value of content_type.created_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.created_stamp
     *
     * @param createdStamp the value for content_type.created_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_type.created_tx_stamp
     *
     * @return the value of content_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_type.created_tx_stamp
     *
     * @param createdTxStamp the value for content_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
}