package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class CustomMethod implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.custom_method_id
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private String customMethodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.custom_method_type_id
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private String customMethodTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.custom_method_name
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private String customMethodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.description
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.last_updated_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.created_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_method.created_tx_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    private Instant createdTxStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.custom_method_id
     *
     * @return the value of custom_method.custom_method_id
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public String getCustomMethodId() {
        return customMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.custom_method_id
     *
     * @param customMethodId the value for custom_method.custom_method_id
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setCustomMethodId(String customMethodId) {
        this.customMethodId = customMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.custom_method_type_id
     *
     * @return the value of custom_method.custom_method_type_id
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public String getCustomMethodTypeId() {
        return customMethodTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.custom_method_type_id
     *
     * @param customMethodTypeId the value for custom_method.custom_method_type_id
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setCustomMethodTypeId(String customMethodTypeId) {
        this.customMethodTypeId = customMethodTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.custom_method_name
     *
     * @return the value of custom_method.custom_method_name
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public String getCustomMethodName() {
        return customMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.custom_method_name
     *
     * @param customMethodName the value for custom_method.custom_method_name
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setCustomMethodName(String customMethodName) {
        this.customMethodName = customMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.description
     *
     * @return the value of custom_method.description
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.description
     *
     * @param description the value for custom_method.description
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.last_updated_stamp
     *
     * @return the value of custom_method.last_updated_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for custom_method.last_updated_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.last_updated_tx_stamp
     *
     * @return the value of custom_method.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for custom_method.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.created_stamp
     *
     * @return the value of custom_method.created_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.created_stamp
     *
     * @param createdStamp the value for custom_method.created_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_method.created_tx_stamp
     *
     * @return the value of custom_method.created_tx_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_method.created_tx_stamp
     *
     * @param createdTxStamp the value for custom_method.created_tx_stamp
     *
     * @mbg.generated Thu Nov 16 09:24:55 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
}