package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class DataSourceType implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.data_source_type_id
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private String dataSourceTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.description
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.created_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_type.created_by_user_login
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    private String createdByUserLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.data_source_type_id
     *
     * @return the value of data_source_type.data_source_type_id
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public String getDataSourceTypeId() {
        return dataSourceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.data_source_type_id
     *
     * @param dataSourceTypeId the value for data_source_type.data_source_type_id
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setDataSourceTypeId(String dataSourceTypeId) {
        this.dataSourceTypeId = dataSourceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.description
     *
     * @return the value of data_source_type.description
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.description
     *
     * @param description the value for data_source_type.description
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.last_updated_stamp
     *
     * @return the value of data_source_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for data_source_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.last_updated_tx_stamp
     *
     * @return the value of data_source_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for data_source_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.created_stamp
     *
     * @return the value of data_source_type.created_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.created_stamp
     *
     * @param createdStamp the value for data_source_type.created_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.created_tx_stamp
     *
     * @return the value of data_source_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.created_tx_stamp
     *
     * @param createdTxStamp the value for data_source_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.last_modified_by_user_login
     *
     * @return the value of data_source_type.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for data_source_type.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source_type.created_by_user_login
     *
     * @return the value of data_source_type.created_by_user_login
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source_type.created_by_user_login
     *
     * @param createdByUserLogin the value for data_source_type.created_by_user_login
     *
     * @mbg.generated Thu Oct 05 12:31:13 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }
}