package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.math.BigDecimal;
import java.time.Instant;

public class JobLog implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.job_log_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String jobLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.job_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.user_login_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String userLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.service_type_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String serviceTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.service_name
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.description
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.log_date
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private Instant logDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.log_end_date
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private Instant logEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.record_elaborated
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private BigDecimal recordElaborated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.warning_messages
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private BigDecimal warningMessages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.blocking_errors
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private BigDecimal blockingErrors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.elab_ref1
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String elabRef1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.session_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.created_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.last_updated_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.created_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.created_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    private Instant createdTxStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.job_log_id
     *
     * @return the value of job_log.job_log_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getJobLogId() {
        return jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.job_log_id
     *
     * @param jobLogId the value for job_log.job_log_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setJobLogId(String jobLogId) {
        this.jobLogId = jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.job_id
     *
     * @return the value of job_log.job_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.job_id
     *
     * @param jobId the value for job_log.job_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.user_login_id
     *
     * @return the value of job_log.user_login_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getUserLoginId() {
        return userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.user_login_id
     *
     * @param userLoginId the value for job_log.user_login_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.service_type_id
     *
     * @return the value of job_log.service_type_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getServiceTypeId() {
        return serviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.service_type_id
     *
     * @param serviceTypeId the value for job_log.service_type_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setServiceTypeId(String serviceTypeId) {
        this.serviceTypeId = serviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.service_name
     *
     * @return the value of job_log.service_name
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.service_name
     *
     * @param serviceName the value for job_log.service_name
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.description
     *
     * @return the value of job_log.description
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.description
     *
     * @param description the value for job_log.description
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.log_date
     *
     * @return the value of job_log.log_date
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public Instant getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.log_date
     *
     * @param logDate the value for job_log.log_date
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setLogDate(Instant logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.log_end_date
     *
     * @return the value of job_log.log_end_date
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public Instant getLogEndDate() {
        return logEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.log_end_date
     *
     * @param logEndDate the value for job_log.log_end_date
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setLogEndDate(Instant logEndDate) {
        this.logEndDate = logEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.record_elaborated
     *
     * @return the value of job_log.record_elaborated
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public BigDecimal getRecordElaborated() {
        return recordElaborated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.record_elaborated
     *
     * @param recordElaborated the value for job_log.record_elaborated
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setRecordElaborated(BigDecimal recordElaborated) {
        this.recordElaborated = recordElaborated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.warning_messages
     *
     * @return the value of job_log.warning_messages
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public BigDecimal getWarningMessages() {
        return warningMessages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.warning_messages
     *
     * @param warningMessages the value for job_log.warning_messages
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setWarningMessages(BigDecimal warningMessages) {
        this.warningMessages = warningMessages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.blocking_errors
     *
     * @return the value of job_log.blocking_errors
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public BigDecimal getBlockingErrors() {
        return blockingErrors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.blocking_errors
     *
     * @param blockingErrors the value for job_log.blocking_errors
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setBlockingErrors(BigDecimal blockingErrors) {
        this.blockingErrors = blockingErrors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.elab_ref1
     *
     * @return the value of job_log.elab_ref1
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getElabRef1() {
        return elabRef1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.elab_ref1
     *
     * @param elabRef1 the value for job_log.elab_ref1
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setElabRef1(String elabRef1) {
        this.elabRef1 = elabRef1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.session_id
     *
     * @return the value of job_log.session_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.session_id
     *
     * @param sessionId the value for job_log.session_id
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.last_modified_by_user_login
     *
     * @return the value of job_log.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for job_log.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.created_by_user_login
     *
     * @return the value of job_log.created_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.created_by_user_login
     *
     * @param createdByUserLogin the value for job_log.created_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.last_updated_stamp
     *
     * @return the value of job_log.last_updated_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for job_log.last_updated_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.last_updated_tx_stamp
     *
     * @return the value of job_log.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for job_log.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.created_stamp
     *
     * @return the value of job_log.created_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.created_stamp
     *
     * @param createdStamp the value for job_log.created_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.created_tx_stamp
     *
     * @return the value of job_log.created_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.created_tx_stamp
     *
     * @param createdTxStamp the value for job_log.created_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:36:59 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
}