package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class JobLogLog implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.job_log_log_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String jobLogLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.job_log_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String jobLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.log_type_enum_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String logTypeEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.log_code
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String logCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.log_message
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String logMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.value_ref1
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String valueRef1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.value_ref2
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String valueRef2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.value_ref3
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String valueRef3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.log_message_long
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String logMessageLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.value_pk1
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String valuePk1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.created_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.last_updated_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.created_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log_log.created_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    private Instant createdTxStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.job_log_log_id
     *
     * @return the value of job_log_log.job_log_log_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getJobLogLogId() {
        return jobLogLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.job_log_log_id
     *
     * @param jobLogLogId the value for job_log_log.job_log_log_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setJobLogLogId(String jobLogLogId) {
        this.jobLogLogId = jobLogLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.job_log_id
     *
     * @return the value of job_log_log.job_log_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getJobLogId() {
        return jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.job_log_id
     *
     * @param jobLogId the value for job_log_log.job_log_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setJobLogId(String jobLogId) {
        this.jobLogId = jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.log_type_enum_id
     *
     * @return the value of job_log_log.log_type_enum_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getLogTypeEnumId() {
        return logTypeEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.log_type_enum_id
     *
     * @param logTypeEnumId the value for job_log_log.log_type_enum_id
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLogTypeEnumId(String logTypeEnumId) {
        this.logTypeEnumId = logTypeEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.log_code
     *
     * @return the value of job_log_log.log_code
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getLogCode() {
        return logCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.log_code
     *
     * @param logCode the value for job_log_log.log_code
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLogCode(String logCode) {
        this.logCode = logCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.log_message
     *
     * @return the value of job_log_log.log_message
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getLogMessage() {
        return logMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.log_message
     *
     * @param logMessage the value for job_log_log.log_message
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLogMessage(String logMessage) {
        this.logMessage = logMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.value_ref1
     *
     * @return the value of job_log_log.value_ref1
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getValueRef1() {
        return valueRef1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.value_ref1
     *
     * @param valueRef1 the value for job_log_log.value_ref1
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setValueRef1(String valueRef1) {
        this.valueRef1 = valueRef1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.value_ref2
     *
     * @return the value of job_log_log.value_ref2
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getValueRef2() {
        return valueRef2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.value_ref2
     *
     * @param valueRef2 the value for job_log_log.value_ref2
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setValueRef2(String valueRef2) {
        this.valueRef2 = valueRef2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.value_ref3
     *
     * @return the value of job_log_log.value_ref3
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getValueRef3() {
        return valueRef3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.value_ref3
     *
     * @param valueRef3 the value for job_log_log.value_ref3
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setValueRef3(String valueRef3) {
        this.valueRef3 = valueRef3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.log_message_long
     *
     * @return the value of job_log_log.log_message_long
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getLogMessageLong() {
        return logMessageLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.log_message_long
     *
     * @param logMessageLong the value for job_log_log.log_message_long
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLogMessageLong(String logMessageLong) {
        this.logMessageLong = logMessageLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.value_pk1
     *
     * @return the value of job_log_log.value_pk1
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getValuePk1() {
        return valuePk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.value_pk1
     *
     * @param valuePk1 the value for job_log_log.value_pk1
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setValuePk1(String valuePk1) {
        this.valuePk1 = valuePk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.last_modified_by_user_login
     *
     * @return the value of job_log_log.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for job_log_log.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.created_by_user_login
     *
     * @return the value of job_log_log.created_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.created_by_user_login
     *
     * @param createdByUserLogin the value for job_log_log.created_by_user_login
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.last_updated_stamp
     *
     * @return the value of job_log_log.last_updated_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for job_log_log.last_updated_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.last_updated_tx_stamp
     *
     * @return the value of job_log_log.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for job_log_log.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.created_stamp
     *
     * @return the value of job_log_log.created_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.created_stamp
     *
     * @param createdStamp the value for job_log_log.created_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log_log.created_tx_stamp
     *
     * @return the value of job_log_log.created_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log_log.created_tx_stamp
     *
     * @param createdTxStamp the value for job_log_log.created_tx_stamp
     *
     * @mbg.generated Wed Nov 29 12:32:30 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
}