package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.io.Serializable;
import java.time.Instant;

public class Party implements AbstractIdentity, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String partyId;
    private PartyParentRole partyParentRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_type_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String partyTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.external_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String externalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.preferred_currency_uom_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String preferredCurrencyUomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.description
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.status_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.created_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.created_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.last_modified_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.last_modified_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.data_source_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String dataSourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.is_unread
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String isUnread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.last_updated_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.created_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.created_tx_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.fiscal_code
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String fiscalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.vat_code
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String vatCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_name
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String partyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.description_lang
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String descriptionLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.end_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private Instant endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.party_name_lang
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    private String partyNameLang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_id
     *
     * @return the value of party.party_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_id
     *
     * @param partyId the value for party.party_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_type_id
     *
     * @return the value of party.party_type_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getPartyTypeId() {
        return partyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_type_id
     *
     * @param partyTypeId the value for party.party_type_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setPartyTypeId(String partyTypeId) {
        this.partyTypeId = partyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.external_id
     *
     * @return the value of party.external_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.external_id
     *
     * @param externalId the value for party.external_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.preferred_currency_uom_id
     *
     * @return the value of party.preferred_currency_uom_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getPreferredCurrencyUomId() {
        return preferredCurrencyUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.preferred_currency_uom_id
     *
     * @param preferredCurrencyUomId the value for party.preferred_currency_uom_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setPreferredCurrencyUomId(String preferredCurrencyUomId) {
        this.preferredCurrencyUomId = preferredCurrencyUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.description
     *
     * @return the value of party.description
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.description
     *
     * @param description the value for party.description
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.status_id
     *
     * @return the value of party.status_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.status_id
     *
     * @param statusId the value for party.status_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.created_date
     *
     * @return the value of party.created_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.created_date
     *
     * @param createdDate the value for party.created_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setCreatedDate(Instant createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.created_by_user_login
     *
     * @return the value of party.created_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.created_by_user_login
     *
     * @param createdByUserLogin the value for party.created_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.last_modified_date
     *
     * @return the value of party.last_modified_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.last_modified_date
     *
     * @param lastModifiedDate the value for party.last_modified_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setLastModifiedDate(Instant lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.last_modified_by_user_login
     *
     * @return the value of party.last_modified_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for party.last_modified_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.data_source_id
     *
     * @return the value of party.data_source_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.data_source_id
     *
     * @param dataSourceId the value for party.data_source_id
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.is_unread
     *
     * @return the value of party.is_unread
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getIsUnread() {
        return isUnread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.is_unread
     *
     * @param isUnread the value for party.is_unread
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setIsUnread(String isUnread) {
        this.isUnread = isUnread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.last_updated_stamp
     *
     * @return the value of party.last_updated_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for party.last_updated_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.last_updated_tx_stamp
     *
     * @return the value of party.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for party.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.created_stamp
     *
     * @return the value of party.created_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.created_stamp
     *
     * @param createdStamp the value for party.created_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.created_tx_stamp
     *
     * @return the value of party.created_tx_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.created_tx_stamp
     *
     * @param createdTxStamp the value for party.created_tx_stamp
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.fiscal_code
     *
     * @return the value of party.fiscal_code
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getFiscalCode() {
        return fiscalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.fiscal_code
     *
     * @param fiscalCode the value for party.fiscal_code
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setFiscalCode(String fiscalCode) {
        this.fiscalCode = fiscalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.vat_code
     *
     * @return the value of party.vat_code
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getVatCode() {
        return vatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.vat_code
     *
     * @param vatCode the value for party.vat_code
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setVatCode(String vatCode) {
        this.vatCode = vatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_name
     *
     * @return the value of party.party_name
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getPartyName() {
        return partyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_name
     *
     * @param partyName the value for party.party_name
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.description_lang
     *
     * @return the value of party.description_lang
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getDescriptionLang() {
        return descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.description_lang
     *
     * @param descriptionLang the value for party.description_lang
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setDescriptionLang(String descriptionLang) {
        this.descriptionLang = descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.end_date
     *
     * @return the value of party.end_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public Instant getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.end_date
     *
     * @param endDate the value for party.end_date
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setEndDate(Instant endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.party_name_lang
     *
     * @return the value of party.party_name_lang
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public String getPartyNameLang() {
        return partyNameLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.party_name_lang
     *
     * @param partyNameLang the value for party.party_name_lang
     *
     * @mbg.generated Tue Oct 17 16:05:59 CEST 2023
     */
    public void setPartyNameLang(String partyNameLang) {
        this.partyNameLang = partyNameLang;
    }

    public PartyParentRole getPartyParentRole() {
        return partyParentRole;
    }

    public void setPartyParentRole(PartyParentRole partyParentRole) {
        this.partyParentRole = partyParentRole;
    }
}