package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.Instant;

public class Person implements AbstractIdentity, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.party_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.salutation
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String salutation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.first_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.middle_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String middleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.personal_title
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String personalTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.suffix
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.nickname
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.first_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String firstNameLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.middle_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String middleNameLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String lastNameLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.other_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String otherLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.member_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.gender
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.birth_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private LocalDate birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.deceased_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private LocalDate deceasedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.height
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.weight
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.mothers_maiden_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String mothersMaidenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.marital_status
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.social_security_number
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String socialSecurityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.passport_number
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String passportNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.passport_expire_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private LocalDate passportExpireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.total_years_work_experience
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Double totalYearsWorkExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.comments
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.employment_status_enum_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String employmentStatusEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.residence_status_enum_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String residenceStatusEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.occupation
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.years_with_employer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private BigDecimal yearsWithEmployer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.months_with_employer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private BigDecimal monthsWithEmployer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.existing_customer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String existingCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.card_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_updated_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.created_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.created_tx_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.birth_place
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String birthPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.birth_country
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String birthCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.number_of_child
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private BigDecimal numberOfChild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.empl_position_type_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String emplPositionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.empl_position_type_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private Instant emplPositionTypeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.employment_amount
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private BigDecimal employmentAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.created_by_user_login
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_position
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    private String personPosition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.party_id
     *
     * @return the value of person.party_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.party_id
     *
     * @param partyId the value for person.party_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.salutation
     *
     * @return the value of person.salutation
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.salutation
     *
     * @param salutation the value for person.salutation
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.first_name
     *
     * @return the value of person.first_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.first_name
     *
     * @param firstName the value for person.first_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.middle_name
     *
     * @return the value of person.middle_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.middle_name
     *
     * @param middleName the value for person.middle_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_name
     *
     * @return the value of person.last_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_name
     *
     * @param lastName the value for person.last_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.personal_title
     *
     * @return the value of person.personal_title
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getPersonalTitle() {
        return personalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.personal_title
     *
     * @param personalTitle the value for person.personal_title
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setPersonalTitle(String personalTitle) {
        this.personalTitle = personalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.suffix
     *
     * @return the value of person.suffix
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.suffix
     *
     * @param suffix the value for person.suffix
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.nickname
     *
     * @return the value of person.nickname
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.nickname
     *
     * @param nickname the value for person.nickname
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.first_name_local
     *
     * @return the value of person.first_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getFirstNameLocal() {
        return firstNameLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.first_name_local
     *
     * @param firstNameLocal the value for person.first_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setFirstNameLocal(String firstNameLocal) {
        this.firstNameLocal = firstNameLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.middle_name_local
     *
     * @return the value of person.middle_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getMiddleNameLocal() {
        return middleNameLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.middle_name_local
     *
     * @param middleNameLocal the value for person.middle_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setMiddleNameLocal(String middleNameLocal) {
        this.middleNameLocal = middleNameLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_name_local
     *
     * @return the value of person.last_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getLastNameLocal() {
        return lastNameLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_name_local
     *
     * @param lastNameLocal the value for person.last_name_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setLastNameLocal(String lastNameLocal) {
        this.lastNameLocal = lastNameLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.other_local
     *
     * @return the value of person.other_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getOtherLocal() {
        return otherLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.other_local
     *
     * @param otherLocal the value for person.other_local
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setOtherLocal(String otherLocal) {
        this.otherLocal = otherLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.member_id
     *
     * @return the value of person.member_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.member_id
     *
     * @param memberId the value for person.member_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.gender
     *
     * @return the value of person.gender
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.gender
     *
     * @param gender the value for person.gender
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.birth_date
     *
     * @return the value of person.birth_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.birth_date
     *
     * @param birthDate the value for person.birth_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.deceased_date
     *
     * @return the value of person.deceased_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public LocalDate getDeceasedDate() {
        return deceasedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.deceased_date
     *
     * @param deceasedDate the value for person.deceased_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setDeceasedDate(LocalDate deceasedDate) {
        this.deceasedDate = deceasedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.height
     *
     * @return the value of person.height
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.height
     *
     * @param height the value for person.height
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.weight
     *
     * @return the value of person.weight
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.weight
     *
     * @param weight the value for person.weight
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.mothers_maiden_name
     *
     * @return the value of person.mothers_maiden_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getMothersMaidenName() {
        return mothersMaidenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.mothers_maiden_name
     *
     * @param mothersMaidenName the value for person.mothers_maiden_name
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setMothersMaidenName(String mothersMaidenName) {
        this.mothersMaidenName = mothersMaidenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.marital_status
     *
     * @return the value of person.marital_status
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.marital_status
     *
     * @param maritalStatus the value for person.marital_status
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.social_security_number
     *
     * @return the value of person.social_security_number
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.social_security_number
     *
     * @param socialSecurityNumber the value for person.social_security_number
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setSocialSecurityNumber(String socialSecurityNumber) {
        this.socialSecurityNumber = socialSecurityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.passport_number
     *
     * @return the value of person.passport_number
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.passport_number
     *
     * @param passportNumber the value for person.passport_number
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.passport_expire_date
     *
     * @return the value of person.passport_expire_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public LocalDate getPassportExpireDate() {
        return passportExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.passport_expire_date
     *
     * @param passportExpireDate the value for person.passport_expire_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setPassportExpireDate(LocalDate passportExpireDate) {
        this.passportExpireDate = passportExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.total_years_work_experience
     *
     * @return the value of person.total_years_work_experience
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Double getTotalYearsWorkExperience() {
        return totalYearsWorkExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.total_years_work_experience
     *
     * @param totalYearsWorkExperience the value for person.total_years_work_experience
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setTotalYearsWorkExperience(Double totalYearsWorkExperience) {
        this.totalYearsWorkExperience = totalYearsWorkExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.comments
     *
     * @return the value of person.comments
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.comments
     *
     * @param comments the value for person.comments
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.employment_status_enum_id
     *
     * @return the value of person.employment_status_enum_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getEmploymentStatusEnumId() {
        return employmentStatusEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.employment_status_enum_id
     *
     * @param employmentStatusEnumId the value for person.employment_status_enum_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setEmploymentStatusEnumId(String employmentStatusEnumId) {
        this.employmentStatusEnumId = employmentStatusEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.residence_status_enum_id
     *
     * @return the value of person.residence_status_enum_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getResidenceStatusEnumId() {
        return residenceStatusEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.residence_status_enum_id
     *
     * @param residenceStatusEnumId the value for person.residence_status_enum_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setResidenceStatusEnumId(String residenceStatusEnumId) {
        this.residenceStatusEnumId = residenceStatusEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.occupation
     *
     * @return the value of person.occupation
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.occupation
     *
     * @param occupation the value for person.occupation
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.years_with_employer
     *
     * @return the value of person.years_with_employer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public BigDecimal getYearsWithEmployer() {
        return yearsWithEmployer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.years_with_employer
     *
     * @param yearsWithEmployer the value for person.years_with_employer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setYearsWithEmployer(BigDecimal yearsWithEmployer) {
        this.yearsWithEmployer = yearsWithEmployer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.months_with_employer
     *
     * @return the value of person.months_with_employer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public BigDecimal getMonthsWithEmployer() {
        return monthsWithEmployer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.months_with_employer
     *
     * @param monthsWithEmployer the value for person.months_with_employer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setMonthsWithEmployer(BigDecimal monthsWithEmployer) {
        this.monthsWithEmployer = monthsWithEmployer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.existing_customer
     *
     * @return the value of person.existing_customer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getExistingCustomer() {
        return existingCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.existing_customer
     *
     * @param existingCustomer the value for person.existing_customer
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setExistingCustomer(String existingCustomer) {
        this.existingCustomer = existingCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.card_id
     *
     * @return the value of person.card_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.card_id
     *
     * @param cardId the value for person.card_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_updated_stamp
     *
     * @return the value of person.last_updated_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for person.last_updated_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_updated_tx_stamp
     *
     * @return the value of person.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for person.last_updated_tx_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.created_stamp
     *
     * @return the value of person.created_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.created_stamp
     *
     * @param createdStamp the value for person.created_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.created_tx_stamp
     *
     * @return the value of person.created_tx_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.created_tx_stamp
     *
     * @param createdTxStamp the value for person.created_tx_stamp
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.birth_place
     *
     * @return the value of person.birth_place
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.birth_place
     *
     * @param birthPlace the value for person.birth_place
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.birth_country
     *
     * @return the value of person.birth_country
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getBirthCountry() {
        return birthCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.birth_country
     *
     * @param birthCountry the value for person.birth_country
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setBirthCountry(String birthCountry) {
        this.birthCountry = birthCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.number_of_child
     *
     * @return the value of person.number_of_child
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public BigDecimal getNumberOfChild() {
        return numberOfChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.number_of_child
     *
     * @param numberOfChild the value for person.number_of_child
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setNumberOfChild(BigDecimal numberOfChild) {
        this.numberOfChild = numberOfChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.empl_position_type_id
     *
     * @return the value of person.empl_position_type_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getEmplPositionTypeId() {
        return emplPositionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.empl_position_type_id
     *
     * @param emplPositionTypeId the value for person.empl_position_type_id
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setEmplPositionTypeId(String emplPositionTypeId) {
        this.emplPositionTypeId = emplPositionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.empl_position_type_date
     *
     * @return the value of person.empl_position_type_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public Instant getEmplPositionTypeDate() {
        return emplPositionTypeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.empl_position_type_date
     *
     * @param emplPositionTypeDate the value for person.empl_position_type_date
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setEmplPositionTypeDate(Instant emplPositionTypeDate) {
        this.emplPositionTypeDate = emplPositionTypeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.employment_amount
     *
     * @return the value of person.employment_amount
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public BigDecimal getEmploymentAmount() {
        return employmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.employment_amount
     *
     * @param employmentAmount the value for person.employment_amount
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setEmploymentAmount(BigDecimal employmentAmount) {
        this.employmentAmount = employmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_modified_by_user_login
     *
     * @return the value of person.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for person.last_modified_by_user_login
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.created_by_user_login
     *
     * @return the value of person.created_by_user_login
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.created_by_user_login
     *
     * @param createdByUserLogin the value for person.created_by_user_login
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_position
     *
     * @return the value of person.person_position
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public String getPersonPosition() {
        return personPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_position
     *
     * @param personPosition the value for person.person_position
     *
     * @mbg.generated Wed Nov 22 15:44:14 CET 2023
     */
    public void setPersonPosition(String personPosition) {
        this.personPosition = personPosition;
    }
}