package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class RateType implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.rate_type_id
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private String rateTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.description
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.last_updated_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.created_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.created_tx_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_type.description_lang
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    private String descriptionLang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.rate_type_id
     *
     * @return the value of rate_type.rate_type_id
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public String getRateTypeId() {
        return rateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.rate_type_id
     *
     * @param rateTypeId the value for rate_type.rate_type_id
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setRateTypeId(String rateTypeId) {
        this.rateTypeId = rateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.description
     *
     * @return the value of rate_type.description
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.description
     *
     * @param description the value for rate_type.description
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.last_updated_stamp
     *
     * @return the value of rate_type.last_updated_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for rate_type.last_updated_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.last_updated_tx_stamp
     *
     * @return the value of rate_type.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for rate_type.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.created_stamp
     *
     * @return the value of rate_type.created_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.created_stamp
     *
     * @param createdStamp the value for rate_type.created_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.created_tx_stamp
     *
     * @return the value of rate_type.created_tx_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.created_tx_stamp
     *
     * @param createdTxStamp the value for rate_type.created_tx_stamp
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_type.description_lang
     *
     * @return the value of rate_type.description_lang
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public String getDescriptionLang() {
        return descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_type.description_lang
     *
     * @param descriptionLang the value for rate_type.description_lang
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    public void setDescriptionLang(String descriptionLang) {
        this.descriptionLang = descriptionLang;
    }
}