package it.mapsgroup.gzoom.mybatis.dto;

import java.util.Date;

public class SecurityPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.permission_id
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.description
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.dynamic_access
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private String dynamicAccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.last_updated_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private Date lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private Date lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.created_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private Date createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.created_tx_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private Date createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.enabled
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.last_modified_by_user_login
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_permission.created_by_user_login
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    private String createdByUserLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.permission_id
     *
     * @return the value of security_permission.permission_id
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.permission_id
     *
     * @param permissionId the value for security_permission.permission_id
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.description
     *
     * @return the value of security_permission.description
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.description
     *
     * @param description the value for security_permission.description
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.dynamic_access
     *
     * @return the value of security_permission.dynamic_access
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public String getDynamicAccess() {
        return dynamicAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.dynamic_access
     *
     * @param dynamicAccess the value for security_permission.dynamic_access
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setDynamicAccess(String dynamicAccess) {
        this.dynamicAccess = dynamicAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.last_updated_stamp
     *
     * @return the value of security_permission.last_updated_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public Date getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for security_permission.last_updated_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setLastUpdatedStamp(Date lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.last_updated_tx_stamp
     *
     * @return the value of security_permission.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public Date getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for security_permission.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.created_stamp
     *
     * @return the value of security_permission.created_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.created_stamp
     *
     * @param createdStamp the value for security_permission.created_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.created_tx_stamp
     *
     * @return the value of security_permission.created_tx_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public Date getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.created_tx_stamp
     *
     * @param createdTxStamp the value for security_permission.created_tx_stamp
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setCreatedTxStamp(Date createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.enabled
     *
     * @return the value of security_permission.enabled
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.enabled
     *
     * @param enabled the value for security_permission.enabled
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.last_modified_by_user_login
     *
     * @return the value of security_permission.last_modified_by_user_login
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for security_permission.last_modified_by_user_login
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_permission.created_by_user_login
     *
     * @return the value of security_permission.created_by_user_login
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_permission.created_by_user_login
     *
     * @param createdByUserLogin the value for security_permission.created_by_user_login
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }
}