package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class TimeEntry  implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.time_entry_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String timeEntryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.party_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.from_date
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.thru_date
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Instant thruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.rate_type_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String rateTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.work_effort_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String workEffortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.timesheet_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String timesheetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.invoice_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.invoice_item_seq_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String invoiceItemSeqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.hours
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Double hours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.comments
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.last_updated_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.last_updated_tx_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.created_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.created_tx_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.effort_uom_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String effortUomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.percentage
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Double percentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.last_modified_by_user_login
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.created_by_user_login
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.job_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.order_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_entry.plan_hours
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    private Double planHours;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.time_entry_id
     *
     * @return the value of time_entry.time_entry_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getTimeEntryId() {
        return timeEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.time_entry_id
     *
     * @param timeEntryId the value for time_entry.time_entry_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setTimeEntryId(String timeEntryId) {
        this.timeEntryId = timeEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.party_id
     *
     * @return the value of time_entry.party_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.party_id
     *
     * @param partyId the value for time_entry.party_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.from_date
     *
     * @return the value of time_entry.from_date
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.from_date
     *
     * @param fromDate the value for time_entry.from_date
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.thru_date
     *
     * @return the value of time_entry.thru_date
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Instant getThruDate() {
        return thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.thru_date
     *
     * @param thruDate the value for time_entry.thru_date
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setThruDate(Instant thruDate) {
        this.thruDate = thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.rate_type_id
     *
     * @return the value of time_entry.rate_type_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getRateTypeId() {
        return rateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.rate_type_id
     *
     * @param rateTypeId the value for time_entry.rate_type_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setRateTypeId(String rateTypeId) {
        this.rateTypeId = rateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.work_effort_id
     *
     * @return the value of time_entry.work_effort_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getWorkEffortId() {
        return workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.work_effort_id
     *
     * @param workEffortId the value for time_entry.work_effort_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setWorkEffortId(String workEffortId) {
        this.workEffortId = workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.timesheet_id
     *
     * @return the value of time_entry.timesheet_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getTimesheetId() {
        return timesheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.timesheet_id
     *
     * @param timesheetId the value for time_entry.timesheet_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setTimesheetId(String timesheetId) {
        this.timesheetId = timesheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.invoice_id
     *
     * @return the value of time_entry.invoice_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.invoice_id
     *
     * @param invoiceId the value for time_entry.invoice_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.invoice_item_seq_id
     *
     * @return the value of time_entry.invoice_item_seq_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getInvoiceItemSeqId() {
        return invoiceItemSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.invoice_item_seq_id
     *
     * @param invoiceItemSeqId the value for time_entry.invoice_item_seq_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setInvoiceItemSeqId(String invoiceItemSeqId) {
        this.invoiceItemSeqId = invoiceItemSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.hours
     *
     * @return the value of time_entry.hours
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Double getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.hours
     *
     * @param hours the value for time_entry.hours
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setHours(Double hours) {
        this.hours = hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.comments
     *
     * @return the value of time_entry.comments
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.comments
     *
     * @param comments the value for time_entry.comments
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.last_updated_stamp
     *
     * @return the value of time_entry.last_updated_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for time_entry.last_updated_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.last_updated_tx_stamp
     *
     * @return the value of time_entry.last_updated_tx_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for time_entry.last_updated_tx_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.created_stamp
     *
     * @return the value of time_entry.created_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.created_stamp
     *
     * @param createdStamp the value for time_entry.created_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.created_tx_stamp
     *
     * @return the value of time_entry.created_tx_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.created_tx_stamp
     *
     * @param createdTxStamp the value for time_entry.created_tx_stamp
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.effort_uom_id
     *
     * @return the value of time_entry.effort_uom_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getEffortUomId() {
        return effortUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.effort_uom_id
     *
     * @param effortUomId the value for time_entry.effort_uom_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setEffortUomId(String effortUomId) {
        this.effortUomId = effortUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.percentage
     *
     * @return the value of time_entry.percentage
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Double getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.percentage
     *
     * @param percentage the value for time_entry.percentage
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.last_modified_by_user_login
     *
     * @return the value of time_entry.last_modified_by_user_login
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for time_entry.last_modified_by_user_login
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.created_by_user_login
     *
     * @return the value of time_entry.created_by_user_login
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.created_by_user_login
     *
     * @param createdByUserLogin the value for time_entry.created_by_user_login
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.job_id
     *
     * @return the value of time_entry.job_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.job_id
     *
     * @param jobId the value for time_entry.job_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.order_id
     *
     * @return the value of time_entry.order_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.order_id
     *
     * @param orderId the value for time_entry.order_id
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_entry.plan_hours
     *
     * @return the value of time_entry.plan_hours
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public Double getPlanHours() {
        return planHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_entry.plan_hours
     *
     * @param planHours the value for time_entry.plan_hours
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    public void setPlanHours(Double planHours) {
        this.planHours = planHours;
    }
}