package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class TsByUserLogin  implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.timesheet_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String timesheetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.user_login_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String userLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.party_id_pe
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String partyIdPe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.work_effort_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String workEffortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.work_effort_type_period_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String workEffortTypePeriodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.party_id_uo
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String partyIdUo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.updateable
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String updateable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.from_date
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.thru_date
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private Instant thruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.status_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.contract_hours
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private Double contractHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.actual_hours
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private Double actualHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.effort_uom_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String effortUomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_by_user_login.role_type
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    private String roleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.timesheet_id
     *
     * @return the value of ts_by_user_login.timesheet_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getTimesheetId() {
        return timesheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.timesheet_id
     *
     * @param timesheetId the value for ts_by_user_login.timesheet_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setTimesheetId(String timesheetId) {
        this.timesheetId = timesheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.user_login_id
     *
     * @return the value of ts_by_user_login.user_login_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getUserLoginId() {
        return userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.user_login_id
     *
     * @param userLoginId the value for ts_by_user_login.user_login_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.party_id_pe
     *
     * @return the value of ts_by_user_login.party_id_pe
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getPartyIdPe() {
        return partyIdPe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.party_id_pe
     *
     * @param partyIdPe the value for ts_by_user_login.party_id_pe
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setPartyIdPe(String partyIdPe) {
        this.partyIdPe = partyIdPe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.work_effort_id
     *
     * @return the value of ts_by_user_login.work_effort_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getWorkEffortId() {
        return workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.work_effort_id
     *
     * @param workEffortId the value for ts_by_user_login.work_effort_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setWorkEffortId(String workEffortId) {
        this.workEffortId = workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.work_effort_type_period_id
     *
     * @return the value of ts_by_user_login.work_effort_type_period_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getWorkEffortTypePeriodId() {
        return workEffortTypePeriodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.work_effort_type_period_id
     *
     * @param workEffortTypePeriodId the value for ts_by_user_login.work_effort_type_period_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setWorkEffortTypePeriodId(String workEffortTypePeriodId) {
        this.workEffortTypePeriodId = workEffortTypePeriodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.party_id_uo
     *
     * @return the value of ts_by_user_login.party_id_uo
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getPartyIdUo() {
        return partyIdUo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.party_id_uo
     *
     * @param partyIdUo the value for ts_by_user_login.party_id_uo
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setPartyIdUo(String partyIdUo) {
        this.partyIdUo = partyIdUo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.updateable
     *
     * @return the value of ts_by_user_login.updateable
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getUpdateable() {
        return updateable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.updateable
     *
     * @param updateable the value for ts_by_user_login.updateable
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setUpdateable(String updateable) {
        this.updateable = updateable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.from_date
     *
     * @return the value of ts_by_user_login.from_date
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.from_date
     *
     * @param fromDate the value for ts_by_user_login.from_date
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.thru_date
     *
     * @return the value of ts_by_user_login.thru_date
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public Instant getThruDate() {
        return thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.thru_date
     *
     * @param thruDate the value for ts_by_user_login.thru_date
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setThruDate(Instant thruDate) {
        this.thruDate = thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.status_id
     *
     * @return the value of ts_by_user_login.status_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.status_id
     *
     * @param statusId the value for ts_by_user_login.status_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.contract_hours
     *
     * @return the value of ts_by_user_login.contract_hours
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public Double getContractHours() {
        return contractHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.contract_hours
     *
     * @param contractHours the value for ts_by_user_login.contract_hours
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setContractHours(Double contractHours) {
        this.contractHours = contractHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.actual_hours
     *
     * @return the value of ts_by_user_login.actual_hours
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public Double getActualHours() {
        return actualHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.actual_hours
     *
     * @param actualHours the value for ts_by_user_login.actual_hours
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setActualHours(Double actualHours) {
        this.actualHours = actualHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.effort_uom_id
     *
     * @return the value of ts_by_user_login.effort_uom_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getEffortUomId() {
        return effortUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.effort_uom_id
     *
     * @param effortUomId the value for ts_by_user_login.effort_uom_id
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setEffortUomId(String effortUomId) {
        this.effortUomId = effortUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_by_user_login.role_type
     *
     * @return the value of ts_by_user_login.role_type
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_by_user_login.role_type
     *
     * @param roleType the value for ts_by_user_login.role_type
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    @Override
    public Instant getCreatedStamp() {
        return null;
    }

    @Override
    public void setCreatedStamp(Instant createdStamp) {

    }

    @Override
    public Instant getCreatedTxStamp() {
        return null;
    }

    @Override
    public void setCreatedTxStamp(Instant createdTxStamp) {

    }

    @Override
    public Instant getLastUpdatedStamp() {
        return null;
    }

    @Override
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {

    }

    @Override
    public Instant getLastUpdatedTxStamp() {
        return null;
    }

    @Override
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {

    }
}