package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;
import org.apache.ibatis.type.Alias;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;

@Alias("UserLogin")
public class UserLoginPersistent implements AbstractIdentity, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_login_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String userLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.current_password
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String currentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.password_hint
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String passwordHint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.is_system
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String isSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.enabled
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.has_logged_out
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String hasLoggedOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.require_password_change
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String requirePasswordChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.last_currency_uom
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String lastCurrencyUom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.last_locale
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String lastLocale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.last_time_zone
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String lastTimeZone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.disabled_date_time
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private Instant disabledDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.successive_failed_logins
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private BigDecimal successiveFailedLogins;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.external_auth_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String externalAuthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_ldap_dn
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String userLdapDn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.last_updated_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.last_updated_tx_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.created_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.created_tx_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.party_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.external_system
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String externalSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.description
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_login_id
     *
     * @return the value of user_login.user_login_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getUserLoginId() {
        return userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_login_id
     *
     * @param userLoginId the value for user_login.user_login_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.current_password
     *
     * @return the value of user_login.current_password
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getCurrentPassword() {
        return currentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.current_password
     *
     * @param currentPassword the value for user_login.current_password
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setCurrentPassword(String currentPassword) {
        this.currentPassword = currentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.password_hint
     *
     * @return the value of user_login.password_hint
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getPasswordHint() {
        return passwordHint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.password_hint
     *
     * @param passwordHint the value for user_login.password_hint
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.is_system
     *
     * @return the value of user_login.is_system
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.is_system
     *
     * @param isSystem the value for user_login.is_system
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setIsSystem(String isSystem) {
        this.isSystem = isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.enabled
     *
     * @return the value of user_login.enabled
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.enabled
     *
     * @param enabled the value for user_login.enabled
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.has_logged_out
     *
     * @return the value of user_login.has_logged_out
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getHasLoggedOut() {
        return hasLoggedOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.has_logged_out
     *
     * @param hasLoggedOut the value for user_login.has_logged_out
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setHasLoggedOut(String hasLoggedOut) {
        this.hasLoggedOut = hasLoggedOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.require_password_change
     *
     * @return the value of user_login.require_password_change
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getRequirePasswordChange() {
        return requirePasswordChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.require_password_change
     *
     * @param requirePasswordChange the value for user_login.require_password_change
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setRequirePasswordChange(String requirePasswordChange) {
        this.requirePasswordChange = requirePasswordChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.last_currency_uom
     *
     * @return the value of user_login.last_currency_uom
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getLastCurrencyUom() {
        return lastCurrencyUom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.last_currency_uom
     *
     * @param lastCurrencyUom the value for user_login.last_currency_uom
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setLastCurrencyUom(String lastCurrencyUom) {
        this.lastCurrencyUom = lastCurrencyUom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.last_locale
     *
     * @return the value of user_login.last_locale
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getLastLocale() {
        return lastLocale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.last_locale
     *
     * @param lastLocale the value for user_login.last_locale
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setLastLocale(String lastLocale) {
        this.lastLocale = lastLocale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.last_time_zone
     *
     * @return the value of user_login.last_time_zone
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getLastTimeZone() {
        return lastTimeZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.last_time_zone
     *
     * @param lastTimeZone the value for user_login.last_time_zone
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setLastTimeZone(String lastTimeZone) {
        this.lastTimeZone = lastTimeZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.disabled_date_time
     *
     * @return the value of user_login.disabled_date_time
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public Instant getDisabledDateTime() {
        return disabledDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.disabled_date_time
     *
     * @param disabledDateTime the value for user_login.disabled_date_time
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setDisabledDateTime(Instant disabledDateTime) {
        this.disabledDateTime = disabledDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.successive_failed_logins
     *
     * @return the value of user_login.successive_failed_logins
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public BigDecimal getSuccessiveFailedLogins() {
        return successiveFailedLogins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.successive_failed_logins
     *
     * @param successiveFailedLogins the value for user_login.successive_failed_logins
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setSuccessiveFailedLogins(BigDecimal successiveFailedLogins) {
        this.successiveFailedLogins = successiveFailedLogins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.external_auth_id
     *
     * @return the value of user_login.external_auth_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getExternalAuthId() {
        return externalAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.external_auth_id
     *
     * @param externalAuthId the value for user_login.external_auth_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setExternalAuthId(String externalAuthId) {
        this.externalAuthId = externalAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_ldap_dn
     *
     * @return the value of user_login.user_ldap_dn
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getUserLdapDn() {
        return userLdapDn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_ldap_dn
     *
     * @param userLdapDn the value for user_login.user_ldap_dn
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setUserLdapDn(String userLdapDn) {
        this.userLdapDn = userLdapDn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.last_updated_stamp
     *
     * @return the value of user_login.last_updated_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for user_login.last_updated_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.last_updated_tx_stamp
     *
     * @return the value of user_login.last_updated_tx_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for user_login.last_updated_tx_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.created_stamp
     *
     * @return the value of user_login.created_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.created_stamp
     *
     * @param createdStamp the value for user_login.created_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.created_tx_stamp
     *
     * @return the value of user_login.created_tx_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.created_tx_stamp
     *
     * @param createdTxStamp the value for user_login.created_tx_stamp
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.party_id
     *
     * @return the value of user_login.party_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.party_id
     *
     * @param partyId the value for user_login.party_id
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.external_system
     *
     * @return the value of user_login.external_system
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getExternalSystem() {
        return externalSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.external_system
     *
     * @param externalSystem the value for user_login.external_system
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setExternalSystem(String externalSystem) {
        this.externalSystem = externalSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.description
     *
     * @return the value of user_login.description
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.description
     *
     * @param description the value for user_login.description
     *
     * @mbg.generated Fri Nov 24 11:29:31 CET 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }
}