package it.mapsgroup.gzoom.mybatis.dto;


import java.time.Instant;

public class Visit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visit_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String visitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.visitor_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String visitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.user_login_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String userLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.user_created
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String userCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.session_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.server_ip_address
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String serverIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.server_host_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String serverHostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.webapp_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String webappName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.initial_locale
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String initialLocale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.initial_request
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String initialRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.initial_referrer
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String initialReferrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.initial_user_agent
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String initialUserAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.user_agent_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String userAgentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_ip_address
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_host_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientHostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_user
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_ip_isp_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientIpIspName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_ip_postal_code
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientIpPostalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_ip_state_prov_geo_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientIpStateProvGeoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.client_ip_country_geo_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String clientIpCountryGeoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.cookie
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String cookie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.from_date
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.thru_date
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private Instant thruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.last_updated_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.last_updated_tx_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.created_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.created_tx_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.contact_mech_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String contactMechId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.party_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit.role_type_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    private String roleTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visit_id
     *
     * @return the value of visit.visit_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visit_id
     *
     * @param visitId the value for visit.visit_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setVisitId(String visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.visitor_id
     *
     * @return the value of visit.visitor_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.visitor_id
     *
     * @param visitorId the value for visit.visitor_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setVisitorId(String visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.user_login_id
     *
     * @return the value of visit.user_login_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getUserLoginId() {
        return userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.user_login_id
     *
     * @param userLoginId the value for visit.user_login_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.user_created
     *
     * @return the value of visit.user_created
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getUserCreated() {
        return userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.user_created
     *
     * @param userCreated the value for visit.user_created
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setUserCreated(String userCreated) {
        this.userCreated = userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.session_id
     *
     * @return the value of visit.session_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.session_id
     *
     * @param sessionId the value for visit.session_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.server_ip_address
     *
     * @return the value of visit.server_ip_address
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getServerIpAddress() {
        return serverIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.server_ip_address
     *
     * @param serverIpAddress the value for visit.server_ip_address
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setServerIpAddress(String serverIpAddress) {
        this.serverIpAddress = serverIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.server_host_name
     *
     * @return the value of visit.server_host_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getServerHostName() {
        return serverHostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.server_host_name
     *
     * @param serverHostName the value for visit.server_host_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setServerHostName(String serverHostName) {
        this.serverHostName = serverHostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.webapp_name
     *
     * @return the value of visit.webapp_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getWebappName() {
        return webappName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.webapp_name
     *
     * @param webappName the value for visit.webapp_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setWebappName(String webappName) {
        this.webappName = webappName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.initial_locale
     *
     * @return the value of visit.initial_locale
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getInitialLocale() {
        return initialLocale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.initial_locale
     *
     * @param initialLocale the value for visit.initial_locale
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setInitialLocale(String initialLocale) {
        this.initialLocale = initialLocale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.initial_request
     *
     * @return the value of visit.initial_request
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getInitialRequest() {
        return initialRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.initial_request
     *
     * @param initialRequest the value for visit.initial_request
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setInitialRequest(String initialRequest) {
        this.initialRequest = initialRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.initial_referrer
     *
     * @return the value of visit.initial_referrer
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getInitialReferrer() {
        return initialReferrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.initial_referrer
     *
     * @param initialReferrer the value for visit.initial_referrer
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setInitialReferrer(String initialReferrer) {
        this.initialReferrer = initialReferrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.initial_user_agent
     *
     * @return the value of visit.initial_user_agent
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getInitialUserAgent() {
        return initialUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.initial_user_agent
     *
     * @param initialUserAgent the value for visit.initial_user_agent
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setInitialUserAgent(String initialUserAgent) {
        this.initialUserAgent = initialUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.user_agent_id
     *
     * @return the value of visit.user_agent_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getUserAgentId() {
        return userAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.user_agent_id
     *
     * @param userAgentId the value for visit.user_agent_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setUserAgentId(String userAgentId) {
        this.userAgentId = userAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_ip_address
     *
     * @return the value of visit.client_ip_address
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientIpAddress() {
        return clientIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_ip_address
     *
     * @param clientIpAddress the value for visit.client_ip_address
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientIpAddress(String clientIpAddress) {
        this.clientIpAddress = clientIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_host_name
     *
     * @return the value of visit.client_host_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientHostName() {
        return clientHostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_host_name
     *
     * @param clientHostName the value for visit.client_host_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientHostName(String clientHostName) {
        this.clientHostName = clientHostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_user
     *
     * @return the value of visit.client_user
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientUser() {
        return clientUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_user
     *
     * @param clientUser the value for visit.client_user
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientUser(String clientUser) {
        this.clientUser = clientUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_ip_isp_name
     *
     * @return the value of visit.client_ip_isp_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientIpIspName() {
        return clientIpIspName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_ip_isp_name
     *
     * @param clientIpIspName the value for visit.client_ip_isp_name
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientIpIspName(String clientIpIspName) {
        this.clientIpIspName = clientIpIspName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_ip_postal_code
     *
     * @return the value of visit.client_ip_postal_code
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientIpPostalCode() {
        return clientIpPostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_ip_postal_code
     *
     * @param clientIpPostalCode the value for visit.client_ip_postal_code
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientIpPostalCode(String clientIpPostalCode) {
        this.clientIpPostalCode = clientIpPostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_ip_state_prov_geo_id
     *
     * @return the value of visit.client_ip_state_prov_geo_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientIpStateProvGeoId() {
        return clientIpStateProvGeoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_ip_state_prov_geo_id
     *
     * @param clientIpStateProvGeoId the value for visit.client_ip_state_prov_geo_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientIpStateProvGeoId(String clientIpStateProvGeoId) {
        this.clientIpStateProvGeoId = clientIpStateProvGeoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.client_ip_country_geo_id
     *
     * @return the value of visit.client_ip_country_geo_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getClientIpCountryGeoId() {
        return clientIpCountryGeoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.client_ip_country_geo_id
     *
     * @param clientIpCountryGeoId the value for visit.client_ip_country_geo_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setClientIpCountryGeoId(String clientIpCountryGeoId) {
        this.clientIpCountryGeoId = clientIpCountryGeoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.cookie
     *
     * @return the value of visit.cookie
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.cookie
     *
     * @param cookie the value for visit.cookie
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.from_date
     *
     * @return the value of visit.from_date
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.from_date
     *
     * @param fromDate the value for visit.from_date
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.thru_date
     *
     * @return the value of visit.thru_date
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public Instant getThruDate() {
        return thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.thru_date
     *
     * @param thruDate the value for visit.thru_date
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setThruDate(Instant thruDate) {
        this.thruDate = thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.last_updated_stamp
     *
     * @return the value of visit.last_updated_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for visit.last_updated_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.last_updated_tx_stamp
     *
     * @return the value of visit.last_updated_tx_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for visit.last_updated_tx_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.created_stamp
     *
     * @return the value of visit.created_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.created_stamp
     *
     * @param createdStamp the value for visit.created_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.created_tx_stamp
     *
     * @return the value of visit.created_tx_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.created_tx_stamp
     *
     * @param createdTxStamp the value for visit.created_tx_stamp
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.contact_mech_id
     *
     * @return the value of visit.contact_mech_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getContactMechId() {
        return contactMechId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.contact_mech_id
     *
     * @param contactMechId the value for visit.contact_mech_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setContactMechId(String contactMechId) {
        this.contactMechId = contactMechId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.party_id
     *
     * @return the value of visit.party_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.party_id
     *
     * @param partyId the value for visit.party_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit.role_type_id
     *
     * @return the value of visit.role_type_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public String getRoleTypeId() {
        return roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit.role_type_id
     *
     * @param roleTypeId the value for visit.role_type_id
     *
     * @mbg.generated Tue Mar 19 14:59:29 CET 2024
     */
    public void setRoleTypeId(String roleTypeId) {
        this.roleTypeId = roleTypeId;
    }
}