package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class WorkEffortContentType implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.work_effort_content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String workEffortContentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.parent_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String parentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.description
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.created_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String contentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.in_inquiry
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String inInquiry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.description_lang
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String descriptionLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content_type.created_by_user_login
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    private String createdByUserLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.work_effort_content_type_id
     *
     * @return the value of work_effort_content_type.work_effort_content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getWorkEffortContentTypeId() {
        return workEffortContentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.work_effort_content_type_id
     *
     * @param workEffortContentTypeId the value for work_effort_content_type.work_effort_content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setWorkEffortContentTypeId(String workEffortContentTypeId) {
        this.workEffortContentTypeId = workEffortContentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.parent_type_id
     *
     * @return the value of work_effort_content_type.parent_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getParentTypeId() {
        return parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.parent_type_id
     *
     * @param parentTypeId the value for work_effort_content_type.parent_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setParentTypeId(String parentTypeId) {
        this.parentTypeId = parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.description
     *
     * @return the value of work_effort_content_type.description
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.description
     *
     * @param description the value for work_effort_content_type.description
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.last_updated_stamp
     *
     * @return the value of work_effort_content_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for work_effort_content_type.last_updated_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.last_updated_tx_stamp
     *
     * @return the value of work_effort_content_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for work_effort_content_type.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.created_stamp
     *
     * @return the value of work_effort_content_type.created_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.created_stamp
     *
     * @param createdStamp the value for work_effort_content_type.created_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.created_tx_stamp
     *
     * @return the value of work_effort_content_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.created_tx_stamp
     *
     * @param createdTxStamp the value for work_effort_content_type.created_tx_stamp
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.content_type_id
     *
     * @return the value of work_effort_content_type.content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getContentTypeId() {
        return contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.content_type_id
     *
     * @param contentTypeId the value for work_effort_content_type.content_type_id
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setContentTypeId(String contentTypeId) {
        this.contentTypeId = contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.in_inquiry
     *
     * @return the value of work_effort_content_type.in_inquiry
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getInInquiry() {
        return inInquiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.in_inquiry
     *
     * @param inInquiry the value for work_effort_content_type.in_inquiry
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setInInquiry(String inInquiry) {
        this.inInquiry = inInquiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.description_lang
     *
     * @return the value of work_effort_content_type.description_lang
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getDescriptionLang() {
        return descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.description_lang
     *
     * @param descriptionLang the value for work_effort_content_type.description_lang
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setDescriptionLang(String descriptionLang) {
        this.descriptionLang = descriptionLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.last_modified_by_user_login
     *
     * @return the value of work_effort_content_type.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for work_effort_content_type.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content_type.created_by_user_login
     *
     * @return the value of work_effort_content_type.created_by_user_login
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content_type.created_by_user_login
     *
     * @param createdByUserLogin the value for work_effort_content_type.created_by_user_login
     *
     * @mbg.generated Thu Oct 19 12:15:45 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }
}