package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.math.BigDecimal;
import java.time.Instant;

public class WorkEffortAssoc implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.work_effort_id_from
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String workEffortIdFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.work_effort_id_to
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String workEffortIdTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.work_effort_assoc_type_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String workEffortAssocTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.from_date
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.sequence_num
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private BigDecimal sequenceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.thru_date
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Instant thruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.last_updated_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.last_updated_tx_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.created_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.created_tx_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.assoc_weight
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private Double assocWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.comments
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.note
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.is_posted
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String isPosted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.response_enum_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String responseEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.we_measure_eval_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String weMeasureEvalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.work_effort_revision_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String workEffortRevisionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.comments_lang
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String commentsLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.last_modified_by_user_login
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_assoc.created_by_user_login
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    private String createdByUserLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.work_effort_id_from
     *
     * @return the value of work_effort_assoc.work_effort_id_from
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getWorkEffortIdFrom() {
        return workEffortIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.work_effort_id_from
     *
     * @param workEffortIdFrom the value for work_effort_assoc.work_effort_id_from
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setWorkEffortIdFrom(String workEffortIdFrom) {
        this.workEffortIdFrom = workEffortIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.work_effort_id_to
     *
     * @return the value of work_effort_assoc.work_effort_id_to
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getWorkEffortIdTo() {
        return workEffortIdTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.work_effort_id_to
     *
     * @param workEffortIdTo the value for work_effort_assoc.work_effort_id_to
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setWorkEffortIdTo(String workEffortIdTo) {
        this.workEffortIdTo = workEffortIdTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.work_effort_assoc_type_id
     *
     * @return the value of work_effort_assoc.work_effort_assoc_type_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getWorkEffortAssocTypeId() {
        return workEffortAssocTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.work_effort_assoc_type_id
     *
     * @param workEffortAssocTypeId the value for work_effort_assoc.work_effort_assoc_type_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setWorkEffortAssocTypeId(String workEffortAssocTypeId) {
        this.workEffortAssocTypeId = workEffortAssocTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.from_date
     *
     * @return the value of work_effort_assoc.from_date
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.from_date
     *
     * @param fromDate the value for work_effort_assoc.from_date
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.sequence_num
     *
     * @return the value of work_effort_assoc.sequence_num
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public BigDecimal getSequenceNum() {
        return sequenceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.sequence_num
     *
     * @param sequenceNum the value for work_effort_assoc.sequence_num
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setSequenceNum(BigDecimal sequenceNum) {
        this.sequenceNum = sequenceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.thru_date
     *
     * @return the value of work_effort_assoc.thru_date
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Instant getThruDate() {
        return thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.thru_date
     *
     * @param thruDate the value for work_effort_assoc.thru_date
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setThruDate(Instant thruDate) {
        this.thruDate = thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.last_updated_stamp
     *
     * @return the value of work_effort_assoc.last_updated_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for work_effort_assoc.last_updated_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.last_updated_tx_stamp
     *
     * @return the value of work_effort_assoc.last_updated_tx_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for work_effort_assoc.last_updated_tx_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.created_stamp
     *
     * @return the value of work_effort_assoc.created_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.created_stamp
     *
     * @param createdStamp the value for work_effort_assoc.created_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.created_tx_stamp
     *
     * @return the value of work_effort_assoc.created_tx_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.created_tx_stamp
     *
     * @param createdTxStamp the value for work_effort_assoc.created_tx_stamp
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.assoc_weight
     *
     * @return the value of work_effort_assoc.assoc_weight
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public Double getAssocWeight() {
        return assocWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.assoc_weight
     *
     * @param assocWeight the value for work_effort_assoc.assoc_weight
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setAssocWeight(Double assocWeight) {
        this.assocWeight = assocWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.comments
     *
     * @return the value of work_effort_assoc.comments
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.comments
     *
     * @param comments the value for work_effort_assoc.comments
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.note
     *
     * @return the value of work_effort_assoc.note
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.note
     *
     * @param note the value for work_effort_assoc.note
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.is_posted
     *
     * @return the value of work_effort_assoc.is_posted
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getIsPosted() {
        return isPosted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.is_posted
     *
     * @param isPosted the value for work_effort_assoc.is_posted
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setIsPosted(String isPosted) {
        this.isPosted = isPosted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.response_enum_id
     *
     * @return the value of work_effort_assoc.response_enum_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getResponseEnumId() {
        return responseEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.response_enum_id
     *
     * @param responseEnumId the value for work_effort_assoc.response_enum_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setResponseEnumId(String responseEnumId) {
        this.responseEnumId = responseEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.we_measure_eval_id
     *
     * @return the value of work_effort_assoc.we_measure_eval_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getWeMeasureEvalId() {
        return weMeasureEvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.we_measure_eval_id
     *
     * @param weMeasureEvalId the value for work_effort_assoc.we_measure_eval_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setWeMeasureEvalId(String weMeasureEvalId) {
        this.weMeasureEvalId = weMeasureEvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.work_effort_revision_id
     *
     * @return the value of work_effort_assoc.work_effort_revision_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getWorkEffortRevisionId() {
        return workEffortRevisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.work_effort_revision_id
     *
     * @param workEffortRevisionId the value for work_effort_assoc.work_effort_revision_id
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setWorkEffortRevisionId(String workEffortRevisionId) {
        this.workEffortRevisionId = workEffortRevisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.comments_lang
     *
     * @return the value of work_effort_assoc.comments_lang
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getCommentsLang() {
        return commentsLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.comments_lang
     *
     * @param commentsLang the value for work_effort_assoc.comments_lang
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setCommentsLang(String commentsLang) {
        this.commentsLang = commentsLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.last_modified_by_user_login
     *
     * @return the value of work_effort_assoc.last_modified_by_user_login
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for work_effort_assoc.last_modified_by_user_login
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_assoc.created_by_user_login
     *
     * @return the value of work_effort_assoc.created_by_user_login
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_assoc.created_by_user_login
     *
     * @param createdByUserLogin the value for work_effort_assoc.created_by_user_login
     *
     * @mbg.generated Wed Oct 11 11:39:53 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }
}