package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.time.Instant;

public class WorkEffortContent implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.work_effort_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private String workEffortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.content_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private String contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.work_effort_content_type_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private String workEffortContentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.from_date
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.thru_date
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private Instant thruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.last_updated_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.created_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.created_tx_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_content.created_by_user_login
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    private String createdByUserLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.work_effort_id
     *
     * @return the value of work_effort_content.work_effort_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public String getWorkEffortId() {
        return workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.work_effort_id
     *
     * @param workEffortId the value for work_effort_content.work_effort_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setWorkEffortId(String workEffortId) {
        this.workEffortId = workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.content_id
     *
     * @return the value of work_effort_content.content_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public String getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.content_id
     *
     * @param contentId the value for work_effort_content.content_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setContentId(String contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.work_effort_content_type_id
     *
     * @return the value of work_effort_content.work_effort_content_type_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public String getWorkEffortContentTypeId() {
        return workEffortContentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.work_effort_content_type_id
     *
     * @param workEffortContentTypeId the value for work_effort_content.work_effort_content_type_id
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setWorkEffortContentTypeId(String workEffortContentTypeId) {
        this.workEffortContentTypeId = workEffortContentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.from_date
     *
     * @return the value of work_effort_content.from_date
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.from_date
     *
     * @param fromDate the value for work_effort_content.from_date
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.thru_date
     *
     * @return the value of work_effort_content.thru_date
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public Instant getThruDate() {
        return thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.thru_date
     *
     * @param thruDate the value for work_effort_content.thru_date
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setThruDate(Instant thruDate) {
        this.thruDate = thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.last_updated_stamp
     *
     * @return the value of work_effort_content.last_updated_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for work_effort_content.last_updated_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.last_updated_tx_stamp
     *
     * @return the value of work_effort_content.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for work_effort_content.last_updated_tx_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.created_stamp
     *
     * @return the value of work_effort_content.created_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.created_stamp
     *
     * @param createdStamp the value for work_effort_content.created_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.created_tx_stamp
     *
     * @return the value of work_effort_content.created_tx_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.created_tx_stamp
     *
     * @param createdTxStamp the value for work_effort_content.created_tx_stamp
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.last_modified_by_user_login
     *
     * @return the value of work_effort_content.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for work_effort_content.last_modified_by_user_login
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_content.created_by_user_login
     *
     * @return the value of work_effort_content.created_by_user_login
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_content.created_by_user_login
     *
     * @param createdByUserLogin the value for work_effort_content.created_by_user_login
     *
     * @mbg.generated Thu Oct 26 15:44:15 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }
}