package it.mapsgroup.gzoom.mybatis.dto;

import it.mapsgroup.gzoom.mybatis.AbstractIdentity;

import java.math.BigDecimal;
import java.time.Instant;

public class WorkEffortPartyAssignment implements AbstractIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.work_effort_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String workEffortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.party_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.role_type_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String roleTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.from_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.thru_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant thruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.assigned_by_user_login_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String assignedByUserLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.status_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.status_date_time
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant statusDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.expectation_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String expectationEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.delegate_reason_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String delegateReasonEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.facility_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String facilityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.comments
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.must_rsvp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String mustRsvp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.availability_status_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String availabilityStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.last_updated_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.created_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.created_tx_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant createdTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.role_type_weight
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Double roleTypeWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.role_type_weight_actual
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Double roleTypeWeightActual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.work_effort_measure_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String workEffortMeasureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.is_posted
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String isPosted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.from_date_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant fromDateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.work_effort_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String workEffortIdFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.party_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String partyIdFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.role_type_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String roleTypeIdFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.sequence_num
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private BigDecimal sequenceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.last_modified_by_user_login
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.created_by_user_login
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.planned_hours
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Double plannedHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.comments_lang
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String commentsLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private Instant endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_cause_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String endCauseEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_replacement_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String endReplacementEnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_work_effort_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String endWorkEffortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_work_effort_id_we1
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String endWorkEffortIdWe1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_work_effort_id_we2
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String endWorkEffortIdWe2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_party_assignment.end_work_effort_id_we3
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    private String endWorkEffortIdWe3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.work_effort_id
     *
     * @return the value of work_effort_party_assignment.work_effort_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getWorkEffortId() {
        return workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.work_effort_id
     *
     * @param workEffortId the value for work_effort_party_assignment.work_effort_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setWorkEffortId(String workEffortId) {
        this.workEffortId = workEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.party_id
     *
     * @return the value of work_effort_party_assignment.party_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.party_id
     *
     * @param partyId the value for work_effort_party_assignment.party_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.role_type_id
     *
     * @return the value of work_effort_party_assignment.role_type_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getRoleTypeId() {
        return roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.role_type_id
     *
     * @param roleTypeId the value for work_effort_party_assignment.role_type_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setRoleTypeId(String roleTypeId) {
        this.roleTypeId = roleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.from_date
     *
     * @return the value of work_effort_party_assignment.from_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.from_date
     *
     * @param fromDate the value for work_effort_party_assignment.from_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.thru_date
     *
     * @return the value of work_effort_party_assignment.thru_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getThruDate() {
        return thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.thru_date
     *
     * @param thruDate the value for work_effort_party_assignment.thru_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setThruDate(Instant thruDate) {
        this.thruDate = thruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.assigned_by_user_login_id
     *
     * @return the value of work_effort_party_assignment.assigned_by_user_login_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getAssignedByUserLoginId() {
        return assignedByUserLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.assigned_by_user_login_id
     *
     * @param assignedByUserLoginId the value for work_effort_party_assignment.assigned_by_user_login_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setAssignedByUserLoginId(String assignedByUserLoginId) {
        this.assignedByUserLoginId = assignedByUserLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.status_id
     *
     * @return the value of work_effort_party_assignment.status_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.status_id
     *
     * @param statusId the value for work_effort_party_assignment.status_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.status_date_time
     *
     * @return the value of work_effort_party_assignment.status_date_time
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getStatusDateTime() {
        return statusDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.status_date_time
     *
     * @param statusDateTime the value for work_effort_party_assignment.status_date_time
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setStatusDateTime(Instant statusDateTime) {
        this.statusDateTime = statusDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.expectation_enum_id
     *
     * @return the value of work_effort_party_assignment.expectation_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getExpectationEnumId() {
        return expectationEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.expectation_enum_id
     *
     * @param expectationEnumId the value for work_effort_party_assignment.expectation_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setExpectationEnumId(String expectationEnumId) {
        this.expectationEnumId = expectationEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.delegate_reason_enum_id
     *
     * @return the value of work_effort_party_assignment.delegate_reason_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getDelegateReasonEnumId() {
        return delegateReasonEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.delegate_reason_enum_id
     *
     * @param delegateReasonEnumId the value for work_effort_party_assignment.delegate_reason_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setDelegateReasonEnumId(String delegateReasonEnumId) {
        this.delegateReasonEnumId = delegateReasonEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.facility_id
     *
     * @return the value of work_effort_party_assignment.facility_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.facility_id
     *
     * @param facilityId the value for work_effort_party_assignment.facility_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.comments
     *
     * @return the value of work_effort_party_assignment.comments
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.comments
     *
     * @param comments the value for work_effort_party_assignment.comments
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.must_rsvp
     *
     * @return the value of work_effort_party_assignment.must_rsvp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getMustRsvp() {
        return mustRsvp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.must_rsvp
     *
     * @param mustRsvp the value for work_effort_party_assignment.must_rsvp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setMustRsvp(String mustRsvp) {
        this.mustRsvp = mustRsvp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.availability_status_id
     *
     * @return the value of work_effort_party_assignment.availability_status_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getAvailabilityStatusId() {
        return availabilityStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.availability_status_id
     *
     * @param availabilityStatusId the value for work_effort_party_assignment.availability_status_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setAvailabilityStatusId(String availabilityStatusId) {
        this.availabilityStatusId = availabilityStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.last_updated_stamp
     *
     * @return the value of work_effort_party_assignment.last_updated_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for work_effort_party_assignment.last_updated_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.last_updated_tx_stamp
     *
     * @return the value of work_effort_party_assignment.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for work_effort_party_assignment.last_updated_tx_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.created_stamp
     *
     * @return the value of work_effort_party_assignment.created_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.created_stamp
     *
     * @param createdStamp the value for work_effort_party_assignment.created_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.created_tx_stamp
     *
     * @return the value of work_effort_party_assignment.created_tx_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.created_tx_stamp
     *
     * @param createdTxStamp the value for work_effort_party_assignment.created_tx_stamp
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.role_type_weight
     *
     * @return the value of work_effort_party_assignment.role_type_weight
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Double getRoleTypeWeight() {
        return roleTypeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.role_type_weight
     *
     * @param roleTypeWeight the value for work_effort_party_assignment.role_type_weight
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setRoleTypeWeight(Double roleTypeWeight) {
        this.roleTypeWeight = roleTypeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.role_type_weight_actual
     *
     * @return the value of work_effort_party_assignment.role_type_weight_actual
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Double getRoleTypeWeightActual() {
        return roleTypeWeightActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.role_type_weight_actual
     *
     * @param roleTypeWeightActual the value for work_effort_party_assignment.role_type_weight_actual
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setRoleTypeWeightActual(Double roleTypeWeightActual) {
        this.roleTypeWeightActual = roleTypeWeightActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.work_effort_measure_id
     *
     * @return the value of work_effort_party_assignment.work_effort_measure_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getWorkEffortMeasureId() {
        return workEffortMeasureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.work_effort_measure_id
     *
     * @param workEffortMeasureId the value for work_effort_party_assignment.work_effort_measure_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setWorkEffortMeasureId(String workEffortMeasureId) {
        this.workEffortMeasureId = workEffortMeasureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.is_posted
     *
     * @return the value of work_effort_party_assignment.is_posted
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getIsPosted() {
        return isPosted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.is_posted
     *
     * @param isPosted the value for work_effort_party_assignment.is_posted
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setIsPosted(String isPosted) {
        this.isPosted = isPosted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.from_date_from
     *
     * @return the value of work_effort_party_assignment.from_date_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getFromDateFrom() {
        return fromDateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.from_date_from
     *
     * @param fromDateFrom the value for work_effort_party_assignment.from_date_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setFromDateFrom(Instant fromDateFrom) {
        this.fromDateFrom = fromDateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.work_effort_id_from
     *
     * @return the value of work_effort_party_assignment.work_effort_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getWorkEffortIdFrom() {
        return workEffortIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.work_effort_id_from
     *
     * @param workEffortIdFrom the value for work_effort_party_assignment.work_effort_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setWorkEffortIdFrom(String workEffortIdFrom) {
        this.workEffortIdFrom = workEffortIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.party_id_from
     *
     * @return the value of work_effort_party_assignment.party_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getPartyIdFrom() {
        return partyIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.party_id_from
     *
     * @param partyIdFrom the value for work_effort_party_assignment.party_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setPartyIdFrom(String partyIdFrom) {
        this.partyIdFrom = partyIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.role_type_id_from
     *
     * @return the value of work_effort_party_assignment.role_type_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getRoleTypeIdFrom() {
        return roleTypeIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.role_type_id_from
     *
     * @param roleTypeIdFrom the value for work_effort_party_assignment.role_type_id_from
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setRoleTypeIdFrom(String roleTypeIdFrom) {
        this.roleTypeIdFrom = roleTypeIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.sequence_num
     *
     * @return the value of work_effort_party_assignment.sequence_num
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public BigDecimal getSequenceNum() {
        return sequenceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.sequence_num
     *
     * @param sequenceNum the value for work_effort_party_assignment.sequence_num
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setSequenceNum(BigDecimal sequenceNum) {
        this.sequenceNum = sequenceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.last_modified_by_user_login
     *
     * @return the value of work_effort_party_assignment.last_modified_by_user_login
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for work_effort_party_assignment.last_modified_by_user_login
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.created_by_user_login
     *
     * @return the value of work_effort_party_assignment.created_by_user_login
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.created_by_user_login
     *
     * @param createdByUserLogin the value for work_effort_party_assignment.created_by_user_login
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.planned_hours
     *
     * @return the value of work_effort_party_assignment.planned_hours
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Double getPlannedHours() {
        return plannedHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.planned_hours
     *
     * @param plannedHours the value for work_effort_party_assignment.planned_hours
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setPlannedHours(Double plannedHours) {
        this.plannedHours = plannedHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.comments_lang
     *
     * @return the value of work_effort_party_assignment.comments_lang
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getCommentsLang() {
        return commentsLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.comments_lang
     *
     * @param commentsLang the value for work_effort_party_assignment.comments_lang
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setCommentsLang(String commentsLang) {
        this.commentsLang = commentsLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_date
     *
     * @return the value of work_effort_party_assignment.end_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public Instant getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_date
     *
     * @param endDate the value for work_effort_party_assignment.end_date
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndDate(Instant endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_cause_enum_id
     *
     * @return the value of work_effort_party_assignment.end_cause_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getEndCauseEnumId() {
        return endCauseEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_cause_enum_id
     *
     * @param endCauseEnumId the value for work_effort_party_assignment.end_cause_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndCauseEnumId(String endCauseEnumId) {
        this.endCauseEnumId = endCauseEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_replacement_enum_id
     *
     * @return the value of work_effort_party_assignment.end_replacement_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getEndReplacementEnumId() {
        return endReplacementEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_replacement_enum_id
     *
     * @param endReplacementEnumId the value for work_effort_party_assignment.end_replacement_enum_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndReplacementEnumId(String endReplacementEnumId) {
        this.endReplacementEnumId = endReplacementEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_work_effort_id
     *
     * @return the value of work_effort_party_assignment.end_work_effort_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getEndWorkEffortId() {
        return endWorkEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_work_effort_id
     *
     * @param endWorkEffortId the value for work_effort_party_assignment.end_work_effort_id
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndWorkEffortId(String endWorkEffortId) {
        this.endWorkEffortId = endWorkEffortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_work_effort_id_we1
     *
     * @return the value of work_effort_party_assignment.end_work_effort_id_we1
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getEndWorkEffortIdWe1() {
        return endWorkEffortIdWe1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_work_effort_id_we1
     *
     * @param endWorkEffortIdWe1 the value for work_effort_party_assignment.end_work_effort_id_we1
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndWorkEffortIdWe1(String endWorkEffortIdWe1) {
        this.endWorkEffortIdWe1 = endWorkEffortIdWe1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_work_effort_id_we2
     *
     * @return the value of work_effort_party_assignment.end_work_effort_id_we2
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getEndWorkEffortIdWe2() {
        return endWorkEffortIdWe2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_work_effort_id_we2
     *
     * @param endWorkEffortIdWe2 the value for work_effort_party_assignment.end_work_effort_id_we2
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndWorkEffortIdWe2(String endWorkEffortIdWe2) {
        this.endWorkEffortIdWe2 = endWorkEffortIdWe2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_party_assignment.end_work_effort_id_we3
     *
     * @return the value of work_effort_party_assignment.end_work_effort_id_we3
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public String getEndWorkEffortIdWe3() {
        return endWorkEffortIdWe3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_party_assignment.end_work_effort_id_we3
     *
     * @param endWorkEffortIdWe3 the value for work_effort_party_assignment.end_work_effort_id_we3
     *
     * @mbg.generated Tue Oct 17 10:10:35 CEST 2023
     */
    public void setEndWorkEffortIdWe3(String endWorkEffortIdWe3) {
        this.endWorkEffortIdWe3 = endWorkEffortIdWe3;
    }
}