package it.mapsgroup.gzoom.mybatis.dto;

import java.time.Instant;

public class WorkEffortRevision {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.work_effort_revision_id
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String workEffortRevisionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.work_effort_type_id_ctx
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String workEffortTypeIdCtx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.work_effort_type_id_fil
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String workEffortTypeIdFil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.ref_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant refDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.description
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.comments
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.is_closed
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String isClosed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.has_acctg_trans
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String hasAcctgTrans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.is_automatic
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String isAutomatic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.from_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.to_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant toDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.organization_id
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.last_modified_by_user_login
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String lastModifiedByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.created_by_user_login
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private String createdByUserLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.last_updated_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant lastUpdatedStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant lastUpdatedTxStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.created_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant createdStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_effort_revision.created_tx_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    private Instant createdTxStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.work_effort_revision_id
     *
     * @return the value of work_effort_revision.work_effort_revision_id
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getWorkEffortRevisionId() {
        return workEffortRevisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.work_effort_revision_id
     *
     * @param workEffortRevisionId the value for work_effort_revision.work_effort_revision_id
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setWorkEffortRevisionId(String workEffortRevisionId) {
        this.workEffortRevisionId = workEffortRevisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.work_effort_type_id_ctx
     *
     * @return the value of work_effort_revision.work_effort_type_id_ctx
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getWorkEffortTypeIdCtx() {
        return workEffortTypeIdCtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.work_effort_type_id_ctx
     *
     * @param workEffortTypeIdCtx the value for work_effort_revision.work_effort_type_id_ctx
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setWorkEffortTypeIdCtx(String workEffortTypeIdCtx) {
        this.workEffortTypeIdCtx = workEffortTypeIdCtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.work_effort_type_id_fil
     *
     * @return the value of work_effort_revision.work_effort_type_id_fil
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getWorkEffortTypeIdFil() {
        return workEffortTypeIdFil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.work_effort_type_id_fil
     *
     * @param workEffortTypeIdFil the value for work_effort_revision.work_effort_type_id_fil
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setWorkEffortTypeIdFil(String workEffortTypeIdFil) {
        this.workEffortTypeIdFil = workEffortTypeIdFil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.ref_date
     *
     * @return the value of work_effort_revision.ref_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getRefDate() {
        return refDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.ref_date
     *
     * @param refDate the value for work_effort_revision.ref_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setRefDate(Instant refDate) {
        this.refDate = refDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.description
     *
     * @return the value of work_effort_revision.description
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.description
     *
     * @param description the value for work_effort_revision.description
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.comments
     *
     * @return the value of work_effort_revision.comments
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.comments
     *
     * @param comments the value for work_effort_revision.comments
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.is_closed
     *
     * @return the value of work_effort_revision.is_closed
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getIsClosed() {
        return isClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.is_closed
     *
     * @param isClosed the value for work_effort_revision.is_closed
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setIsClosed(String isClosed) {
        this.isClosed = isClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.has_acctg_trans
     *
     * @return the value of work_effort_revision.has_acctg_trans
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getHasAcctgTrans() {
        return hasAcctgTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.has_acctg_trans
     *
     * @param hasAcctgTrans the value for work_effort_revision.has_acctg_trans
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setHasAcctgTrans(String hasAcctgTrans) {
        this.hasAcctgTrans = hasAcctgTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.is_automatic
     *
     * @return the value of work_effort_revision.is_automatic
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getIsAutomatic() {
        return isAutomatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.is_automatic
     *
     * @param isAutomatic the value for work_effort_revision.is_automatic
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setIsAutomatic(String isAutomatic) {
        this.isAutomatic = isAutomatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.from_date
     *
     * @return the value of work_effort_revision.from_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.from_date
     *
     * @param fromDate the value for work_effort_revision.from_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setFromDate(Instant fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.to_date
     *
     * @return the value of work_effort_revision.to_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.to_date
     *
     * @param toDate the value for work_effort_revision.to_date
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setToDate(Instant toDate) {
        this.toDate = toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.organization_id
     *
     * @return the value of work_effort_revision.organization_id
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.organization_id
     *
     * @param organizationId the value for work_effort_revision.organization_id
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.last_modified_by_user_login
     *
     * @return the value of work_effort_revision.last_modified_by_user_login
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.last_modified_by_user_login
     *
     * @param lastModifiedByUserLogin the value for work_effort_revision.last_modified_by_user_login
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.created_by_user_login
     *
     * @return the value of work_effort_revision.created_by_user_login
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.created_by_user_login
     *
     * @param createdByUserLogin the value for work_effort_revision.created_by_user_login
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.last_updated_stamp
     *
     * @return the value of work_effort_revision.last_updated_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.last_updated_stamp
     *
     * @param lastUpdatedStamp the value for work_effort_revision.last_updated_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setLastUpdatedStamp(Instant lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.last_updated_tx_stamp
     *
     * @return the value of work_effort_revision.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.last_updated_tx_stamp
     *
     * @param lastUpdatedTxStamp the value for work_effort_revision.last_updated_tx_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setLastUpdatedTxStamp(Instant lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.created_stamp
     *
     * @return the value of work_effort_revision.created_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.created_stamp
     *
     * @param createdStamp the value for work_effort_revision.created_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setCreatedStamp(Instant createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_effort_revision.created_tx_stamp
     *
     * @return the value of work_effort_revision.created_tx_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public Instant getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_effort_revision.created_tx_stamp
     *
     * @param createdTxStamp the value for work_effort_revision.created_tx_stamp
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    public void setCreatedTxStamp(Instant createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
}