package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.AcctgTrans;
import it.mapsgroup.gzoom.mybatis.dto.AcctgTransEntry;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AcctgTransMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acctg_trans
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    @Delete({
        "delete from acctg_trans",
        "where acctg_trans_id = #{acctgTransId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String acctgTransId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acctg_trans
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    @Insert({
        "insert into acctg_trans (acctg_trans_id, acctg_trans_type_id, ",
        "description, transaction_date, ",
        "is_posted, posted_date, ",
        "scheduled_posting_date, gl_journal_id, ",
        "gl_fiscal_type_id, voucher_ref, ",
        "voucher_date, group_status_id, ",
        "fixed_asset_id, inventory_item_id, ",
        "physical_inventory_id, party_id, ",
        "role_type_id, invoice_id, ",
        "payment_id, fin_account_trans_id, ",
        "shipment_id, receipt_id, ",
        "work_effort_id, their_acctg_trans_id, ",
        "created_by_user_login, last_modified_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "snapshot_date, work_effort_snapshot_id, ",
        "work_effort_revision_id, description_lang)",
        "values (#{acctgTransId,jdbcType=VARCHAR}, #{acctgTransTypeId,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{transactionDate,jdbcType=TIMESTAMP}, ",
        "#{isPosted,jdbcType=CHAR}, #{postedDate,jdbcType=TIMESTAMP}, ",
        "#{scheduledPostingDate,jdbcType=TIMESTAMP}, #{glJournalId,jdbcType=VARCHAR}, ",
        "#{glFiscalTypeId,jdbcType=VARCHAR}, #{voucherRef,jdbcType=VARCHAR}, ",
        "#{voucherDate,jdbcType=TIMESTAMP}, #{groupStatusId,jdbcType=VARCHAR}, ",
        "#{fixedAssetId,jdbcType=VARCHAR}, #{inventoryItemId,jdbcType=VARCHAR}, ",
        "#{physicalInventoryId,jdbcType=VARCHAR}, #{partyId,jdbcType=VARCHAR}, ",
        "#{roleTypeId,jdbcType=VARCHAR}, #{invoiceId,jdbcType=VARCHAR}, ",
        "#{paymentId,jdbcType=VARCHAR}, #{finAccountTransId,jdbcType=VARCHAR}, ",
        "#{shipmentId,jdbcType=VARCHAR}, #{receiptId,jdbcType=VARCHAR}, ",
        "#{workEffortId,jdbcType=VARCHAR}, #{theirAcctgTransId,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{snapshotDate,jdbcType=TIMESTAMP}, #{workEffortSnapshotId,jdbcType=VARCHAR}, ",
        "#{workEffortRevisionId,jdbcType=VARCHAR}, #{descriptionLang,jdbcType=VARCHAR})"
    })
    int insert(AcctgTrans row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acctg_trans
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    @Select({
        "select",
        "acctg_trans_id, acctg_trans_type_id, description, transaction_date, is_posted, ",
        "posted_date, scheduled_posting_date, gl_journal_id, gl_fiscal_type_id, voucher_ref, ",
        "voucher_date, group_status_id, fixed_asset_id, inventory_item_id, physical_inventory_id, ",
        "party_id, role_type_id, invoice_id, payment_id, fin_account_trans_id, shipment_id, ",
        "receipt_id, work_effort_id, their_acctg_trans_id, created_by_user_login, last_modified_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp, ",
        "snapshot_date, work_effort_snapshot_id, work_effort_revision_id, description_lang",
        "from acctg_trans",
        "where acctg_trans_id = #{acctgTransId,jdbcType=VARCHAR}"
    })
    @Results(id = "acctgTransMapper", value = {
        @Result(column="acctg_trans_id", property="acctgTransId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="acctg_trans_type_id", property="acctgTransTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="transaction_date", property="transactionDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
        @Result(column="posted_date", property="postedDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="scheduled_posting_date", property="scheduledPostingDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gl_journal_id", property="glJournalId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_fiscal_type_id", property="glFiscalTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="voucher_ref", property="voucherRef", jdbcType=JdbcType.VARCHAR),
        @Result(column="voucher_date", property="voucherDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="group_status_id", property="groupStatusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="fixed_asset_id", property="fixedAssetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_item_id", property="inventoryItemId", jdbcType=JdbcType.VARCHAR),
        @Result(column="physical_inventory_id", property="physicalInventoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_id", property="invoiceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="fin_account_trans_id", property="finAccountTransId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shipment_id", property="shipmentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="receipt_id", property="receiptId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="their_acctg_trans_id", property="theirAcctgTransId", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="snapshot_date", property="snapshotDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="work_effort_snapshot_id", property="workEffortSnapshotId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_revision_id", property="workEffortRevisionId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR)
    })
    AcctgTrans selectByPrimaryKey(String acctgTransId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acctg_trans
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    @Select({
        "select",
        "acctg_trans_id, acctg_trans_type_id, description, transaction_date, is_posted, ",
        "posted_date, scheduled_posting_date, gl_journal_id, gl_fiscal_type_id, voucher_ref, ",
        "voucher_date, group_status_id, fixed_asset_id, inventory_item_id, physical_inventory_id, ",
        "party_id, role_type_id, invoice_id, payment_id, fin_account_trans_id, shipment_id, ",
        "receipt_id, work_effort_id, their_acctg_trans_id, created_by_user_login, last_modified_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp, ",
        "snapshot_date, work_effort_snapshot_id, work_effort_revision_id, description_lang",
        "from acctg_trans"
    })
    @Results(id = "accTransResultMap", value = {
        @Result(column="acctg_trans_id", property="acctgTransId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="acctg_trans_type_id", property="acctgTransTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="transaction_date", property="transactionDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
        @Result(column="posted_date", property="postedDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="scheduled_posting_date", property="scheduledPostingDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gl_journal_id", property="glJournalId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_fiscal_type_id", property="glFiscalTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="voucher_ref", property="voucherRef", jdbcType=JdbcType.VARCHAR),
        @Result(column="voucher_date", property="voucherDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="group_status_id", property="groupStatusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="fixed_asset_id", property="fixedAssetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_item_id", property="inventoryItemId", jdbcType=JdbcType.VARCHAR),
        @Result(column="physical_inventory_id", property="physicalInventoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_id", property="invoiceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="fin_account_trans_id", property="finAccountTransId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shipment_id", property="shipmentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="receipt_id", property="receiptId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="their_acctg_trans_id", property="theirAcctgTransId", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="snapshot_date", property="snapshotDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="work_effort_snapshot_id", property="workEffortSnapshotId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_revision_id", property="workEffortRevisionId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR)
    })
    List<AcctgTrans> selectAll();

    @Select({
            "select * ",
            "from acctg_trans at",
            "where at.voucher_ref = #{workEffortMeasureId}"
    })
    @ResultMap("accTransResultMap")
    List<AcctgTrans> getAcctgTransByWorkEffortMeasureId(@Param("workEffortMeasureId") String workEffortMeasureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acctg_trans
     *
     * @mbg.generated Fri Nov 17 16:33:54 CET 2023
     */
    @Update({
        "update acctg_trans",
        "set acctg_trans_type_id = #{acctgTransTypeId,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "transaction_date = #{transactionDate,jdbcType=TIMESTAMP},",
          "is_posted = #{isPosted,jdbcType=CHAR},",
          "posted_date = #{postedDate,jdbcType=TIMESTAMP},",
          "scheduled_posting_date = #{scheduledPostingDate,jdbcType=TIMESTAMP},",
          "gl_journal_id = #{glJournalId,jdbcType=VARCHAR},",
          "gl_fiscal_type_id = #{glFiscalTypeId,jdbcType=VARCHAR},",
          "voucher_ref = #{voucherRef,jdbcType=VARCHAR},",
          "voucher_date = #{voucherDate,jdbcType=TIMESTAMP},",
          "group_status_id = #{groupStatusId,jdbcType=VARCHAR},",
          "fixed_asset_id = #{fixedAssetId,jdbcType=VARCHAR},",
          "inventory_item_id = #{inventoryItemId,jdbcType=VARCHAR},",
          "physical_inventory_id = #{physicalInventoryId,jdbcType=VARCHAR},",
          "party_id = #{partyId,jdbcType=VARCHAR},",
          "role_type_id = #{roleTypeId,jdbcType=VARCHAR},",
          "invoice_id = #{invoiceId,jdbcType=VARCHAR},",
          "payment_id = #{paymentId,jdbcType=VARCHAR},",
          "fin_account_trans_id = #{finAccountTransId,jdbcType=VARCHAR},",
          "shipment_id = #{shipmentId,jdbcType=VARCHAR},",
          "receipt_id = #{receiptId,jdbcType=VARCHAR},",
          "work_effort_id = #{workEffortId,jdbcType=VARCHAR},",
          "their_acctg_trans_id = #{theirAcctgTransId,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "snapshot_date = #{snapshotDate,jdbcType=TIMESTAMP},",
          "work_effort_snapshot_id = #{workEffortSnapshotId,jdbcType=VARCHAR},",
          "work_effort_revision_id = #{workEffortRevisionId,jdbcType=VARCHAR},",
          "description_lang = #{descriptionLang,jdbcType=VARCHAR}",
        "where acctg_trans_id = #{acctgTransId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AcctgTrans row);

    @Update({
            "update acctg_trans",
            "set",
            "party_id = #{partyId,jdbcType=VARCHAR},",
            "role_type_id = #{roleTypeId,jdbcType=VARCHAR},",
            "gl_fiscal_type_id = #{glFiscalTypeId,jdbcType=VARCHAR},",
            "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
            "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
            "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
            "where acctg_trans_id = #{acctgTransId,jdbcType=VARCHAR}"
    })
    int updatePartialTable(AcctgTrans row);


    @Update({
            "update acctg_trans",
            "set",
            "description = #{description,jdbcType=VARCHAR},",
            "is_posted = #{isPosted,jdbcType=CHAR},",
            "gl_fiscal_type_id = #{glFiscalTypeId,jdbcType=VARCHAR},",
            "voucher_ref = #{voucherRef,jdbcType=VARCHAR},",
            "party_id = #{partyId,jdbcType=VARCHAR},",
            "role_type_id = #{roleTypeId,jdbcType=VARCHAR},",
            "work_effort_id = #{workEffortId,jdbcType=VARCHAR},",
            "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
            "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
            "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
             "description_lang = #{descriptionLang,jdbcType=VARCHAR}",
            "where acctg_trans_id = #{acctgTransId,jdbcType=VARCHAR}"
    })
    int updateDetail(AcctgTrans acctgTrans);
}