package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.DataSource;
import it.mapsgroup.gzoom.mybatis.dto.DataSourceEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface DataSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated Tue Dec 05 12:22:58 CET 2023
     */
    @Delete({
        "delete from data_source",
        "where data_source_id = #{dataSourceId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String dataSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated Tue Dec 05 12:22:58 CET 2023
     */
    @Insert({
        "insert into data_source (data_source_id, data_source_type_id, ",
        "description, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, val_mod_id, ",
        "last_modified_by_user_login, created_by_user_login)",
        "values (#{dataSourceId,jdbcType=VARCHAR}, #{dataSourceTypeId,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP}, #{valModId,jdbcType=VARCHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(DataSource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated Tue Dec 05 12:22:58 CET 2023
     */
    @Select({
        "select",
        "data_source_id, data_source_type_id, description, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, val_mod_id, last_modified_by_user_login, created_by_user_login",
        "from data_source",
        "where data_source_id = #{dataSourceId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="data_source_id", property="dataSourceId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="data_source_type_id", property="dataSourceTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="val_mod_id", property="valModId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    DataSource selectByPrimaryKey(String dataSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated Tue Dec 05 12:22:58 CET 2023
     */
    @Select({
        "select",
        "data_source_id, data_source_type_id, description, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, val_mod_id, last_modified_by_user_login, created_by_user_login",
        "from data_source"
    })
    @Results({
        @Result(column="data_source_id", property="dataSourceId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="data_source_type_id", property="dataSourceTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="val_mod_id", property="valModId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<DataSource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbg.generated Tue Dec 05 12:22:58 CET 2023
     */
    @Update({
        "update data_source",
        "set data_source_type_id = #{dataSourceTypeId,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "val_mod_id = #{valModId,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR}",
        "where data_source_id = #{dataSourceId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(DataSource row);

    List<DataSourceEx> getDataSourceEx();


}