package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.EnumerationType;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface EnumerationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enumeration_type
     *
     * @mbg.generated Mon Dec 18 09:27:22 CET 2023
     */
    @Delete({
        "delete from enumeration_type",
        "where enum_type_id = #{enumTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String enumTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enumeration_type
     *
     * @mbg.generated Mon Dec 18 09:27:22 CET 2023
     */
    @Insert({
        "insert into enumeration_type (enum_type_id, parent_type_id, ",
        "has_table, description, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{enumTypeId,jdbcType=VARCHAR}, #{parentTypeId,jdbcType=VARCHAR}, ",
        "#{hasTable,jdbcType=CHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(EnumerationType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enumeration_type
     *
     * @mbg.generated Mon Dec 18 09:27:22 CET 2023
     */
    @Select({
        "select",
        "enum_type_id, parent_type_id, has_table, description, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp",
        "from enumeration_type",
        "where enum_type_id = #{enumTypeId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="enum_type_id", property="enumTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_type_id", property="parentTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_table", property="hasTable", jdbcType=JdbcType.CHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    EnumerationType selectByPrimaryKey(String enumTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enumeration_type
     *
     * @mbg.generated Mon Dec 18 09:27:22 CET 2023
     */
    @Select({
        "select",
        "enum_type_id, parent_type_id, has_table, description, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp",
        "from enumeration_type"
    })
    @Results({
        @Result(column="enum_type_id", property="enumTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_type_id", property="parentTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_table", property="hasTable", jdbcType=JdbcType.CHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<EnumerationType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enumeration_type
     *
     * @mbg.generated Mon Dec 18 09:27:22 CET 2023
     */
    @Update({
        "update enumeration_type",
        "set parent_type_id = #{parentTypeId,jdbcType=VARCHAR},",
          "has_table = #{hasTable,jdbcType=CHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP}",
        "where enum_type_id = #{enumTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EnumerationType row);
}