package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.GlAccountInterfaceExt;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface GlAccountInterfaceExtMapper {

    @Delete({
        "delete from gl_account_interface_ext",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);


    @Insert({
        "insert into gl_account_interface_ext (id, stato, ",
        "data_source, ref_date, ",
        "account_code, account_type_id, ",
        "account_name, description, ",
        "referenced_account_code, product_id, ",
        "party_id_cdr, role_type_id_cdr, ",
        "party_id_cdc, role_type_id_cdc, ",
        "purpose_type_id, debit_credit_default, ",
        "from_date, thru_date, ",
        "account_type_enum_id, default_uom_code, ",
        "period_type_desc, gl_resource_type_id, ",
        "source, we_measure_type_enum_id, ",
        "input_enum_id, calc_custom_method_id, ",
        "prio_calc, detect_org_unit_id_flag, ",
        "account_name_lang, description_lang, ",
        "source_lang, uom_range_id, ",
        "gl_account_class_code, custom_text01, ",
        "custom_text02, custom_text03, ",
        "custom_text04, custom_text05, ",
        "custom_date01, custom_date02, ",
        "custom_date03, custom_date04, ",
        "custom_date05, custom_value01, ",
        "custom_value02, custom_value03, ",
        "custom_value04, custom_value05, ",
        "seq)",
        "values (#{id,jdbcType=VARCHAR}, #{stato,jdbcType=VARCHAR}, ",
        "#{dataSource,jdbcType=VARCHAR}, #{refDate,jdbcType=TIMESTAMP}, ",
        "#{accountCode,jdbcType=VARCHAR}, #{accountTypeId,jdbcType=VARCHAR}, ",
        "#{accountName,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{referencedAccountCode,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR}, ",
        "#{partyIdCdr,jdbcType=VARCHAR}, #{roleTypeIdCdr,jdbcType=VARCHAR}, ",
        "#{partyIdCdc,jdbcType=VARCHAR}, #{roleTypeIdCdc,jdbcType=VARCHAR}, ",
        "#{purposeTypeId,jdbcType=VARCHAR}, #{debitCreditDefault,jdbcType=CHAR}, ",
        "#{fromDate,jdbcType=TIMESTAMP}, #{thruDate,jdbcType=TIMESTAMP}, ",
        "#{accountTypeEnumId,jdbcType=VARCHAR}, #{defaultUomCode,jdbcType=VARCHAR}, ",
        "#{periodTypeDesc,jdbcType=VARCHAR}, #{glResourceTypeId,jdbcType=VARCHAR}, ",
        "#{source,jdbcType=VARCHAR}, #{weMeasureTypeEnumId,jdbcType=VARCHAR}, ",
        "#{inputEnumId,jdbcType=VARCHAR}, #{calcCustomMethodId,jdbcType=VARCHAR}, ",
        "#{prioCalc,jdbcType=NUMERIC}, #{detectOrgUnitIdFlag,jdbcType=CHAR}, ",
        "#{accountNameLang,jdbcType=VARCHAR}, #{descriptionLang,jdbcType=VARCHAR}, ",
        "#{sourceLang,jdbcType=VARCHAR}, #{uomRangeId,jdbcType=VARCHAR}, ",
        "#{glAccountClassCode,jdbcType=VARCHAR}, #{customText01,jdbcType=VARCHAR}, ",
        "#{customText02,jdbcType=VARCHAR}, #{customText03,jdbcType=VARCHAR}, ",
        "#{customText04,jdbcType=VARCHAR}, #{customText05,jdbcType=VARCHAR}, ",
        "#{customDate01,jdbcType=TIMESTAMP}, #{customDate02,jdbcType=TIMESTAMP}, ",
        "#{customDate03,jdbcType=TIMESTAMP}, #{customDate04,jdbcType=TIMESTAMP}, ",
        "#{customDate05,jdbcType=TIMESTAMP}, #{customValue01,jdbcType=DOUBLE}, ",
        "#{customValue02,jdbcType=DOUBLE}, #{customValue03,jdbcType=DOUBLE}, ",
        "#{customValue04,jdbcType=DOUBLE}, #{customValue05,jdbcType=DOUBLE}, ",
        "#{seq,jdbcType=NUMERIC})"
    })
    int insert(GlAccountInterfaceExt row);


    @Select({
        "select",
        "id, stato, data_source, ref_date, account_code, account_type_id, account_name, ",
        "description, referenced_account_code, product_id, party_id_cdr, role_type_id_cdr, ",
        "party_id_cdc, role_type_id_cdc, purpose_type_id, debit_credit_default, from_date, ",
        "thru_date, account_type_enum_id, default_uom_code, period_type_desc, gl_resource_type_id, ",
        "source, we_measure_type_enum_id, input_enum_id, calc_custom_method_id, prio_calc, ",
        "detect_org_unit_id_flag, account_name_lang, description_lang, source_lang, uom_range_id, ",
        "gl_account_class_code, custom_text01, custom_text02, custom_text03, custom_text04, ",
        "custom_text05, custom_date01, custom_date02, custom_date03, custom_date04, custom_date05, ",
        "custom_value01, custom_value02, custom_value03, custom_value04, custom_value05, ",
        "seq",
        "from gl_account_interface_ext",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="stato", property="stato", jdbcType=JdbcType.VARCHAR),
        @Result(column="data_source", property="dataSource", jdbcType=JdbcType.VARCHAR),
        @Result(column="ref_date", property="refDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="account_code", property="accountCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="account_type_id", property="accountTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="account_name", property="accountName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="referenced_account_code", property="referencedAccountCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_cdr", property="partyIdCdr", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id_cdr", property="roleTypeIdCdr", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_cdc", property="partyIdCdc", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id_cdc", property="roleTypeIdCdc", jdbcType=JdbcType.VARCHAR),
        @Result(column="purpose_type_id", property="purposeTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="debit_credit_default", property="debitCreditDefault", jdbcType=JdbcType.CHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="account_type_enum_id", property="accountTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="default_uom_code", property="defaultUomCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="period_type_desc", property="periodTypeDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_resource_type_id", property="glResourceTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_measure_type_enum_id", property="weMeasureTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_enum_id", property="inputEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="calc_custom_method_id", property="calcCustomMethodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="prio_calc", property="prioCalc", jdbcType=JdbcType.NUMERIC),
        @Result(column="detect_org_unit_id_flag", property="detectOrgUnitIdFlag", jdbcType=JdbcType.CHAR),
        @Result(column="account_name_lang", property="accountNameLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="source_lang", property="sourceLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_range_id", property="uomRangeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_account_class_code", property="glAccountClassCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text01", property="customText01", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text02", property="customText02", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text03", property="customText03", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text04", property="customText04", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text05", property="customText05", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_date01", property="customDate01", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date02", property="customDate02", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date03", property="customDate03", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date04", property="customDate04", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date05", property="customDate05", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_value01", property="customValue01", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value02", property="customValue02", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value03", property="customValue03", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value04", property="customValue04", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value05", property="customValue05", jdbcType=JdbcType.DOUBLE),
        @Result(column="seq", property="seq", jdbcType=JdbcType.NUMERIC)
    })
    GlAccountInterfaceExt selectByPrimaryKey(String id);


    @Select({
        "select",
        "id, stato, data_source, ref_date, account_code, account_type_id, account_name, ",
        "description, referenced_account_code, product_id, party_id_cdr, role_type_id_cdr, ",
        "party_id_cdc, role_type_id_cdc, purpose_type_id, debit_credit_default, from_date, ",
        "thru_date, account_type_enum_id, default_uom_code, period_type_desc, gl_resource_type_id, ",
        "source, we_measure_type_enum_id, input_enum_id, calc_custom_method_id, prio_calc, ",
        "detect_org_unit_id_flag, account_name_lang, description_lang, source_lang, uom_range_id, ",
        "gl_account_class_code, custom_text01, custom_text02, custom_text03, custom_text04, ",
        "custom_text05, custom_date01, custom_date02, custom_date03, custom_date04, custom_date05, ",
        "custom_value01, custom_value02, custom_value03, custom_value04, custom_value05, ",
        "seq",
        "from gl_account_interface_ext"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="stato", property="stato", jdbcType=JdbcType.VARCHAR),
        @Result(column="data_source", property="dataSource", jdbcType=JdbcType.VARCHAR),
        @Result(column="ref_date", property="refDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="account_code", property="accountCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="account_type_id", property="accountTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="account_name", property="accountName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="referenced_account_code", property="referencedAccountCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_cdr", property="partyIdCdr", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id_cdr", property="roleTypeIdCdr", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_cdc", property="partyIdCdc", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id_cdc", property="roleTypeIdCdc", jdbcType=JdbcType.VARCHAR),
        @Result(column="purpose_type_id", property="purposeTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="debit_credit_default", property="debitCreditDefault", jdbcType=JdbcType.CHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="account_type_enum_id", property="accountTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="default_uom_code", property="defaultUomCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="period_type_desc", property="periodTypeDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_resource_type_id", property="glResourceTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_measure_type_enum_id", property="weMeasureTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_enum_id", property="inputEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="calc_custom_method_id", property="calcCustomMethodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="prio_calc", property="prioCalc", jdbcType=JdbcType.NUMERIC),
        @Result(column="detect_org_unit_id_flag", property="detectOrgUnitIdFlag", jdbcType=JdbcType.CHAR),
        @Result(column="account_name_lang", property="accountNameLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="source_lang", property="sourceLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_range_id", property="uomRangeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_account_class_code", property="glAccountClassCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text01", property="customText01", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text02", property="customText02", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text03", property="customText03", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text04", property="customText04", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_text05", property="customText05", jdbcType=JdbcType.VARCHAR),
        @Result(column="custom_date01", property="customDate01", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date02", property="customDate02", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date03", property="customDate03", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date04", property="customDate04", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_date05", property="customDate05", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="custom_value01", property="customValue01", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value02", property="customValue02", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value03", property="customValue03", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value04", property="customValue04", jdbcType=JdbcType.DOUBLE),
        @Result(column="custom_value05", property="customValue05", jdbcType=JdbcType.DOUBLE),
        @Result(column="seq", property="seq", jdbcType=JdbcType.NUMERIC)
    })
    List<GlAccountInterfaceExt> selectAll();


    @Update({
        "update gl_account_interface_ext",
        "set stato = #{stato,jdbcType=VARCHAR},",
          "data_source = #{dataSource,jdbcType=VARCHAR},",
          "ref_date = #{refDate,jdbcType=TIMESTAMP},",
          "account_code = #{accountCode,jdbcType=VARCHAR},",
          "account_type_id = #{accountTypeId,jdbcType=VARCHAR},",
          "account_name = #{accountName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "referenced_account_code = #{referencedAccountCode,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=VARCHAR},",
          "party_id_cdr = #{partyIdCdr,jdbcType=VARCHAR},",
          "role_type_id_cdr = #{roleTypeIdCdr,jdbcType=VARCHAR},",
          "party_id_cdc = #{partyIdCdc,jdbcType=VARCHAR},",
          "role_type_id_cdc = #{roleTypeIdCdc,jdbcType=VARCHAR},",
          "purpose_type_id = #{purposeTypeId,jdbcType=VARCHAR},",
          "debit_credit_default = #{debitCreditDefault,jdbcType=CHAR},",
          "from_date = #{fromDate,jdbcType=TIMESTAMP},",
          "thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "account_type_enum_id = #{accountTypeEnumId,jdbcType=VARCHAR},",
          "default_uom_code = #{defaultUomCode,jdbcType=VARCHAR},",
          "period_type_desc = #{periodTypeDesc,jdbcType=VARCHAR},",
          "gl_resource_type_id = #{glResourceTypeId,jdbcType=VARCHAR},",
          "source = #{source,jdbcType=VARCHAR},",
          "we_measure_type_enum_id = #{weMeasureTypeEnumId,jdbcType=VARCHAR},",
          "input_enum_id = #{inputEnumId,jdbcType=VARCHAR},",
          "calc_custom_method_id = #{calcCustomMethodId,jdbcType=VARCHAR},",
          "prio_calc = #{prioCalc,jdbcType=NUMERIC},",
          "detect_org_unit_id_flag = #{detectOrgUnitIdFlag,jdbcType=CHAR},",
          "account_name_lang = #{accountNameLang,jdbcType=VARCHAR},",
          "description_lang = #{descriptionLang,jdbcType=VARCHAR},",
          "source_lang = #{sourceLang,jdbcType=VARCHAR},",
          "uom_range_id = #{uomRangeId,jdbcType=VARCHAR},",
          "gl_account_class_code = #{glAccountClassCode,jdbcType=VARCHAR},",
          "custom_text01 = #{customText01,jdbcType=VARCHAR},",
          "custom_text02 = #{customText02,jdbcType=VARCHAR},",
          "custom_text03 = #{customText03,jdbcType=VARCHAR},",
          "custom_text04 = #{customText04,jdbcType=VARCHAR},",
          "custom_text05 = #{customText05,jdbcType=VARCHAR},",
          "custom_date01 = #{customDate01,jdbcType=TIMESTAMP},",
          "custom_date02 = #{customDate02,jdbcType=TIMESTAMP},",
          "custom_date03 = #{customDate03,jdbcType=TIMESTAMP},",
          "custom_date04 = #{customDate04,jdbcType=TIMESTAMP},",
          "custom_date05 = #{customDate05,jdbcType=TIMESTAMP},",
          "custom_value01 = #{customValue01,jdbcType=DOUBLE},",
          "custom_value02 = #{customValue02,jdbcType=DOUBLE},",
          "custom_value03 = #{customValue03,jdbcType=DOUBLE},",
          "custom_value04 = #{customValue04,jdbcType=DOUBLE},",
          "custom_value05 = #{customValue05,jdbcType=DOUBLE},",
          "seq = #{seq,jdbcType=NUMERIC}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GlAccountInterfaceExt row);
}