package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.JobLogJobExecParams;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface JobLogJobExecParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log_job_exec_params
     *
     * @mbg.generated Wed Dec 13 11:06:11 CET 2023
     */
    @Delete({
        "delete from job_log_job_exec_params",
        "where job_log_id = #{jobLogId,jdbcType=VARCHAR}",
          "and parameter_name = #{parameterName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("jobLogId") String jobLogId, @Param("parameterName") String parameterName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log_job_exec_params
     *
     * @mbg.generated Wed Dec 13 11:06:11 CET 2023
     */
    @Insert({
        "insert into job_log_job_exec_params (job_log_id, parameter_name, ",
        "parameter_description, parameter_type, ",
        "parameter_value, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp)",
        "values (#{jobLogId,jdbcType=VARCHAR}, #{parameterName,jdbcType=VARCHAR}, ",
        "#{parameterDescription,jdbcType=VARCHAR}, #{parameterType,jdbcType=VARCHAR}, ",
        "#{parameterValue,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(JobLogJobExecParams row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log_job_exec_params
     *
     * @mbg.generated Wed Dec 13 11:06:11 CET 2023
     */
    @Select({
        "select",
        "job_log_id, parameter_name, parameter_description, parameter_type, parameter_value, ",
        "last_modified_by_user_login, created_by_user_login, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp",
        "from job_log_job_exec_params",
        "where job_log_id = #{jobLogId,jdbcType=VARCHAR}",
          "and parameter_name = #{parameterName,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="job_log_id", property="jobLogId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parameter_name", property="parameterName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parameter_description", property="parameterDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="parameter_type", property="parameterType", jdbcType=JdbcType.VARCHAR),
        @Result(column="parameter_value", property="parameterValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    JobLogJobExecParams selectByPrimaryKey(@Param("jobLogId") String jobLogId, @Param("parameterName") String parameterName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log_job_exec_params
     *
     * @mbg.generated Wed Dec 13 11:06:11 CET 2023
     */
    @Select({
        "select",
        "job_log_id, parameter_name, parameter_description, parameter_type, parameter_value, ",
        "last_modified_by_user_login, created_by_user_login, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp",
        "from job_log_job_exec_params"
    })
    @Results({
        @Result(column="job_log_id", property="jobLogId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parameter_name", property="parameterName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parameter_description", property="parameterDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="parameter_type", property="parameterType", jdbcType=JdbcType.VARCHAR),
        @Result(column="parameter_value", property="parameterValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<JobLogJobExecParams> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log_job_exec_params
     *
     * @mbg.generated Wed Dec 13 11:06:11 CET 2023
     */
    @Update({
        "update job_log_job_exec_params",
        "set parameter_description = #{parameterDescription,jdbcType=VARCHAR},",
          "parameter_type = #{parameterType,jdbcType=VARCHAR},",
          "parameter_value = #{parameterValue,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where job_log_id = #{jobLogId,jdbcType=VARCHAR}",
          "and parameter_name = #{parameterName,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(JobLogJobExecParams row);


    @Select({
            "select",
            "job_log_id, parameter_name, parameter_description, parameter_type, parameter_value, ",
            "last_modified_by_user_login, created_by_user_login, last_updated_stamp, last_updated_tx_stamp, ",
            "created_stamp, created_tx_stamp",
            "from job_log_job_exec_params",
            "where job_log_id = #{jobLogId,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="job_log_id", property="jobLogId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="parameter_name", property="parameterName", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="parameter_description", property="parameterDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="parameter_type", property="parameterType", jdbcType=JdbcType.VARCHAR),
            @Result(column="parameter_value", property="parameterValue", jdbcType=JdbcType.VARCHAR),
            @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<JobLogJobExecParams> selectByJobLogId(@Param("jobLogId") String jobLogId);
}