package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.*;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PartyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_role
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Delete({
        "delete from party_role",
        "where party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_role
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Insert({
        "insert into party_role (party_id, role_type_id, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "parent_role_type_id, last_modified_by_user_login, ",
        "created_by_user_login)",
        "values (#{partyId,jdbcType=VARCHAR}, #{roleTypeId,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{parentRoleTypeId,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(PartyRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_role
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Select({
        "select",
        "party_id, role_type_id, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, parent_role_type_id, last_modified_by_user_login, created_by_user_login",
        "from party_role",
        "where party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    @Results(id = "partyRoleMap", value = {
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="parent_role_type_id", property="parentRoleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    PartyRole selectByPrimaryKey(@Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_role
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Select({
        "select",
        "party_id, role_type_id, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, parent_role_type_id, last_modified_by_user_login, created_by_user_login",
        "from party_role"
    })
    @Results( id = "partyRoleResultMap", value = {
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="parent_role_type_id", property="parentRoleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<PartyRole> selectAll();

    List<PartyRole> getPartyRole(
            boolean isSecondaryLang,
            String search,
            String matchModeSearch,
            String[] roleTypeId
    );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_role
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Update({
        "update party_role",
        "set last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "parent_role_type_id = #{parentRoleTypeId,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR}",
        "where party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PartyRole row);

    List<PartyRoleEx> getPartyRoleOrgUnit(@Param("userPreferenceOrganizationUnitId") String userPreferenceOrganizationUnitId);

    List<PartyRoleEx> getPartyRoleExOrgUnit(@Param("userPreferenceOrganizationUnitId") String userPreferenceOrganizationUnitId, @Param("userLoginId") String userLoginId, @Param("accountTypeEnumId") String accountTypeEnumId);
}