package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.PartyRelationship;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PartyRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_relationship
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Delete({
        "delete from party_relationship",
        "where party_id_from = #{partyIdFrom,jdbcType=VARCHAR}",
          "and party_id_to = #{partyIdTo,jdbcType=VARCHAR}",
          "and role_type_id_from = #{roleTypeIdFrom,jdbcType=VARCHAR}",
          "and role_type_id_to = #{roleTypeIdTo,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}",
          "and party_relationship_type_id = #{partyRelationshipTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("partyIdFrom") String partyIdFrom, @Param("partyIdTo") String partyIdTo, @Param("roleTypeIdFrom") String roleTypeIdFrom, @Param("roleTypeIdTo") String roleTypeIdTo, @Param("fromDate") LocalDateTime fromDate, @Param("partyRelationshipTypeId") String partyRelationshipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_relationship
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Insert({
        "insert into party_relationship (party_id_from, party_id_to, ",
        "role_type_id_from, role_type_id_to, ",
        "from_date, party_relationship_type_id, ",
        "thru_date, status_id, ",
        "relationship_name, security_group_id, ",
        "priority_type_id, permissions_enum_id, ",
        "position_title, comments, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "value_uom_id, relationship_value, ",
        "last_modified_by_user_login, created_by_user_login, ",
        "ctx_enabled)",
        "values (#{partyIdFrom,jdbcType=VARCHAR}, #{partyIdTo,jdbcType=VARCHAR}, ",
        "#{roleTypeIdFrom,jdbcType=VARCHAR}, #{roleTypeIdTo,jdbcType=VARCHAR}, ",
        "#{fromDate,jdbcType=TIMESTAMP}, #{partyRelationshipTypeId,jdbcType=VARCHAR}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{statusId,jdbcType=VARCHAR}, ",
        "#{relationshipName,jdbcType=VARCHAR}, #{securityGroupId,jdbcType=VARCHAR}, ",
        "#{priorityTypeId,jdbcType=VARCHAR}, #{permissionsEnumId,jdbcType=VARCHAR}, ",
        "#{positionTitle,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{valueUomId,jdbcType=VARCHAR}, #{relationshipValue,jdbcType=DOUBLE}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR}, ",
        "#{ctxEnabled,jdbcType=VARCHAR})"
    })
    int insert(PartyRelationship row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_relationship
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Select({
        "select",
        "party_id_from, party_id_to, role_type_id_from, role_type_id_to, from_date, party_relationship_type_id, ",
        "thru_date, status_id, relationship_name, security_group_id, priority_type_id, ",
        "permissions_enum_id, position_title, comments, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, value_uom_id, relationship_value, last_modified_by_user_login, ",
        "created_by_user_login, ctx_enabled",
        "from party_relationship",
        "where party_id_from = #{partyIdFrom,jdbcType=VARCHAR}",
          "and party_id_to = #{partyIdTo,jdbcType=VARCHAR}",
          "and role_type_id_from = #{roleTypeIdFrom,jdbcType=VARCHAR}",
          "and role_type_id_to = #{roleTypeIdTo,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}",
          "and party_relationship_type_id = #{partyRelationshipTypeId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="party_id_from", property="partyIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id_to", property="partyIdTo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id_from", property="roleTypeIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id_to", property="roleTypeIdTo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="party_relationship_type_id", property="partyRelationshipTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="relationship_name", property="relationshipName", jdbcType=JdbcType.VARCHAR),
        @Result(column="security_group_id", property="securityGroupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority_type_id", property="priorityTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="permissions_enum_id", property="permissionsEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_title", property="positionTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="value_uom_id", property="valueUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="relationship_value", property="relationshipValue", jdbcType=JdbcType.DOUBLE),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="ctx_enabled", property="ctxEnabled", jdbcType=JdbcType.VARCHAR)
    })
    PartyRelationship selectByPrimaryKey(@Param("partyIdFrom") String partyIdFrom, @Param("partyIdTo") String partyIdTo, @Param("roleTypeIdFrom") String roleTypeIdFrom, @Param("roleTypeIdTo") String roleTypeIdTo, @Param("fromDate") LocalDateTime fromDate, @Param("partyRelationshipTypeId") String partyRelationshipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_relationship
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Select({
        "select",
        "party_id_from, party_id_to, role_type_id_from, role_type_id_to, from_date, party_relationship_type_id, ",
        "thru_date, status_id, relationship_name, security_group_id, priority_type_id, ",
        "permissions_enum_id, position_title, comments, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, value_uom_id, relationship_value, last_modified_by_user_login, ",
        "created_by_user_login, ctx_enabled",
        "from party_relationship"
    })
    @Results({
        @Result(column="party_id_from", property="partyIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id_to", property="partyIdTo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id_from", property="roleTypeIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id_to", property="roleTypeIdTo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="party_relationship_type_id", property="partyRelationshipTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="relationship_name", property="relationshipName", jdbcType=JdbcType.VARCHAR),
        @Result(column="security_group_id", property="securityGroupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority_type_id", property="priorityTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="permissions_enum_id", property="permissionsEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_title", property="positionTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="value_uom_id", property="valueUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="relationship_value", property="relationshipValue", jdbcType=JdbcType.DOUBLE),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="ctx_enabled", property="ctxEnabled", jdbcType=JdbcType.VARCHAR)
    })
    List<PartyRelationship> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_relationship
     *
     * @mbg.generated Wed Nov 22 12:31:08 CET 2023
     */
    @Update({
        "update party_relationship",
        "set thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "status_id = #{statusId,jdbcType=VARCHAR},",
          "relationship_name = #{relationshipName,jdbcType=VARCHAR},",
          "security_group_id = #{securityGroupId,jdbcType=VARCHAR},",
          "priority_type_id = #{priorityTypeId,jdbcType=VARCHAR},",
          "permissions_enum_id = #{permissionsEnumId,jdbcType=VARCHAR},",
          "position_title = #{positionTitle,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "value_uom_id = #{valueUomId,jdbcType=VARCHAR},",
          "relationship_value = #{relationshipValue,jdbcType=DOUBLE},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR},",
          "ctx_enabled = #{ctxEnabled,jdbcType=VARCHAR}",
        "where party_id_from = #{partyIdFrom,jdbcType=VARCHAR}",
          "and party_id_to = #{partyIdTo,jdbcType=VARCHAR}",
          "and role_type_id_from = #{roleTypeIdFrom,jdbcType=VARCHAR}",
          "and role_type_id_to = #{roleTypeIdTo,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}",
          "and party_relationship_type_id = #{partyRelationshipTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PartyRelationship row);
}