package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.PartyHistoryView;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PartyHistoryViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_history_view
     *
     * @mbg.generated Fri Oct 13 09:50:12 CEST 2023
     */
    @Insert({
        "insert into party_history_view (party_id, from_date, ",
        "thru_date, employment_amount, ",
        "empl_position_type_id, description, ",
        "comments)",
        "values (#{partyId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{employmentAmount,jdbcType=NUMERIC}, ",
        "#{emplPositionTypeId,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{comments,jdbcType=VARCHAR})"
    })
    int insert(PartyHistoryView row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_history_view
     *
     * @mbg.generated Fri Oct 13 09:50:12 CEST 2023
     */
    @Select({
        "select",
        "party_id, from_date, thru_date, employment_amount, empl_position_type_id, description, ",
        "comments",
        "from party_history_view"
    })
    @Results(id = "partyHistoryViewResultMap" , value = {
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="employment_amount", property="employmentAmount", jdbcType=JdbcType.NUMERIC),
        @Result(column="empl_position_type_id", property="emplPositionTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR)
    })
    List<PartyHistoryView> selectAll();
}