package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.PartyParentRole;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PartyParentRoleMapper {

    @Delete({
        "delete from party_parent_role",
        "where party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId);


    @Insert({
        "insert into party_parent_role (party_id, role_type_id, ",
        "parent_role_code, organization_id, ",
        "last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{partyId,jdbcType=VARCHAR}, #{roleTypeId,jdbcType=VARCHAR}, ",
        "#{parentRoleCode,jdbcType=VARCHAR}, #{organizationId,jdbcType=VARCHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(PartyParentRole row);


    @Select({
        "select",
        "party_id, role_type_id, parent_role_code, organization_id, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from party_parent_role",
        "where party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    @Results( id = "partyParentRoleMap", value = {
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_role_code", property="parentRoleCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_id", property="organizationId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    PartyParentRole selectByPrimaryKey(@Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId);


    @Select({
        "select",
        "party_id, role_type_id, parent_role_code, organization_id, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from party_parent_role"
    })
    @Results({
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_role_code", property="parentRoleCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_id", property="organizationId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PartyParentRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_parent_role
     *
     * @mbg.generated Tue Oct 17 16:07:23 CEST 2023
     */
    @Update({
        "update party_parent_role",
        "set parent_role_code = #{parentRoleCode,jdbcType=VARCHAR},",
          "organization_id = #{organizationId,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP}",
        "where party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PartyParentRole row);
}