package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.RateType;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RateTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_type
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    @Delete({
        "delete from rate_type",
        "where rate_type_id = #{rateTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String rateTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_type
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    @Insert({
        "insert into rate_type (rate_type_id, description, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "description_lang)",
        "values (#{rateTypeId,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{descriptionLang,jdbcType=VARCHAR})"
    })
    int insert(RateType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_type
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    @Select({
        "select",
        "rate_type_id, description, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, description_lang",
        "from rate_type",
        "where rate_type_id = #{rateTypeId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="rate_type_id", property="rateTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR)
    })
    RateType selectByPrimaryKey(String rateTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_type
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    @Select({
        "select",
        "rate_type_id, description, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, description_lang",
        "from rate_type"
    })
    @Results( id = "rateTypeResultMap", value ={
        @Result(column="rate_type_id", property="rateTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR)
    })
    List<RateType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_type
     *
     * @mbg.generated Tue Oct 24 14:08:42 CEST 2023
     */
    @Update({
        "update rate_type",
        "set description = #{description,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "description_lang = #{descriptionLang,jdbcType=VARCHAR}",
        "where rate_type_id = #{rateTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RateType row);

}