package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.SecurityGroupPermission;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface SecurityGroupPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_group_permission
     *
     * @mbg.generated Tue Nov 28 14:57:05 CET 2023
     */
    @Delete({
        "delete from security_group_permission",
        "where group_id = #{groupId,jdbcType=VARCHAR}",
          "and permission_id = #{permissionId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("groupId") String groupId, @Param("permissionId") String permissionId);

    @Delete({
            "delete from security_group_permission",
            "where group_id = #{groupId,jdbcType=VARCHAR}"
    })
    int deleteByGroupId(@Param("groupId") String groupId);


    @Insert({
        "insert into security_group_permission (group_id, permission_id, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{groupId,jdbcType=VARCHAR}, #{permissionId,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(SecurityGroupPermission row);


    @Select({
        "select",
        "group_id, permission_id, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from security_group_permission",
        "where group_id = #{groupId,jdbcType=VARCHAR}",
          "and permission_id = #{permissionId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    SecurityGroupPermission selectByPrimaryKey(@Param("groupId") String groupId, @Param("permissionId") String permissionId);


    @Select({
        "select",
        "group_id, permission_id, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from security_group_permission",
            "where group_id = #{groupId,jdbcType=VARCHAR}",
            "order by group_id, permission_id"
    })
    @ResultType(SecurityGroupPermission.class)
    List<SecurityGroupPermission> selectByGroupIdOrderByPrimaryKey(@Param("groupId") String groupId);


    @Update({
        "update security_group_permission",
        "set last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where group_id = #{groupId,jdbcType=VARCHAR}",
          "and permission_id = #{permissionId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SecurityGroupPermission row);
}