package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.SecurityPermission;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface SecurityPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_permission
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    @Delete({
        "delete from security_permission",
        "where permission_id = #{permissionId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_permission
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    @Insert({
        "insert into security_permission (permission_id, description, ",
        "dynamic_access, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, enabled, ",
        "last_modified_by_user_login, created_by_user_login)",
        "values (#{permissionId,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{dynamicAccess,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP}, #{enabled,jdbcType=CHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(SecurityPermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_permission
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    @Select({
        "select",
        "permission_id, description, dynamic_access, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, enabled, last_modified_by_user_login, created_by_user_login",
        "from security_permission",
        "where permission_id = #{permissionId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="dynamic_access", property="dynamicAccess", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.CHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    SecurityPermission selectByPrimaryKey(String permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_permission
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    @Select({
        "select",
        "permission_id, description, dynamic_access, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, enabled, last_modified_by_user_login, created_by_user_login",
        "from security_permission"
    })
    @Results( id="securityPermissionResultMap", value = {
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="dynamic_access", property="dynamicAccess", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.CHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<SecurityPermission> selectAll();

    @Select({
            "select *",
            "from security_permission",
            "where enabled = #{enabled,jdbcType=VARCHAR}",
            "order by permission_id"
    })
    @ResultType(SecurityPermission.class)
    List<SecurityPermission> selectByEnabledOrderByPrimaryKey(String enabled);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_permission
     *
     * @mbg.generated Thu Nov 30 12:32:47 CET 2023
     */
    @Update({
        "update security_permission",
        "set description = #{description,jdbcType=VARCHAR},",
          "dynamic_access = #{dynamicAccess,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "enabled = #{enabled,jdbcType=CHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR}",
        "where permission_id = #{permissionId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SecurityPermission row);

    List<SecurityPermission> getPermission(@Param("userLoginId") String userLoginId);
}