package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.StandardImportFieldConfig;
import it.mapsgroup.gzoom.mybatis.dto.StandardImportFieldConfigEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.math.BigDecimal;
import java.util.List;

public interface StandardImportFieldConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_import_field_config
     *
     * @mbg.generated Thu Dec 07 10:09:28 CET 2023
     */
    @Delete({
        "delete from standard_import_field_config",
        "where data_source_id = #{dataSourceId,jdbcType=VARCHAR}",
          "and standard_interface = #{standardInterface,jdbcType=VARCHAR}",
          "and internal_field_name = #{internalFieldName,jdbcType=VARCHAR}",
          "and interface_seq = #{interfaceSeq,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(@Param("dataSourceId") String dataSourceId, @Param("standardInterface") String standardInterface, @Param("internalFieldName") String internalFieldName, @Param("interfaceSeq") BigDecimal interfaceSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_import_field_config
     *
     * @mbg.generated Thu Dec 07 10:09:28 CET 2023
     */
    @Insert({
        "insert into standard_import_field_config (data_source_id, standard_interface, ",
        "internal_field_name, interface_seq, ",
        "external_field_name, default_value, ",
        "last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{dataSourceId,jdbcType=VARCHAR}, #{standardInterface,jdbcType=VARCHAR}, ",
        "#{internalFieldName,jdbcType=VARCHAR}, #{interfaceSeq,jdbcType=NUMERIC}, ",
        "#{externalFieldName,jdbcType=VARCHAR}, #{defaultValue,jdbcType=VARCHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(StandardImportFieldConfig row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_import_field_config
     *
     * @mbg.generated Thu Dec 07 10:09:28 CET 2023
     */
    @Select({
        "select",
        "data_source_id, standard_interface, internal_field_name, interface_seq, external_field_name, ",
        "default_value, last_modified_by_user_login, created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from standard_import_field_config",
        "where data_source_id = #{dataSourceId,jdbcType=VARCHAR}",
          "and standard_interface = #{standardInterface,jdbcType=VARCHAR}",
          "and internal_field_name = #{internalFieldName,jdbcType=VARCHAR}",
          "and interface_seq = #{interfaceSeq,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="data_source_id", property="dataSourceId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="standard_interface", property="standardInterface", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="internal_field_name", property="internalFieldName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="interface_seq", property="interfaceSeq", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="external_field_name", property="externalFieldName", jdbcType=JdbcType.VARCHAR),
        @Result(column="default_value", property="defaultValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    StandardImportFieldConfig selectByPrimaryKey(@Param("dataSourceId") String dataSourceId, @Param("standardInterface") String standardInterface, @Param("internalFieldName") String internalFieldName, @Param("interfaceSeq") BigDecimal interfaceSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_import_field_config
     *
     * @mbg.generated Thu Dec 07 10:09:28 CET 2023
     */
    @Select({
        "select",
        "data_source_id, standard_interface, internal_field_name, interface_seq, external_field_name, ",
        "default_value, last_modified_by_user_login, created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from standard_import_field_config"
    })
    @Results(id="standardImportFieldConfigResultMap", value = {
        @Result(column="data_source_id", property="dataSourceId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="standard_interface", property="standardInterface", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="internal_field_name", property="internalFieldName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="interface_seq", property="interfaceSeq", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="external_field_name", property="externalFieldName", jdbcType=JdbcType.VARCHAR),
        @Result(column="default_value", property="defaultValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<StandardImportFieldConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_import_field_config
     *
     * @mbg.generated Thu Dec 07 10:09:28 CET 2023
     */
    @Update({
        "update standard_import_field_config",
        "set external_field_name = #{externalFieldName,jdbcType=VARCHAR},",
          "default_value = #{defaultValue,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where data_source_id = #{dataSourceId,jdbcType=VARCHAR}",
          "and standard_interface = #{standardInterface,jdbcType=VARCHAR}",
          "and internal_field_name = #{internalFieldName,jdbcType=VARCHAR}",
          "and interface_seq = #{interfaceSeq,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(StandardImportFieldConfig row);

    List<StandardImportFieldConfigEx> getStandardImportFieldConfigEx(@Param("dataSourceId") String dataSourceId);
}