package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.TimeEntry;
import it.mapsgroup.gzoom.mybatis.dto.TimeEntryEx;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffort;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface TimeEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_entry
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    @Delete({
        "delete from time_entry",
        "where time_entry_id = #{timeEntryId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String timeEntryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_entry
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    @Insert({
        "insert into time_entry (time_entry_id, party_id, ",
        "from_date, thru_date, ",
        "rate_type_id, work_effort_id, ",
        "timesheet_id, invoice_id, ",
        "invoice_item_seq_id, hours, ",
        "comments, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, effort_uom_id, ",
        "percentage, last_modified_by_user_login, ",
        "created_by_user_login, job_id, ",
        "order_id, plan_hours)",
        "values (#{timeEntryId,jdbcType=VARCHAR}, #{partyId,jdbcType=VARCHAR}, ",
        "#{fromDate,jdbcType=TIMESTAMP}, #{thruDate,jdbcType=TIMESTAMP}, ",
        "#{rateTypeId,jdbcType=VARCHAR}, #{workEffortId,jdbcType=VARCHAR}, ",
        "#{timesheetId,jdbcType=VARCHAR}, #{invoiceId,jdbcType=VARCHAR}, ",
        "#{invoiceItemSeqId,jdbcType=VARCHAR}, #{hours,jdbcType=DOUBLE}, ",
        "#{comments,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP}, #{effortUomId,jdbcType=VARCHAR}, ",
        "#{percentage,jdbcType=DOUBLE}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{jobId,jdbcType=VARCHAR}, ",
        "#{orderId,jdbcType=VARCHAR}, #{planHours,jdbcType=DOUBLE})"
    })
    int insert(TimeEntry row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_entry
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    @Select({
        "select",
        "time_entry_id, party_id, from_date, thru_date, rate_type_id, work_effort_id, ",
        "timesheet_id, invoice_id, invoice_item_seq_id, hours, comments, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp, effort_uom_id, percentage, ",
        "last_modified_by_user_login, created_by_user_login, job_id, order_id, plan_hours",
        "from time_entry",
        "where time_entry_id = #{timeEntryId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="time_entry_id", property="timeEntryId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="rate_type_id", property="rateTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="timesheet_id", property="timesheetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_id", property="invoiceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_item_seq_id", property="invoiceItemSeqId", jdbcType=JdbcType.VARCHAR),
        @Result(column="hours", property="hours", jdbcType=JdbcType.DOUBLE),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="percentage", property="percentage", jdbcType=JdbcType.DOUBLE),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="job_id", property="jobId", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="plan_hours", property="planHours", jdbcType=JdbcType.DOUBLE)
    })
    TimeEntry selectByPrimaryKey(String timeEntryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_entry
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    @Select({
        "select",
        "time_entry_id, party_id, from_date, thru_date, rate_type_id, work_effort_id, ",
        "timesheet_id, invoice_id, invoice_item_seq_id, hours, comments, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp, effort_uom_id, percentage, ",
        "last_modified_by_user_login, created_by_user_login, job_id, order_id, plan_hours",
        "from time_entry"
    })
    @Results({
        @Result(column="time_entry_id", property="timeEntryId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="rate_type_id", property="rateTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="timesheet_id", property="timesheetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_id", property="invoiceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_item_seq_id", property="invoiceItemSeqId", jdbcType=JdbcType.VARCHAR),
        @Result(column="hours", property="hours", jdbcType=JdbcType.DOUBLE),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="percentage", property="percentage", jdbcType=JdbcType.DOUBLE),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="job_id", property="jobId", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="plan_hours", property="planHours", jdbcType=JdbcType.DOUBLE)
    })
    List<TimeEntry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_entry
     *
     * @mbg.generated Fri Oct 20 10:57:00 CEST 2023
     */
    @Update({
        "update time_entry",
        "set party_id = #{partyId,jdbcType=VARCHAR},",
          "from_date = #{fromDate,jdbcType=TIMESTAMP},",
          "thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "rate_type_id = #{rateTypeId,jdbcType=VARCHAR},",
          "work_effort_id = #{workEffortId,jdbcType=VARCHAR},",
          "timesheet_id = #{timesheetId,jdbcType=VARCHAR},",
          "invoice_id = #{invoiceId,jdbcType=VARCHAR},",
          "invoice_item_seq_id = #{invoiceItemSeqId,jdbcType=VARCHAR},",
          "hours = #{hours,jdbcType=DOUBLE},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "effort_uom_id = #{effortUomId,jdbcType=VARCHAR},",
          "percentage = #{percentage,jdbcType=DOUBLE},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "job_id = #{jobId,jdbcType=VARCHAR},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "plan_hours = #{planHours,jdbcType=DOUBLE}",
        "where time_entry_id = #{timeEntryId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TimeEntry row);

    List<TimeEntryEx> getTimeEntryEx(@Param("timesheetId") String timesheetId);

    List<WorkEffort> getWorkEffort(@Param("timesheetId") String timesheetId, @Param("secondaryLang") boolean secondaryLang);


}