package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.commons.Filter;
import it.mapsgroup.gzoom.mybatis.dto.Timesheet;
import it.mapsgroup.gzoom.mybatis.dto.TimesheetEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface TimesheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated Wed Oct 11 11:07:22 CEST 2023
     */
    @Delete({
        "delete from timesheet",
        "where timesheet_id = #{timesheetId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String timesheetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated Wed Oct 11 11:07:22 CEST 2023
     */
    @Insert({
        "insert into timesheet (timesheet_id, party_id, ",
        "client_party_id, from_date, ",
        "thru_date, status_id, ",
        "approved_by_user_login_id, comments, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "transfer_flag, contract_hours, ",
        "actual_hours, work_effort_type_period_id, ",
        "effort_uom_id, work_effort_id)",
        "values (#{timesheetId,jdbcType=VARCHAR}, #{partyId,jdbcType=VARCHAR}, ",
        "#{clientPartyId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{statusId,jdbcType=VARCHAR}, ",
        "#{approvedByUserLoginId,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{transferFlag,jdbcType=CHAR}, #{contractHours,jdbcType=DOUBLE}, ",
        "#{actualHours,jdbcType=DOUBLE}, #{workEffortTypePeriodId,jdbcType=VARCHAR}, ",
        "#{effortUomId,jdbcType=VARCHAR}, #{workEffortId,jdbcType=VARCHAR})"
    })
    int insert(Timesheet row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated Wed Oct 11 11:07:22 CEST 2023
     */
    @Select({
        "select",
        "timesheet_id, party_id, client_party_id, from_date, thru_date, status_id, approved_by_user_login_id, ",
        "comments, last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp, ",
        "transfer_flag, contract_hours, actual_hours, work_effort_type_period_id, effort_uom_id, ",
        "work_effort_id",
        "from timesheet",
        "where timesheet_id = #{timesheetId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="timesheet_id", property="timesheetId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_party_id", property="clientPartyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="approved_by_user_login_id", property="approvedByUserLoginId", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="transfer_flag", property="transferFlag", jdbcType=JdbcType.CHAR),
        @Result(column="contract_hours", property="contractHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="actual_hours", property="actualHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="work_effort_type_period_id", property="workEffortTypePeriodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR)
    })
    Timesheet selectByPrimaryKey(String timesheetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated Wed Oct 11 11:07:22 CEST 2023
     */
    @Select({
        "select",
        "timesheet_id, party_id, client_party_id, from_date, thru_date, status_id, approved_by_user_login_id, ",
        "comments, last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp, ",
        "transfer_flag, contract_hours, actual_hours, work_effort_type_period_id, effort_uom_id, ",
        "work_effort_id",
        "from timesheet"
    })
    @Results({
        @Result(column="timesheet_id", property="timesheetId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_party_id", property="clientPartyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="approved_by_user_login_id", property="approvedByUserLoginId", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="transfer_flag", property="transferFlag", jdbcType=JdbcType.CHAR),
        @Result(column="contract_hours", property="contractHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="actual_hours", property="actualHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="work_effort_type_period_id", property="workEffortTypePeriodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR)
    })
    List<Timesheet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timesheet
     *
     * @mbg.generated Wed Oct 11 11:07:22 CEST 2023
     */
    @Update({
        "update timesheet",
        "set party_id = #{partyId,jdbcType=VARCHAR},",
          "client_party_id = #{clientPartyId,jdbcType=VARCHAR},",
          "status_id = #{statusId,jdbcType=VARCHAR},",
          "approved_by_user_login_id = #{approvedByUserLoginId,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "transfer_flag = #{transferFlag,jdbcType=CHAR},",
          "contract_hours = #{contractHours,jdbcType=DOUBLE},",
          "actual_hours = #{actualHours,jdbcType=DOUBLE},",
          "work_effort_type_period_id = #{workEffortTypePeriodId,jdbcType=VARCHAR},",
          "effort_uom_id = #{effortUomId,jdbcType=VARCHAR},",
          "work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
        "where timesheet_id = #{timesheetId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Timesheet row);

    List<TimesheetEx> getTimesheetExs(@Param("userLoginId") String userLoginId);

    TimesheetEx getTimesheetExsById( @Param("timesheetId") String timesheetId, @Param("userLoginId") String userLoginId);

    List<TimesheetEx> findTimesheetsPagination(@Param("userLoginId") String userLoginId, @Param("LIMIT") Integer limit, @Param("OFFSET") Integer offset, @Param("filters") Filter[] filters, @Param("SORTORDER") Integer sortOrder, @Param("SORTFIELD") String sortField, @Param("SECONDARYLANGUAGE") Boolean secondaryLanguage);
}