package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.TsByUserLogin;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TsByUserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    @Insert({
        "insert into ts_by_user_login (timesheet_id, user_login_id, ",
        "party_id_pe, work_effort_id, ",
        "work_effort_type_period_id, party_id_uo, ",
        "updateable, from_date, ",
        "thru_date, status_id, ",
        "contract_hours, actual_hours, ",
        "effort_uom_id, role_type)",
        "values (#{timesheetId,jdbcType=VARCHAR}, #{userLoginId,jdbcType=VARCHAR}, ",
        "#{partyIdPe,jdbcType=VARCHAR}, #{workEffortId,jdbcType=VARCHAR}, ",
        "#{workEffortTypePeriodId,jdbcType=VARCHAR}, #{partyIdUo,jdbcType=VARCHAR}, ",
        "#{updateable,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{statusId,jdbcType=VARCHAR}, ",
        "#{contractHours,jdbcType=DOUBLE}, #{actualHours,jdbcType=DOUBLE}, ",
        "#{effortUomId,jdbcType=VARCHAR}, #{roleType,jdbcType=VARCHAR})"
    })
    int insert(TsByUserLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_by_user_login
     *
     * @mbg.generated Tue Oct 17 16:07:01 CEST 2023
     */
    @Select({
        "select",
        "timesheet_id, user_login_id, party_id_pe, work_effort_id, work_effort_type_period_id, ",
        "party_id_uo, updateable, from_date, thru_date, status_id, contract_hours, actual_hours, ",
        "effort_uom_id, role_type",
        "from ts_by_user_login"
    })
    @Results( id = "tsByUserLoginResultMap" , value = {
        @Result(column="timesheet_id", property="timesheetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_login_id", property="userLoginId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_pe", property="partyIdPe", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_type_period_id", property="workEffortTypePeriodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_uo", property="partyIdUo", jdbcType=JdbcType.VARCHAR),
        @Result(column="updateable", property="updateable", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract_hours", property="contractHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="actual_hours", property="actualHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type", property="roleType", jdbcType=JdbcType.VARCHAR)
    })
    List<TsByUserLogin> selectAll();
}