package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.TsHolidaysDates;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface TsHolidaysDatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_holidays_dates
     *
     * @mbg.generated Thu Nov 30 09:53:59 CET 2023
     */
    @Insert({
        "insert into ts_holidays_dates (timesheet_id, holiday_date)",
        "values (#{timesheetId,jdbcType=VARCHAR}, #{holidayDate,jdbcType=TIMESTAMP})"
    })
    int insert(TsHolidaysDates row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_holidays_dates
     *
     * @mbg.generated Thu Nov 30 09:53:59 CET 2023
     */
    @Select({
        "select",
        "timesheet_id, holiday_date",
        "from ts_holidays_dates"
    })
    @Results( id="tsHolidaysDatesResultMap", value = {
        @Result(column="timesheet_id", property="timesheetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="holiday_date", property="holidayDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TsHolidaysDates> selectAll();

    List<TsHolidaysDates> getTsHolidayDatesByTimesheetId(@Param("timesheetId") String timesheetId);
}