package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.UomRatingScale;
import it.mapsgroup.gzoom.mybatis.dto.UomRatingScaleEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;

@Mapper
@Repository
public interface UomRatingScaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_rating_scale
     *
     * @mbg.generated Mon Nov 13 10:11:47 CET 2023
     */
    @Delete({
        "delete from uom_rating_scale",
        "where uom_id = #{uomId,jdbcType=VARCHAR}",
          "and uom_rating_value = #{uomRatingValue,jdbcType=DOUBLE}"
    })
    int deleteByPrimaryKey(@Param("uomId") String uomId, @Param("uomRatingValue") Double uomRatingValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_rating_scale
     *
     * @mbg.generated Mon Nov 13 10:11:47 CET 2023
     */
    @Insert({
        "insert into uom_rating_scale (uom_id, uom_rating_value, ",
        "description, icon_content_id, ",
        "description_lang, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp)",
        "values (#{uomId,jdbcType=VARCHAR}, #{uomRatingValue,jdbcType=DOUBLE}, ",
        "#{description,jdbcType=VARCHAR}, #{iconContentId,jdbcType=VARCHAR}, ",
        "#{descriptionLang,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(UomRatingScale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_rating_scale
     *
     * @mbg.generated Mon Nov 13 10:11:47 CET 2023
     */
    @Select({
        "select",
        "uom_id, uom_rating_value, description, icon_content_id, description_lang, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from uom_rating_scale",
        "where uom_id = #{uomId,jdbcType=VARCHAR}",
          "and uom_rating_value = #{uomRatingValue,jdbcType=DOUBLE}"
    })
    @Results({
        @Result(column="uom_id", property="uomId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uom_rating_value", property="uomRatingValue", jdbcType=JdbcType.DOUBLE, id=true),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon_content_id", property="iconContentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    UomRatingScale selectByPrimaryKey(@Param("uomId") String uomId, @Param("uomRatingValue") Double uomRatingValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_rating_scale
     *
     * @mbg.generated Mon Nov 13 10:11:47 CET 2023
     */
    @Select({
        "select",
        "uom_id, uom_rating_value, description, icon_content_id, description_lang, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from uom_rating_scale"
    })
    @Results(id = "uomRatingScaleResultMap", value = {
        @Result(column="uom_id", property="uomId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uom_rating_value", property="uomRatingValue", jdbcType=JdbcType.DOUBLE, id=true),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon_content_id", property="iconContentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UomRatingScale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_rating_scale
     *
     * @mbg.generated Mon Nov 13 10:11:47 CET 2023
     */
    @Update({
        "update uom_rating_scale",
        "set description = #{description,jdbcType=VARCHAR},",
          "icon_content_id = #{iconContentId,jdbcType=VARCHAR},",
          "description_lang = #{descriptionLang,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where uom_id = #{uomId,jdbcType=VARCHAR}",
          "and uom_rating_value = #{uomRatingValue,jdbcType=DOUBLE}"
    })
    int updateByPrimaryKey(UomRatingScale row);

    List<UomRatingScaleEx> getUomRatingScalesEx(@Param("uomId") String uomId);

    UomRatingScaleEx getUomRatingScaleEx(@Param("uomId") String uomId, @Param("uomRatingValue") BigDecimal uomRatingValue);

    List<UomRatingScale> getUomRatingScales(@Param("uomId") String uomId);

    @Select({
            "select urs.*",
            "from uom_rating_scale urs",
            "join gl_account ga on ga.default_uom_id = urs.uom_id",
            "where ga.gl_account_id = #{glAccountId}"
    })
    @ResultType(UomRatingScale.class)
    List<UomRatingScale> selectByGlAccountId(String glAccountId);

    @Select({
            "select urs.* from uom_rating_scale urs",
            "join gl_account_meas_rat_sc gamrs on gamrs.uom_rating_value  = urs.uom_rating_value",
            "and gamrs.uom_id = urs.uom_id",
            "where gamrs.gl_account_id = #{glAccountId}"
    })
    @ResultType(UomRatingScale.class)
    List<UomRatingScale> selectByGlAccountIdOnGlAccountMeasRatSc(String glAccountId);

    List<UomRatingScale> getUomRatingScalesExcludingGlAccount(String glAccountId);
}