package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.UomType;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_type
     *
     * @mbg.generated Thu Nov 16 11:55:31 CET 2023
     */
    @Delete({
        "delete from uom_type",
        "where uom_type_id = #{uomTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uomTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_type
     *
     * @mbg.generated Thu Nov 16 11:55:31 CET 2023
     */
    @Insert({
        "insert into uom_type (uom_type_id, parent_type_id, ",
        "has_table, description, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "is_reserved, last_modified_by_user_login, ",
        "created_by_user_login)",
        "values (#{uomTypeId,jdbcType=VARCHAR}, #{parentTypeId,jdbcType=VARCHAR}, ",
        "#{hasTable,jdbcType=CHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{isReserved,jdbcType=CHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(UomType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_type
     *
     * @mbg.generated Thu Nov 16 11:55:31 CET 2023
     */
    @Select({
        "select",
        "uom_type_id, parent_type_id, has_table, description, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, is_reserved, last_modified_by_user_login, created_by_user_login",
        "from uom_type",
        "where uom_type_id = #{uomTypeId,jdbcType=VARCHAR}"
    })
    @Results(id = "uomType", value = {
        @Result(column="uom_type_id", property="uomTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_type_id", property="parentTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_table", property="hasTable", jdbcType=JdbcType.CHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_reserved", property="isReserved", jdbcType=JdbcType.CHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    UomType selectByPrimaryKey(String uomTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_type
     *
     * @mbg.generated Thu Nov 16 11:55:31 CET 2023
     */
    @Select({
        "select",
        "uom_type_id, parent_type_id, has_table, description, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, is_reserved, last_modified_by_user_login, created_by_user_login",
        "from uom_type"
    })
    @Results({
        @Result(column="uom_type_id", property="uomTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_type_id", property="parentTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_table", property="hasTable", jdbcType=JdbcType.CHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_reserved", property="isReserved", jdbcType=JdbcType.CHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<UomType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uom_type
     *
     * @mbg.generated Thu Nov 16 11:55:31 CET 2023
     */
    @Update({
        "update uom_type",
        "set parent_type_id = #{parentTypeId,jdbcType=VARCHAR},",
          "has_table = #{hasTable,jdbcType=CHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "is_reserved = #{isReserved,jdbcType=CHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR}",
        "where uom_type_id = #{uomTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UomType row);
}