package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.UserLoginValidPartyRole;
import it.mapsgroup.gzoom.mybatis.dto.UserLoginValidPartyRoleEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UserLoginValidPartyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_valid_party_role
     *
     * @mbg.generated Thu Nov 23 12:53:58 CET 2023
     */
    @Delete({
        "delete from user_login_valid_party_role",
        "where user_login_id = #{userLoginId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("userLoginId") String userLoginId, @Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_valid_party_role
     *
     * @mbg.generated Thu Nov 23 12:53:58 CET 2023
     */
    @Insert({
        "insert into user_login_valid_party_role (user_login_id, party_id, ",
        "role_type_id, comments, ",
        "last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{userLoginId,jdbcType=VARCHAR}, #{partyId,jdbcType=VARCHAR}, ",
        "#{roleTypeId,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(UserLoginValidPartyRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_valid_party_role
     *
     * @mbg.generated Thu Nov 23 12:53:58 CET 2023
     */
    @Select({
        "select",
        "user_login_id, party_id, role_type_id, comments, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from user_login_valid_party_role",
        "where user_login_id = #{userLoginId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="user_login_id", property="userLoginId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    UserLoginValidPartyRole selectByPrimaryKey(@Param("userLoginId") String userLoginId, @Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_valid_party_role
     *
     * @mbg.generated Thu Nov 23 12:53:58 CET 2023
     */
    @Select({
        "select",
        "user_login_id, party_id, role_type_id, comments, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp",
        "from user_login_valid_party_role"
    })
    @Results(id="userLoginValidPartyRoleResultMap", value = {
        @Result(column="user_login_id", property="userLoginId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UserLoginValidPartyRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_valid_party_role
     *
     * @mbg.generated Thu Nov 23 12:53:58 CET 2023
     */
    @Update({
        "update user_login_valid_party_role",
        "set comments = #{comments,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP}",
        "where user_login_id = #{userLoginId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserLoginValidPartyRole row);

    List<UserLoginValidPartyRoleEx> getUserLoginValidPartyRoleList(@Param("user") String user);
}