package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.UserLoginHistory;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

@Mapper
@Repository
public interface UserLoginHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbg.generated Fri Feb 16 10:23:31 CET 2024
     */
    @Delete({
        "delete from user_login_history",
        "where user_login_id = #{userLoginId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(@Param("userLoginId") String userLoginId, @Param("fromDate") Instant fromDate);

    /**
     * This method delete all user_login_history where created_stamp is <= minusYear
     *
     * @mbg.generated Fri Feb 16 10:23:31 CET 2024
     */
    @Delete({
            "delete from user_login_history",
            "where created_stamp <= #{minusYear,jdbcType=TIMESTAMP}"
    })
    int deleteOld(@Param("minusYear") Instant minusYear);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbg.generated Fri Feb 16 10:23:31 CET 2024
     */
    @Insert({
        "insert into user_login_history (user_login_id, from_date, ",
        "visit_id, thru_date, ",
        "password_used, successful_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "party_id)",
        "values (#{userLoginId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{visitId,jdbcType=VARCHAR}, #{thruDate,jdbcType=TIMESTAMP}, ",
        "#{passwordUsed,jdbcType=VARCHAR}, #{successfulLogin,jdbcType=CHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{partyId,jdbcType=VARCHAR})"
    })
    int insert(UserLoginHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbg.generated Fri Feb 16 10:23:31 CET 2024
     */
    @Select({
        "select",
        "user_login_id, from_date, visit_id, thru_date, password_used, successful_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp, ",
        "party_id",
        "from user_login_history",
        "where user_login_id = #{userLoginId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="user_login_id", property="userLoginId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="visit_id", property="visitId", jdbcType=JdbcType.VARCHAR),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="password_used", property="passwordUsed", jdbcType=JdbcType.VARCHAR),
        @Result(column="successful_login", property="successfulLogin", jdbcType=JdbcType.CHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR)
    })
    UserLoginHistory selectByPrimaryKey(@Param("userLoginId") String userLoginId, @Param("fromDate") Instant fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbg.generated Fri Feb 16 10:23:31 CET 2024
     */
    @Select({
        "select",
        "user_login_id, from_date, visit_id, thru_date, password_used, successful_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp, ",
        "party_id",
        "from user_login_history"
    })
    @Results({
        @Result(column="user_login_id", property="userLoginId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="visit_id", property="visitId", jdbcType=JdbcType.VARCHAR),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="password_used", property="passwordUsed", jdbcType=JdbcType.VARCHAR),
        @Result(column="successful_login", property="successfulLogin", jdbcType=JdbcType.CHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR)
    })
    List<UserLoginHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbg.generated Fri Feb 16 10:23:31 CET 2024
     */
    @Update({
        "update user_login_history",
        "set visit_id = #{visitId,jdbcType=VARCHAR},",
          "thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "password_used = #{passwordUsed,jdbcType=VARCHAR},",
          "successful_login = #{successfulLogin,jdbcType=CHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "party_id = #{partyId,jdbcType=VARCHAR}",
        "where user_login_id = #{userLoginId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(UserLoginHistory row);

    @Select({
            "select *",
            "from user_login_history",
            "where user_login_history.user_login_id = #{username,jdbcType=VARCHAR} and user_login_history.password_used = #{token,jdbcType=VARCHAR}"
    })
    @ResultType(UserLoginHistory.class)
    UserLoginHistory verifyToken(@Param("username") String username, @Param("token") String token);


    @Update({
            "update user_login_history set thru_date = current_timestamp where password_used is not null and thru_date > current_timestamp and user_login_id = #{userLoginId}"
    })
    int updatePreToken(@Param("userLoginId") String userLoginId);
}