package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortType;
import java.util.List;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortTypeContentExt;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WorkEffortTypeMapper {

    @Delete({
        "delete from work_effort_type",
        "where work_effort_type_id = #{workEffortTypeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String workEffortTypeId);


    @Insert({
        "insert into work_effort_type (work_effort_type_id, parent_type_id, ",
        "has_table, description, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "influence_catalog_id, icon_content_id, ",
        "effort_uom_id, note, ",
        "code_prefix, code_counter, ",
        "is_template, is_root, local_name_content_id, ",
        "is_in_only_one_card, all_roles_assigned, ",
        "all_org_assigned, child_template_id, ",
        "from_date, thru_date, ",
        "hierarchy_assoc_type_id, weight_control_sum, ",
        "uom_range_score_id, we_layout_type_enum_id, ",
        "period_type_id, type_id1, ",
        "type_id2, type_id3, ",
        "type_id4, rule_type_id1, ",
        "rule_type_id2, rule_type_id3, ",
        "rule_type_id4, rule_type_id5, ",
        "min1, min2, min3, ",
        "min4, min5, max1, ",
        "max2, max3, max4, ",
        "max5, weight_kpi, ",
        "weight_sons, weight_assoc_work_effort, ",
        "total_enum_id_kpi, total_enum_id_sons, ",
        "total_enum_id_assoc, work_effort_assoc_type_id, ",
        "we_purpose_type_id_res, we_purpose_type_id_ind, ",
        "etch, short_label, ",
        "is_indic_auto, frame_enum_id, ",
        "seq_digit, seq_only_id, ",
        "we_purpose_type_id_we, has_product, ",
        "has_person_filter, weight_kpi_control_sum, ",
        "work_effort_type_hierarchy_id, show_scorekpi, ",
        "enable_snapshot, copy, ",
        "purpose_etch, eval_enum_id, ",
        "apply_score_range, enable_multi_year_flag, ",
        "org_unit_role_type_id, for_all_users, ",
        "is_role_type_id_auto, role_type_id_auto, ",
        "party_rel_type_id_auto, parent_period_filter, ",
        "period_open_enum_id, show_hierarchy, ",
        "score_period_enum_id, description_lang, ",
        "etch_lang, note_lang, ",
        "purpose_etch_lang, is_root_active, ",
        "reminder_active, seq_esp, ",
        "gp_menu_enum_id, initially_collapsed, ",
        "batch_status_active, last_modified_by_user_login, ",
        "created_by_user_login, org_unit_role_type_id2, ",
        "org_unit_role_type_id3)",
        "values (#{workEffortTypeId,jdbcType=VARCHAR}, #{parentTypeId,jdbcType=VARCHAR}, ",
        "#{hasTable,jdbcType=CHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{influenceCatalogId,jdbcType=VARCHAR}, #{iconContentId,jdbcType=VARCHAR}, ",
        "#{effortUomId,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR}, ",
        "#{codePrefix,jdbcType=VARCHAR}, #{codeCounter,jdbcType=VARCHAR}, ",
        "#{isTemplate,jdbcType=CHAR}, #{isRoot,jdbcType=CHAR}, #{localNameContentId,jdbcType=VARCHAR}, ",
        "#{isInOnlyOneCard,jdbcType=CHAR}, #{allRolesAssigned,jdbcType=CHAR}, ",
        "#{allOrgAssigned,jdbcType=CHAR}, #{childTemplateId,jdbcType=VARCHAR}, ",
        "#{fromDate,jdbcType=TIMESTAMP}, #{thruDate,jdbcType=TIMESTAMP}, ",
        "#{hierarchyAssocTypeId,jdbcType=VARCHAR}, #{weightControlSum,jdbcType=DOUBLE}, ",
        "#{uomRangeScoreId,jdbcType=VARCHAR}, #{weLayoutTypeEnumId,jdbcType=VARCHAR}, ",
        "#{periodTypeId,jdbcType=VARCHAR}, #{typeId1,jdbcType=VARCHAR}, ",
        "#{typeId2,jdbcType=VARCHAR}, #{typeId3,jdbcType=VARCHAR}, ",
        "#{typeId4,jdbcType=VARCHAR}, #{ruleTypeId1,jdbcType=VARCHAR}, ",
        "#{ruleTypeId2,jdbcType=VARCHAR}, #{ruleTypeId3,jdbcType=VARCHAR}, ",
        "#{ruleTypeId4,jdbcType=VARCHAR}, #{ruleTypeId5,jdbcType=VARCHAR}, ",
        "#{min1,jdbcType=NUMERIC}, #{min2,jdbcType=NUMERIC}, #{min3,jdbcType=NUMERIC}, ",
        "#{min4,jdbcType=NUMERIC}, #{min5,jdbcType=NUMERIC}, #{max1,jdbcType=NUMERIC}, ",
        "#{max2,jdbcType=NUMERIC}, #{max3,jdbcType=NUMERIC}, #{max4,jdbcType=NUMERIC}, ",
        "#{max5,jdbcType=NUMERIC}, #{weightKpi,jdbcType=DOUBLE}, ",
        "#{weightSons,jdbcType=DOUBLE}, #{weightAssocWorkEffort,jdbcType=DOUBLE}, ",
        "#{totalEnumIdKpi,jdbcType=VARCHAR}, #{totalEnumIdSons,jdbcType=VARCHAR}, ",
        "#{totalEnumIdAssoc,jdbcType=VARCHAR}, #{workEffortAssocTypeId,jdbcType=VARCHAR}, ",
        "#{wePurposeTypeIdRes,jdbcType=VARCHAR}, #{wePurposeTypeIdInd,jdbcType=VARCHAR}, ",
        "#{etch,jdbcType=VARCHAR}, #{shortLabel,jdbcType=VARCHAR}, ",
        "#{isIndicAuto,jdbcType=CHAR}, #{frameEnumId,jdbcType=VARCHAR}, ",
        "#{seqDigit,jdbcType=NUMERIC}, #{seqOnlyId,jdbcType=CHAR}, ",
        "#{wePurposeTypeIdWe,jdbcType=VARCHAR}, #{hasProduct,jdbcType=CHAR}, ",
        "#{hasPersonFilter,jdbcType=CHAR}, #{weightKpiControlSum,jdbcType=DOUBLE}, ",
        "#{workEffortTypeHierarchyId,jdbcType=VARCHAR}, #{showScorekpi,jdbcType=CHAR}, ",
        "#{enableSnapshot,jdbcType=CHAR}, #{copy,jdbcType=CHAR}, ",
        "#{purposeEtch,jdbcType=VARCHAR}, #{evalEnumId,jdbcType=VARCHAR}, ",
        "#{applyScoreRange,jdbcType=CHAR}, #{enableMultiYearFlag,jdbcType=CHAR}, ",
        "#{orgUnitRoleTypeId,jdbcType=VARCHAR}, #{forAllUsers,jdbcType=CHAR}, ",
        "#{isRoleTypeIdAuto,jdbcType=CHAR}, #{roleTypeIdAuto,jdbcType=VARCHAR}, ",
        "#{partyRelTypeIdAuto,jdbcType=VARCHAR}, #{parentPeriodFilter,jdbcType=CHAR}, ",
        "#{periodOpenEnumId,jdbcType=VARCHAR}, #{showHierarchy,jdbcType=CHAR}, ",
        "#{scorePeriodEnumId,jdbcType=VARCHAR}, #{descriptionLang,jdbcType=VARCHAR}, ",
        "#{etchLang,jdbcType=VARCHAR}, #{noteLang,jdbcType=VARCHAR}, ",
        "#{purposeEtchLang,jdbcType=VARCHAR}, #{isRootActive,jdbcType=CHAR}, ",
        "#{reminderActive,jdbcType=CHAR}, #{seqEsp,jdbcType=NUMERIC}, ",
        "#{gpMenuEnumId,jdbcType=VARCHAR}, #{initiallyCollapsed,jdbcType=VARCHAR}, ",
        "#{batchStatusActive,jdbcType=CHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{orgUnitRoleTypeId2,jdbcType=VARCHAR}, ",
        "#{orgUnitRoleTypeId3,jdbcType=VARCHAR})"
    })
    int insert(WorkEffortType row);


    @Select({
        "select * ",
        "from work_effort_type",
        "where work_effort_type_id = #{workEffortTypeId,jdbcType=VARCHAR}"
    })
    @Results(id = "workEffortType", value = {
        @Result(column="work_effort_type_id", property="workEffortTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="parent_type_id", property="parentTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_table", property="hasTable", jdbcType=JdbcType.CHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="influence_catalog_id", property="influenceCatalogId", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon_content_id", property="iconContentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="code_prefix", property="codePrefix", jdbcType=JdbcType.VARCHAR),
        @Result(column="code_counter", property="codeCounter", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_template", property="isTemplate", jdbcType=JdbcType.CHAR),
        @Result(column="is_root", property="isRoot", jdbcType=JdbcType.CHAR),
        @Result(column="local_name_content_id", property="localNameContentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_in_only_one_card", property="isInOnlyOneCard", jdbcType=JdbcType.CHAR),
        @Result(column="all_roles_assigned", property="allRolesAssigned", jdbcType=JdbcType.CHAR),
        @Result(column="all_org_assigned", property="allOrgAssigned", jdbcType=JdbcType.CHAR),
        @Result(column="child_template_id", property="childTemplateId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="hierarchy_assoc_type_id", property="hierarchyAssocTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight_control_sum", property="weightControlSum", jdbcType=JdbcType.DOUBLE),
        @Result(column="uom_range_score_id", property="uomRangeScoreId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_layout_type_enum_id", property="weLayoutTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="period_type_id", property="periodTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id1", property="typeId1", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id2", property="typeId2", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id3", property="typeId3", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id4", property="typeId4", jdbcType=JdbcType.VARCHAR),
        @Result(column="rule_type_id1", property="ruleTypeId1", jdbcType=JdbcType.VARCHAR),
        @Result(column="rule_type_id2", property="ruleTypeId2", jdbcType=JdbcType.VARCHAR),
        @Result(column="rule_type_id3", property="ruleTypeId3", jdbcType=JdbcType.VARCHAR),
        @Result(column="rule_type_id4", property="ruleTypeId4", jdbcType=JdbcType.VARCHAR),
        @Result(column="rule_type_id5", property="ruleTypeId5", jdbcType=JdbcType.VARCHAR),
        @Result(column="min1", property="min1", jdbcType=JdbcType.NUMERIC),
        @Result(column="min2", property="min2", jdbcType=JdbcType.NUMERIC),
        @Result(column="min3", property="min3", jdbcType=JdbcType.NUMERIC),
        @Result(column="min4", property="min4", jdbcType=JdbcType.NUMERIC),
        @Result(column="min5", property="min5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max1", property="max1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max2", property="max2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max3", property="max3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max4", property="max4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max5", property="max5", jdbcType=JdbcType.NUMERIC),
        @Result(column="weight_kpi", property="weightKpi", jdbcType=JdbcType.DOUBLE),
        @Result(column="weight_sons", property="weightSons", jdbcType=JdbcType.DOUBLE),
        @Result(column="weight_assoc_work_effort", property="weightAssocWorkEffort", jdbcType=JdbcType.DOUBLE),
        @Result(column="total_enum_id_kpi", property="totalEnumIdKpi", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_enum_id_sons", property="totalEnumIdSons", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_enum_id_assoc", property="totalEnumIdAssoc", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_assoc_type_id", property="workEffortAssocTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_purpose_type_id_res", property="wePurposeTypeIdRes", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_purpose_type_id_ind", property="wePurposeTypeIdInd", jdbcType=JdbcType.VARCHAR),
        @Result(column="etch", property="etch", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_label", property="shortLabel", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_indic_auto", property="isIndicAuto", jdbcType=JdbcType.CHAR),
        @Result(column="frame_enum_id", property="frameEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq_digit", property="seqDigit", jdbcType=JdbcType.NUMERIC),
        @Result(column="seq_only_id", property="seqOnlyId", jdbcType=JdbcType.CHAR),
        @Result(column="we_purpose_type_id_we", property="wePurposeTypeIdWe", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_product", property="hasProduct", jdbcType=JdbcType.CHAR),
        @Result(column="has_person_filter", property="hasPersonFilter", jdbcType=JdbcType.CHAR),
        @Result(column="weight_kpi_control_sum", property="weightKpiControlSum", jdbcType=JdbcType.DOUBLE),
        @Result(column="work_effort_type_hierarchy_id", property="workEffortTypeHierarchyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="show_scorekpi", property="showScorekpi", jdbcType=JdbcType.CHAR),
        @Result(column="enable_snapshot", property="enableSnapshot", jdbcType=JdbcType.CHAR),
        @Result(column="copy", property="copy", jdbcType=JdbcType.CHAR),
        @Result(column="purpose_etch", property="purposeEtch", jdbcType=JdbcType.VARCHAR),
        @Result(column="eval_enum_id", property="evalEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="apply_score_range", property="applyScoreRange", jdbcType=JdbcType.CHAR),
        @Result(column="enable_multi_year_flag", property="enableMultiYearFlag", jdbcType=JdbcType.CHAR),
        @Result(column="org_unit_role_type_id", property="orgUnitRoleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="for_all_users", property="forAllUsers", jdbcType=JdbcType.CHAR),
        @Result(column="is_role_type_id_auto", property="isRoleTypeIdAuto", jdbcType=JdbcType.CHAR),
        @Result(column="role_type_id_auto", property="roleTypeIdAuto", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_rel_type_id_auto", property="partyRelTypeIdAuto", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_period_filter", property="parentPeriodFilter", jdbcType=JdbcType.CHAR),
        @Result(column="period_open_enum_id", property="periodOpenEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="show_hierarchy", property="showHierarchy", jdbcType=JdbcType.CHAR),
        @Result(column="score_period_enum_id", property="scorePeriodEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="etch_lang", property="etchLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="note_lang", property="noteLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="purpose_etch_lang", property="purposeEtchLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_root_active", property="isRootActive", jdbcType=JdbcType.CHAR),
        @Result(column="reminder_active", property="reminderActive", jdbcType=JdbcType.CHAR),
        @Result(column="seq_esp", property="seqEsp", jdbcType=JdbcType.NUMERIC),
        @Result(column="gp_menu_enum_id", property="gpMenuEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="initially_collapsed", property="initiallyCollapsed", jdbcType=JdbcType.VARCHAR),
        @Result(column="batch_status_active", property="batchStatusActive", jdbcType=JdbcType.CHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_unit_role_type_id2", property="orgUnitRoleTypeId2", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_unit_role_type_id3", property="orgUnitRoleTypeId3", jdbcType=JdbcType.VARCHAR)
    })
    WorkEffortType selectByPrimaryKey(String workEffortTypeId);


    @Select({
        "select * ",
        "from work_effort_type"
    })
    @ResultMap("workEffortType")
    List<WorkEffortType> selectAll();

    @Select({
            "select * ",
            "from work_effort_type",
            "where work_effort_type_id like #{likeId}"
    })
    @ResultMap("workEffortType")
    List<WorkEffortType> selectLikeWorkEffortTypeId(@Param("likeId") String likeId);


    @Select({
            "select * ",
            "from work_effort_type",
            "where is_root = #{isRoot,jdbcType=VARCHAR}"
    })
    @ResultMap("workEffortType")
    List<WorkEffortType> selectByIsRoot(String isRoot);

    @Select({
            "select wet.*,",

            //WorkEffortTypeContent
            "wetc.work_effort_type_id as wetc_work_effort_type_id, wetc.content_id as wetc_content_id, wetc.we_type_content_type_id as wetc_we_type_content_type_id, wetc.sequence_num as wetc_sequence_num, wetc.etch as wetc_etch, ",
            "wetc.work_effort_purpose_type_id as wetc_work_effort_purpose_type_id, wetc.params as wetc_params, wetc.is_visible as wetc_is_visible, wetc.use_filter as wetc_use_filter, wetc.etch_lang as wetc_etch_lang, wetc.only_admin as wetc_only_admin, ",
            "wetc.last_modified_by_user_login as wetc_last_modified_by_user_login, wetc.created_by_user_login as wetc_created_by_user_login, wetc.last_updated_stamp as wetc_last_updated_stamp, wetc.last_updated_tx_stamp as wetc_last_updated_tx_stamp, ",
            "wetc.created_stamp as wetc_created_stamp, wetc.created_tx_stamp as wetc_created_tx_stamp, wetc.is_mandatory as wetc_is_mandatory,",

            //Content
            "c.content_id as c_content_id, c.content_type_id as c_content_type_id, c.owner_content_id as c_owner_content_id, c.decorator_content_id as c_decorator_content_id, c.instance_of_content_id as c_instance_of_content_id, ",
            "c.data_resource_id as c_data_resource_id, c.template_data_resource_id as c_template_data_resource_id, c.data_source_id as c_data_source_id, c.status_id as c_status_id, c.privilege_enum_id as c_privilege_enum_id, ",
            "c.service_name as c_service_name, c.content_name as c_content_name, c.description as c_description, c.locale_string as c_locale_string, c.mime_type_id as c_mime_type_id, c.character_set_id as c_character_set_id, ",
            "c.child_leaf_count as c_child_leaf_count, c.child_branch_count as c_child_branch_count, c.created_date as c_created_date, c.created_by_user_login as c_created_by_user_login, c.last_modified_date as c_last_modified_date, ",
            "c.last_modified_by_user_login as c_last_modified_by_user_login, c.last_updated_stamp as c_last_updated_stamp, c.last_updated_tx_stamp as c_last_updated_tx_stamp, c.created_stamp as c_created_stamp, ",
            "c.created_tx_stamp as c_created_tx_stamp, c.description_lang as c_description_lang" ,

            "from work_effort_type wet",
            "inner join work_effort_type_content wetc on wetc.work_effort_type_id = wet.work_effort_type_id",
            "inner join content c on c.content_id = wetc.content_id ",
            "where wet.reminder_active = 'Y'  and  wetc.content_id = #{contentId}"
    })
    @Results(id = "workEffortTypeContentExt", value = {
            @Result(column="work_effort_type_id", property="workEffortTypeId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="parent_type_id", property="parentTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="has_table", property="hasTable", jdbcType=JdbcType.CHAR),
            @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
            @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="influence_catalog_id", property="influenceCatalogId", jdbcType=JdbcType.VARCHAR),
            @Result(column="icon_content_id", property="iconContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="effort_uom_id", property="effortUomId", jdbcType=JdbcType.VARCHAR),
            @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
            @Result(column="code_prefix", property="codePrefix", jdbcType=JdbcType.VARCHAR),
            @Result(column="code_counter", property="codeCounter", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_template", property="isTemplate", jdbcType=JdbcType.CHAR),
            @Result(column="is_root", property="isRoot", jdbcType=JdbcType.CHAR),
            @Result(column="local_name_content_id", property="localNameContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_in_only_one_card", property="isInOnlyOneCard", jdbcType=JdbcType.CHAR),
            @Result(column="all_roles_assigned", property="allRolesAssigned", jdbcType=JdbcType.CHAR),
            @Result(column="all_org_assigned", property="allOrgAssigned", jdbcType=JdbcType.CHAR),
            @Result(column="child_template_id", property="childTemplateId", jdbcType=JdbcType.VARCHAR),
            @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="hierarchy_assoc_type_id", property="hierarchyAssocTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="weight_control_sum", property="weightControlSum", jdbcType=JdbcType.DOUBLE),
            @Result(column="uom_range_score_id", property="uomRangeScoreId", jdbcType=JdbcType.VARCHAR),
            @Result(column="we_layout_type_enum_id", property="weLayoutTypeEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="period_type_id", property="periodTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="type_id1", property="typeId1", jdbcType=JdbcType.VARCHAR),
            @Result(column="type_id2", property="typeId2", jdbcType=JdbcType.VARCHAR),
            @Result(column="type_id3", property="typeId3", jdbcType=JdbcType.VARCHAR),
            @Result(column="type_id4", property="typeId4", jdbcType=JdbcType.VARCHAR),
            @Result(column="rule_type_id1", property="ruleTypeId1", jdbcType=JdbcType.VARCHAR),
            @Result(column="rule_type_id2", property="ruleTypeId2", jdbcType=JdbcType.VARCHAR),
            @Result(column="rule_type_id3", property="ruleTypeId3", jdbcType=JdbcType.VARCHAR),
            @Result(column="rule_type_id4", property="ruleTypeId4", jdbcType=JdbcType.VARCHAR),
            @Result(column="rule_type_id5", property="ruleTypeId5", jdbcType=JdbcType.VARCHAR),
            @Result(column="min1", property="min1", jdbcType=JdbcType.NUMERIC),
            @Result(column="min2", property="min2", jdbcType=JdbcType.NUMERIC),
            @Result(column="min3", property="min3", jdbcType=JdbcType.NUMERIC),
            @Result(column="min4", property="min4", jdbcType=JdbcType.NUMERIC),
            @Result(column="min5", property="min5", jdbcType=JdbcType.NUMERIC),
            @Result(column="max1", property="max1", jdbcType=JdbcType.NUMERIC),
            @Result(column="max2", property="max2", jdbcType=JdbcType.NUMERIC),
            @Result(column="max3", property="max3", jdbcType=JdbcType.NUMERIC),
            @Result(column="max4", property="max4", jdbcType=JdbcType.NUMERIC),
            @Result(column="max5", property="max5", jdbcType=JdbcType.NUMERIC),
            @Result(column="weight_kpi", property="weightKpi", jdbcType=JdbcType.DOUBLE),
            @Result(column="weight_sons", property="weightSons", jdbcType=JdbcType.DOUBLE),
            @Result(column="weight_assoc_work_effort", property="weightAssocWorkEffort", jdbcType=JdbcType.DOUBLE),
            @Result(column="total_enum_id_kpi", property="totalEnumIdKpi", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_enum_id_sons", property="totalEnumIdSons", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_enum_id_assoc", property="totalEnumIdAssoc", jdbcType=JdbcType.VARCHAR),
            @Result(column="work_effort_assoc_type_id", property="workEffortAssocTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="we_purpose_type_id_res", property="wePurposeTypeIdRes", jdbcType=JdbcType.VARCHAR),
            @Result(column="we_purpose_type_id_ind", property="wePurposeTypeIdInd", jdbcType=JdbcType.VARCHAR),
            @Result(column="etch", property="etch", jdbcType=JdbcType.VARCHAR),
            @Result(column="short_label", property="shortLabel", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_indic_auto", property="isIndicAuto", jdbcType=JdbcType.CHAR),
            @Result(column="frame_enum_id", property="frameEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="seq_digit", property="seqDigit", jdbcType=JdbcType.NUMERIC),
            @Result(column="seq_only_id", property="seqOnlyId", jdbcType=JdbcType.CHAR),
            @Result(column="we_purpose_type_id_we", property="wePurposeTypeIdWe", jdbcType=JdbcType.VARCHAR),
            @Result(column="has_product", property="hasProduct", jdbcType=JdbcType.CHAR),
            @Result(column="has_person_filter", property="hasPersonFilter", jdbcType=JdbcType.CHAR),
            @Result(column="weight_kpi_control_sum", property="weightKpiControlSum", jdbcType=JdbcType.DOUBLE),
            @Result(column="work_effort_type_hierarchy_id", property="workEffortTypeHierarchyId", jdbcType=JdbcType.VARCHAR),
            @Result(column="show_scorekpi", property="showScorekpi", jdbcType=JdbcType.CHAR),
            @Result(column="enable_snapshot", property="enableSnapshot", jdbcType=JdbcType.CHAR),
            @Result(column="copy", property="copy", jdbcType=JdbcType.CHAR),
            @Result(column="purpose_etch", property="purposeEtch", jdbcType=JdbcType.VARCHAR),
            @Result(column="eval_enum_id", property="evalEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="apply_score_range", property="applyScoreRange", jdbcType=JdbcType.CHAR),
            @Result(column="enable_multi_year_flag", property="enableMultiYearFlag", jdbcType=JdbcType.CHAR),
            @Result(column="org_unit_role_type_id", property="orgUnitRoleTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="for_all_users", property="forAllUsers", jdbcType=JdbcType.CHAR),
            @Result(column="is_role_type_id_auto", property="isRoleTypeIdAuto", jdbcType=JdbcType.CHAR),
            @Result(column="role_type_id_auto", property="roleTypeIdAuto", jdbcType=JdbcType.VARCHAR),
            @Result(column="party_rel_type_id_auto", property="partyRelTypeIdAuto", jdbcType=JdbcType.VARCHAR),
            @Result(column="parent_period_filter", property="parentPeriodFilter", jdbcType=JdbcType.CHAR),
            @Result(column="period_open_enum_id", property="periodOpenEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="show_hierarchy", property="showHierarchy", jdbcType=JdbcType.CHAR),
            @Result(column="score_period_enum_id", property="scorePeriodEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="description_lang", property="descriptionLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="etch_lang", property="etchLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="note_lang", property="noteLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="purpose_etch_lang", property="purposeEtchLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_root_active", property="isRootActive", jdbcType=JdbcType.CHAR),
            @Result(column="reminder_active", property="reminderActive", jdbcType=JdbcType.CHAR),
            @Result(column="seq_esp", property="seqEsp", jdbcType=JdbcType.NUMERIC),
            @Result(column="gp_menu_enum_id", property="gpMenuEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="initially_collapsed", property="initiallyCollapsed", jdbcType=JdbcType.VARCHAR),
            @Result(column="batch_status_active", property="batchStatusActive", jdbcType=JdbcType.CHAR),
            @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="org_unit_role_type_id2", property="orgUnitRoleTypeId2", jdbcType=JdbcType.VARCHAR),
            @Result(column="org_unit_role_type_id3", property="orgUnitRoleTypeId3", jdbcType=JdbcType.VARCHAR),

            //WorkEffortTypeContent
            @Result(column="wetc_work_effort_type_id", property="workEffortContentType.workEffortTypeId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="wetc_content_id", property="workEffortContentType.contentId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="wetc_we_type_content_type_id", property="workEffortContentType.weTypeContentTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_sequence_num", property="workEffortContentType.sequenceNum", jdbcType=JdbcType.NUMERIC),
            @Result(column="wetc_etch", property="workEffortContentType.etch", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_work_effort_purpose_type_id", property="workEffortContentType.workEffortPurposeTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_params", property="workEffortContentType.params", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_is_visible", property="workEffortContentType.isVisible", jdbcType=JdbcType.CHAR),
            @Result(column="wetc_use_filter", property="workEffortContentType.useFilter", jdbcType=JdbcType.CHAR),
            @Result(column="wetc_etch_lang", property="workEffortContentType.etchLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_only_admin", property="workEffortContentType.onlyAdmin", jdbcType=JdbcType.CHAR),
            @Result(column="wetc_last_modified_by_user_login", property="workEffortContentType.lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_created_by_user_login", property="workEffortContentType.createdByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="wetc_last_updated_stamp", property="workEffortContentType.lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wetc_last_updated_tx_stamp", property="workEffortContentType.lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wetc_created_stamp", property="workEffortContentType.createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wetc_created_tx_stamp", property="workEffortContentType.createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wetc_is_mandatory", property="workEffortContentType.isMandatory", jdbcType=JdbcType.CHAR),

            //Content
            @Result(column="c_content_id", property="content.contentId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="c_content_type_id", property="content.contentTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_owner_content_id", property="content.ownerContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_decorator_content_id", property="content.decoratorContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_instance_of_content_id", property="content.instanceOfContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_data_resource_id", property="content.dataResourceId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_template_data_resource_id", property="content.templateDataResourceId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_data_source_id", property="content.dataSourceId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_status_id", property="content.statusId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_privilege_enum_id", property="content.privilegeEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_service_name", property="content.serviceName", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_content_name", property="content.contentName", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_description", property="content.description", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_locale_string", property="content.localeString", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_mime_type_id", property="content.mimeTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_character_set_id", property="content.characterSetId", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_child_leaf_count", property="content.childLeafCount", jdbcType=JdbcType.NUMERIC),
            @Result(column="c_child_branch_count", property="content.childBranchCount", jdbcType=JdbcType.NUMERIC),
            @Result(column="c_created_date", property="content.createdDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="c_created_by_user_login", property="content.createdByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_last_modified_date", property="content.lastModifiedDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="c_last_modified_by_user_login", property="content.lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="c_last_updated_stamp", property="content.lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="c_last_updated_tx_stamp", property="content.lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="c_created_stamp", property="content.createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="c_created_tx_stamp", property="content.createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="c_description_lang", property="content.descriptionLang", jdbcType=JdbcType.VARCHAR)

    })
    List<WorkEffortTypeContentExt> getWorkEffortTypeReminderActive(@Param("contentId") String contentId);


    @Select("select * " +
            "from WORK_EFFORT_TYPE WORK_EFFORT_TYPE\n" +
            "where WORK_EFFORT_TYPE.WORK_EFFORT_TYPE_ID in( select WORK_EFFORT_TYPE.WORK_EFFORT_TYPE_ID\n" +
            "from WORK_EFFORT_TYPE WORK_EFFORT_TYPE\n" +
            "join WORK_EFFORT_TYPE_CONTENT WETC on WETC.WORK_EFFORT_TYPE_ID = WORK_EFFORT_TYPE.WORK_EFFORT_TYPE_ID\n" +
            "where WETC.WE_TYPE_CONTENT_TYPE_ID = 'REPORT')" +
            "and WORK_EFFORT_TYPE.WORK_EFFORT_TYPE_ID in (select WORK_EFFORT_TYPE_TYPE.WORK_EFFORT_TYPE_ID_FROM\n" +
            "from WORK_EFFORT_TYPE_TYPE WORK_EFFORT_TYPE_TYPE\n" +
            "where WORK_EFFORT_TYPE_TYPE.WORK_EFFORT_TYPE_ID_ROOT = #{workEffortTypeId,jdbcType=VARCHAR})")
    @ResultMap("workEffortType")
    List<WorkEffortType> getWorkEffortTypesParametric(@Param("workEffortTypeId") String workEffortTypeId);

    @ResultMap("workEffortType")
    List<WorkEffortType> getWorkEffortTypes(@Param("workEffortTypeIds") String[] workEffortTypeIds);


    @Select({
            "select * ",
            "from work_effort_type wt",
            "where wt.parent_type_id = #{parentTypeId,jdbcType=VARCHAR}",
    })
    @ResultType(WorkEffortType.class)
    List<WorkEffortType> getWorkEffortTypeByParentId(String parentTypeId);

    @Update({
        "update work_effort_type",
        "set parent_type_id = #{parentTypeId,jdbcType=VARCHAR},",
          "has_table = #{hasTable,jdbcType=CHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "influence_catalog_id = #{influenceCatalogId,jdbcType=VARCHAR},",
          "icon_content_id = #{iconContentId,jdbcType=VARCHAR},",
          "effort_uom_id = #{effortUomId,jdbcType=VARCHAR},",
          "note = #{note,jdbcType=VARCHAR},",
          "code_prefix = #{codePrefix,jdbcType=VARCHAR},",
          "code_counter = #{codeCounter,jdbcType=VARCHAR},",
          "is_template = #{isTemplate,jdbcType=CHAR},",
          "is_root = #{isRoot,jdbcType=CHAR},",
          "local_name_content_id = #{localNameContentId,jdbcType=VARCHAR},",
          "is_in_only_one_card = #{isInOnlyOneCard,jdbcType=CHAR},",
          "all_roles_assigned = #{allRolesAssigned,jdbcType=CHAR},",
          "all_org_assigned = #{allOrgAssigned,jdbcType=CHAR},",
          "child_template_id = #{childTemplateId,jdbcType=VARCHAR},",
          "from_date = #{fromDate,jdbcType=TIMESTAMP},",
          "thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "hierarchy_assoc_type_id = #{hierarchyAssocTypeId,jdbcType=VARCHAR},",
          "weight_control_sum = #{weightControlSum,jdbcType=DOUBLE},",
          "uom_range_score_id = #{uomRangeScoreId,jdbcType=VARCHAR},",
          "we_layout_type_enum_id = #{weLayoutTypeEnumId,jdbcType=VARCHAR},",
          "period_type_id = #{periodTypeId,jdbcType=VARCHAR},",
          "type_id1 = #{typeId1,jdbcType=VARCHAR},",
          "type_id2 = #{typeId2,jdbcType=VARCHAR},",
          "type_id3 = #{typeId3,jdbcType=VARCHAR},",
          "type_id4 = #{typeId4,jdbcType=VARCHAR},",
          "rule_type_id1 = #{ruleTypeId1,jdbcType=VARCHAR},",
          "rule_type_id2 = #{ruleTypeId2,jdbcType=VARCHAR},",
          "rule_type_id3 = #{ruleTypeId3,jdbcType=VARCHAR},",
          "rule_type_id4 = #{ruleTypeId4,jdbcType=VARCHAR},",
          "rule_type_id5 = #{ruleTypeId5,jdbcType=VARCHAR},",
          "min1 = #{min1,jdbcType=NUMERIC},",
          "min2 = #{min2,jdbcType=NUMERIC},",
          "min3 = #{min3,jdbcType=NUMERIC},",
          "min4 = #{min4,jdbcType=NUMERIC},",
          "min5 = #{min5,jdbcType=NUMERIC},",
          "max1 = #{max1,jdbcType=NUMERIC},",
          "max2 = #{max2,jdbcType=NUMERIC},",
          "max3 = #{max3,jdbcType=NUMERIC},",
          "max4 = #{max4,jdbcType=NUMERIC},",
          "max5 = #{max5,jdbcType=NUMERIC},",
          "weight_kpi = #{weightKpi,jdbcType=DOUBLE},",
          "weight_sons = #{weightSons,jdbcType=DOUBLE},",
          "weight_assoc_work_effort = #{weightAssocWorkEffort,jdbcType=DOUBLE},",
          "total_enum_id_kpi = #{totalEnumIdKpi,jdbcType=VARCHAR},",
          "total_enum_id_sons = #{totalEnumIdSons,jdbcType=VARCHAR},",
          "total_enum_id_assoc = #{totalEnumIdAssoc,jdbcType=VARCHAR},",
          "work_effort_assoc_type_id = #{workEffortAssocTypeId,jdbcType=VARCHAR},",
          "we_purpose_type_id_res = #{wePurposeTypeIdRes,jdbcType=VARCHAR},",
          "we_purpose_type_id_ind = #{wePurposeTypeIdInd,jdbcType=VARCHAR},",
          "etch = #{etch,jdbcType=VARCHAR},",
          "short_label = #{shortLabel,jdbcType=VARCHAR},",
          "is_indic_auto = #{isIndicAuto,jdbcType=CHAR},",
          "frame_enum_id = #{frameEnumId,jdbcType=VARCHAR},",
          "seq_digit = #{seqDigit,jdbcType=NUMERIC},",
          "seq_only_id = #{seqOnlyId,jdbcType=CHAR},",
          "we_purpose_type_id_we = #{wePurposeTypeIdWe,jdbcType=VARCHAR},",
          "has_product = #{hasProduct,jdbcType=CHAR},",
          "has_person_filter = #{hasPersonFilter,jdbcType=CHAR},",
          "weight_kpi_control_sum = #{weightKpiControlSum,jdbcType=DOUBLE},",
          "work_effort_type_hierarchy_id = #{workEffortTypeHierarchyId,jdbcType=VARCHAR},",
          "show_scorekpi = #{showScorekpi,jdbcType=CHAR},",
          "enable_snapshot = #{enableSnapshot,jdbcType=CHAR},",
          "copy = #{copy,jdbcType=CHAR},",
          "purpose_etch = #{purposeEtch,jdbcType=VARCHAR},",
          "eval_enum_id = #{evalEnumId,jdbcType=VARCHAR},",
          "apply_score_range = #{applyScoreRange,jdbcType=CHAR},",
          "enable_multi_year_flag = #{enableMultiYearFlag,jdbcType=CHAR},",
          "org_unit_role_type_id = #{orgUnitRoleTypeId,jdbcType=VARCHAR},",
          "for_all_users = #{forAllUsers,jdbcType=CHAR},",
          "is_role_type_id_auto = #{isRoleTypeIdAuto,jdbcType=CHAR},",
          "role_type_id_auto = #{roleTypeIdAuto,jdbcType=VARCHAR},",
          "party_rel_type_id_auto = #{partyRelTypeIdAuto,jdbcType=VARCHAR},",
          "parent_period_filter = #{parentPeriodFilter,jdbcType=CHAR},",
          "period_open_enum_id = #{periodOpenEnumId,jdbcType=VARCHAR},",
          "show_hierarchy = #{showHierarchy,jdbcType=CHAR},",
          "score_period_enum_id = #{scorePeriodEnumId,jdbcType=VARCHAR},",
          "description_lang = #{descriptionLang,jdbcType=VARCHAR},",
          "etch_lang = #{etchLang,jdbcType=VARCHAR},",
          "note_lang = #{noteLang,jdbcType=VARCHAR},",
          "purpose_etch_lang = #{purposeEtchLang,jdbcType=VARCHAR},",
          "is_root_active = #{isRootActive,jdbcType=CHAR},",
          "reminder_active = #{reminderActive,jdbcType=CHAR},",
          "seq_esp = #{seqEsp,jdbcType=NUMERIC},",
          "gp_menu_enum_id = #{gpMenuEnumId,jdbcType=VARCHAR},",
          "initially_collapsed = #{initiallyCollapsed,jdbcType=VARCHAR},",
          "batch_status_active = #{batchStatusActive,jdbcType=CHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "org_unit_role_type_id2 = #{orgUnitRoleTypeId2,jdbcType=VARCHAR},",
          "org_unit_role_type_id3 = #{orgUnitRoleTypeId3,jdbcType=VARCHAR}",
        "where work_effort_type_id = #{workEffortTypeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WorkEffortType row);
}