package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortMeasureRatScView;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface WorkEffortMeasureRatScViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure_rat_sc_view
     *
     * @mbg.generated Mon Nov 13 09:11:33 CET 2023
     */
    @Insert({
        "insert into work_effort_measure_rat_sc_view (work_effort_measure_id, uom_id, ",
        "uom_rating_value, uom_code, ",
        "uom_code_lang, uom_descr, ",
        "uom_descr_lang)",
        "values (#{workEffortMeasureId,jdbcType=VARCHAR}, #{uomId,jdbcType=VARCHAR}, ",
        "#{uomRatingValue,jdbcType=DOUBLE}, #{uomCode,jdbcType=VARCHAR}, ",
        "#{uomCodeLang,jdbcType=VARCHAR}, #{uomDescr,jdbcType=VARCHAR}, ",
        "#{uomDescrLang,jdbcType=VARCHAR})"
    })
    int insert(WorkEffortMeasureRatScView row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure_rat_sc_view
     *
     * @mbg.generated Mon Nov 13 09:11:33 CET 2023
     */
    @Select({
        "select",
        "work_effort_measure_id, uom_id, uom_rating_value, uom_code, uom_code_lang, uom_descr, ",
        "uom_descr_lang",
        "from work_effort_measure_rat_sc_view"
    })
    @Results(id = "workEffortMeasureRatScViewResultMap", value = {
        @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_id", property="uomId", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_rating_value", property="uomRatingValue", jdbcType=JdbcType.DOUBLE),
        @Result(column="uom_code", property="uomCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_code_lang", property="uomCodeLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_descr", property="uomDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_descr_lang", property="uomDescrLang", jdbcType=JdbcType.VARCHAR)
    })
    List<WorkEffortMeasureRatScView> selectAll();

    List<WorkEffortMeasureRatScView> getWorkEffortMeasureRatScView(String workEffortMeasureId);
}