package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortMeasRatSc;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortMeasRatScExUomRatingScale;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface WorkEffortMeasRatScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_meas_rat_sc
     *
     * @mbg.generated Mon Nov 13 09:17:27 CET 2023
     */
    @Delete({
        "delete from work_effort_meas_rat_sc",
        "where work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR}",
          "and uom_id = #{uomId,jdbcType=VARCHAR}",
          "and uom_rating_value = #{uomRatingValue,jdbcType=DOUBLE}"
    })
    int deleteByPrimaryKey(@Param("workEffortMeasureId") String workEffortMeasureId, @Param("uomId") String uomId, @Param("uomRatingValue") Double uomRatingValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_meas_rat_sc
     *
     * @mbg.generated Mon Nov 13 09:17:27 CET 2023
     */
    @Insert({
        "insert into work_effort_meas_rat_sc (work_effort_measure_id, uom_id, ",
        "uom_rating_value, uom_code, ",
        "uom_descr, uom_code_lang, ",
        "uom_descr_lang, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp)",
        "values (#{workEffortMeasureId,jdbcType=VARCHAR}, #{uomId,jdbcType=VARCHAR}, ",
        "#{uomRatingValue,jdbcType=DOUBLE}, #{uomCode,jdbcType=VARCHAR}, ",
        "#{uomDescr,jdbcType=VARCHAR}, #{uomCodeLang,jdbcType=VARCHAR}, ",
        "#{uomDescrLang,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(WorkEffortMeasRatSc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_meas_rat_sc
     *
     * @mbg.generated Mon Nov 13 09:17:27 CET 2023
     */
    @Select({
        "select",
        "work_effort_measure_id, uom_id, uom_rating_value, uom_code, uom_descr, uom_code_lang, ",
        "uom_descr_lang, last_modified_by_user_login, created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_meas_rat_sc",
        "where work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR}",
          "and uom_id = #{uomId,jdbcType=VARCHAR}",
          "and uom_rating_value = #{uomRatingValue,jdbcType=DOUBLE}"
    })
    @Results({
        @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uom_id", property="uomId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uom_rating_value", property="uomRatingValue", jdbcType=JdbcType.DOUBLE, id=true),
        @Result(column="uom_code", property="uomCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_descr", property="uomDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_code_lang", property="uomCodeLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_descr_lang", property="uomDescrLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    WorkEffortMeasRatSc selectByPrimaryKey(@Param("workEffortMeasureId") String workEffortMeasureId, @Param("uomId") String uomId, @Param("uomRatingValue") Double uomRatingValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_meas_rat_sc
     *
     * @mbg.generated Mon Nov 13 09:17:27 CET 2023
     */
    @Select({
        "select",
        "work_effort_measure_id, uom_id, uom_rating_value, uom_code, uom_descr, uom_code_lang, ",
        "uom_descr_lang, last_modified_by_user_login, created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_meas_rat_sc"
    })
    @Results(id = "workEffortMeasureRatScResultMap", value = {
        @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uom_id", property="uomId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="uom_rating_value", property="uomRatingValue", jdbcType=JdbcType.DOUBLE, id=true),
        @Result(column="uom_code", property="uomCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_descr", property="uomDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_code_lang", property="uomCodeLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_descr_lang", property="uomDescrLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WorkEffortMeasRatSc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_meas_rat_sc
     *
     * @mbg.generated Mon Nov 13 09:17:27 CET 2023
     */
    @Update({
        "update work_effort_meas_rat_sc",
        "set uom_code = #{uomCode,jdbcType=VARCHAR},",
          "uom_descr = #{uomDescr,jdbcType=VARCHAR},",
          "uom_code_lang = #{uomCodeLang,jdbcType=VARCHAR},",
          "uom_descr_lang = #{uomDescrLang,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR}",
          "and uom_id = #{uomId,jdbcType=VARCHAR}",
          "and uom_rating_value = #{uomRatingValue,jdbcType=DOUBLE}"
    })
    int updateByPrimaryKey(WorkEffortMeasRatSc row);

    List<WorkEffortMeasRatScExUomRatingScale> getRatingScaleWEM(String workEffortMeasureId);

    List<WorkEffortMeasRatSc> getWorkEffortMeasRatSc(String workEffortMeasureId);

    boolean deleteByMeasureId(String workEffortMeasureId);

}