package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortAssignmentRate;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortAssignmentRateEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Mapper
@Repository
public interface WorkEffortAssignmentRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assignment_rate
     *
     * @mbg.generated Wed Nov 29 12:21:53 CET 2023
     */
    @Delete({
        "delete from work_effort_assignment_rate",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and rate_type_id = #{rateTypeId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(@Param("workEffortId") String workEffortId, @Param("rateTypeId") String rateTypeId, @Param("partyId") String partyId, @Param("fromDate") Date fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assignment_rate
     *
     * @mbg.generated Wed Nov 29 12:21:53 CET 2023
     */
    @Insert({
        "insert into work_effort_assignment_rate (work_effort_id, rate_type_id, ",
        "party_id, from_date, ",
        "thru_date, rate, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{workEffortId,jdbcType=VARCHAR}, #{rateTypeId,jdbcType=VARCHAR}, ",
        "#{partyId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{rate,jdbcType=NUMERIC}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(WorkEffortAssignmentRate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assignment_rate
     *
     * @mbg.generated Wed Nov 29 12:21:53 CET 2023
     */
    @Select({
        "select",
        "work_effort_id, rate_type_id, party_id, from_date, thru_date, rate, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_assignment_rate",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and rate_type_id = #{rateTypeId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="rate_type_id", property="rateTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="rate", property="rate", jdbcType=JdbcType.NUMERIC),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    WorkEffortAssignmentRate selectByPrimaryKey(@Param("workEffortId") String workEffortId, @Param("rateTypeId") String rateTypeId, @Param("partyId") String partyId, @Param("fromDate") Date fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assignment_rate
     *
     * @mbg.generated Wed Nov 29 12:21:53 CET 2023
     */
    @Select({
        "select",
        "work_effort_id, rate_type_id, party_id, from_date, thru_date, rate, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_assignment_rate"
    })
    @Results({
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="rate_type_id", property="rateTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="rate", property="rate", jdbcType=JdbcType.NUMERIC),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WorkEffortAssignmentRate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assignment_rate
     *
     * @mbg.generated Wed Nov 29 12:21:53 CET 2023
     */
    @Update({
        "update work_effort_assignment_rate",
        "set thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "rate = #{rate,jdbcType=NUMERIC},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP}",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and rate_type_id = #{rateTypeId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(WorkEffortAssignmentRate row);

    List<WorkEffortAssignmentRateEx> getWorkEffortAssignmentRateExs(@Param("workEffortId") String workEffortId);
}