package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortTypeType;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface WorkEffortTypeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_type
     *
     * @mbg.generated Fri Nov 17 17:25:25 CET 2023
     */
    @Delete({
        "delete from work_effort_type_type",
        "where work_effort_type_id_root = #{workEffortTypeIdRoot,jdbcType=VARCHAR}",
          "and work_effort_type_id_from = #{workEffortTypeIdFrom,jdbcType=VARCHAR}",
          "and work_effort_type_id_to = #{workEffortTypeIdTo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("workEffortTypeIdRoot") String workEffortTypeIdRoot, @Param("workEffortTypeIdFrom") String workEffortTypeIdFrom, @Param("workEffortTypeIdTo") String workEffortTypeIdTo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_type
     *
     * @mbg.generated Fri Nov 17 17:25:25 CET 2023
     */
    @Insert({
        "insert into work_effort_type_type (work_effort_type_id_root, work_effort_type_id_from, ",
        "work_effort_type_id_to, sequence_num, ",
        "comments, last_modified_by_user_login, ",
        "created_by_user_login, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp)",
        "values (#{workEffortTypeIdRoot,jdbcType=VARCHAR}, #{workEffortTypeIdFrom,jdbcType=VARCHAR}, ",
        "#{workEffortTypeIdTo,jdbcType=VARCHAR}, #{sequenceNum,jdbcType=NUMERIC}, ",
        "#{comments,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(WorkEffortTypeType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_type
     *
     * @mbg.generated Fri Nov 17 17:25:25 CET 2023
     */
    @Select({
        "select",
        "work_effort_type_id_root, work_effort_type_id_from, work_effort_type_id_to, ",
        "sequence_num, comments, last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_type_type",
        "where work_effort_type_id_root = #{workEffortTypeIdRoot,jdbcType=VARCHAR}",
          "and work_effort_type_id_from = #{workEffortTypeIdFrom,jdbcType=VARCHAR}",
          "and work_effort_type_id_to = #{workEffortTypeIdTo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="work_effort_type_id_root", property="workEffortTypeIdRoot", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="work_effort_type_id_from", property="workEffortTypeIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="work_effort_type_id_to", property="workEffortTypeIdTo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sequence_num", property="sequenceNum", jdbcType=JdbcType.NUMERIC),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    WorkEffortTypeType selectByPrimaryKey(@Param("workEffortTypeIdRoot") String workEffortTypeIdRoot, @Param("workEffortTypeIdFrom") String workEffortTypeIdFrom, @Param("workEffortTypeIdTo") String workEffortTypeIdTo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_type
     *
     * @mbg.generated Fri Nov 17 17:25:25 CET 2023
     */
    @Select({
        "select",
        "work_effort_type_id_root, work_effort_type_id_from, work_effort_type_id_to, ",
        "sequence_num, comments, last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_type_type"
    })
    @Results({
        @Result(column="work_effort_type_id_root", property="workEffortTypeIdRoot", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="work_effort_type_id_from", property="workEffortTypeIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="work_effort_type_id_to", property="workEffortTypeIdTo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sequence_num", property="sequenceNum", jdbcType=JdbcType.NUMERIC),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WorkEffortTypeType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_type
     *
     * @mbg.generated Fri Nov 17 17:25:25 CET 2023
     */
    @Update({
        "update work_effort_type_type",
        "set sequence_num = #{sequenceNum,jdbcType=NUMERIC},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP}",
        "where work_effort_type_id_root = #{workEffortTypeIdRoot,jdbcType=VARCHAR}",
          "and work_effort_type_id_from = #{workEffortTypeIdFrom,jdbcType=VARCHAR}",
          "and work_effort_type_id_to = #{workEffortTypeIdTo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WorkEffortTypeType row);
}