package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.commons.Filter;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortMeasExUom;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortMeasure;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface WorkEffortMeasureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure
     *
     * @mbg.generated Tue Oct 24 10:26:00 CEST 2023
     */
    @Delete({
        "delete from work_effort_measure",
        "where work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String workEffortMeasureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure
     *
     * @mbg.generated Tue Oct 24 10:26:00 CEST 2023
     */
    @Insert({
        "insert into work_effort_measure (work_effort_measure_id, product_id, ",
        "empl_position_type_id, gl_fiscal_type_enum_id, ",
        "party_id, role_type_id, ",
        "we_measure_type_enum_id, we_score_range_enum_id, ",
        "we_score_conv_enum_id, we_alert_rule_enum_id, ",
        "work_effort_influence_id, uom_range_id, ",
        "we_other_goal_enum_id, work_effort_id, ",
        "gl_account_id, from_date, ",
        "thru_date, uom_descr, ",
        "comments, kpi_score_weight, ",
        "other_work_effort_id, period_type_id, ",
        "we_without_perf, org_unit_role_type_id, ",
        "org_unit_id, detail_enum_id, ",
        "data_source_id, current_status_id, ",
        "is_posted, source, sequence_id, ",
        "uom_descr_lang, kpi_other_weight, ",
        "is_invisible, comments_lang, ",
        "last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{workEffortMeasureId,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR}, ",
        "#{emplPositionTypeId,jdbcType=VARCHAR}, #{glFiscalTypeEnumId,jdbcType=VARCHAR}, ",
        "#{partyId,jdbcType=VARCHAR}, #{roleTypeId,jdbcType=VARCHAR}, ",
        "#{weMeasureTypeEnumId,jdbcType=VARCHAR}, #{weScoreRangeEnumId,jdbcType=VARCHAR}, ",
        "#{weScoreConvEnumId,jdbcType=VARCHAR}, #{weAlertRuleEnumId,jdbcType=VARCHAR}, ",
        "#{workEffortInfluenceId,jdbcType=VARCHAR}, #{uomRangeId,jdbcType=VARCHAR}, ",
        "#{weOtherGoalEnumId,jdbcType=VARCHAR}, #{workEffortId,jdbcType=VARCHAR}, ",
        "#{glAccountId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{uomDescr,jdbcType=VARCHAR}, ",
        "#{comments,jdbcType=VARCHAR}, #{kpiScoreWeight,jdbcType=DOUBLE}, ",
        "#{otherWorkEffortId,jdbcType=VARCHAR}, #{periodTypeId,jdbcType=VARCHAR}, ",
        "#{weWithoutPerf,jdbcType=VARCHAR}, #{orgUnitRoleTypeId,jdbcType=VARCHAR}, ",
        "#{orgUnitId,jdbcType=VARCHAR}, #{detailEnumId,jdbcType=VARCHAR}, ",
        "#{dataSourceId,jdbcType=VARCHAR}, #{currentStatusId,jdbcType=VARCHAR}, ",
        "#{isPosted,jdbcType=CHAR}, #{source,jdbcType=VARCHAR}, #{sequenceId,jdbcType=NUMERIC}, ",
        "#{uomDescrLang,jdbcType=VARCHAR}, #{kpiOtherWeight,jdbcType=DOUBLE}, ",
        "#{isInvisible,jdbcType=CHAR}, #{commentsLang,jdbcType=VARCHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(WorkEffortMeasure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure
     *
     * @mbg.generated Tue Oct 24 10:26:00 CEST 2023
     */
    @Select({
        "select",
        "work_effort_measure_id, product_id, empl_position_type_id, gl_fiscal_type_enum_id, ",
        "party_id, role_type_id, we_measure_type_enum_id, we_score_range_enum_id, we_score_conv_enum_id, ",
        "we_alert_rule_enum_id, work_effort_influence_id, uom_range_id, we_other_goal_enum_id, ",
        "work_effort_id, gl_account_id, from_date, thru_date, uom_descr, comments, kpi_score_weight, ",
        "other_work_effort_id, period_type_id, we_without_perf, org_unit_role_type_id, ",
        "org_unit_id, detail_enum_id, data_source_id, current_status_id, is_posted, source, ",
        "sequence_id, uom_descr_lang, kpi_other_weight, is_invisible, comments_lang, ",
        "last_modified_by_user_login, created_by_user_login, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp",
        "from work_effort_measure",
        "where work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="empl_position_type_id", property="emplPositionTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_fiscal_type_enum_id", property="glFiscalTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_measure_type_enum_id", property="weMeasureTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_score_range_enum_id", property="weScoreRangeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_score_conv_enum_id", property="weScoreConvEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_alert_rule_enum_id", property="weAlertRuleEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_influence_id", property="workEffortInfluenceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_range_id", property="uomRangeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_other_goal_enum_id", property="weOtherGoalEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_account_id", property="glAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="uom_descr", property="uomDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="kpi_score_weight", property="kpiScoreWeight", jdbcType=JdbcType.DOUBLE),
        @Result(column="other_work_effort_id", property="otherWorkEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="period_type_id", property="periodTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_without_perf", property="weWithoutPerf", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_unit_role_type_id", property="orgUnitRoleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_unit_id", property="orgUnitId", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_enum_id", property="detailEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="data_source_id", property="dataSourceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="current_status_id", property="currentStatusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.NUMERIC),
        @Result(column="uom_descr_lang", property="uomDescrLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="kpi_other_weight", property="kpiOtherWeight", jdbcType=JdbcType.DOUBLE),
        @Result(column="is_invisible", property="isInvisible", jdbcType=JdbcType.CHAR),
        @Result(column="comments_lang", property="commentsLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    WorkEffortMeasure selectByPrimaryKey(String workEffortMeasureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure
     *
     * @mbg.generated Tue Oct 24 10:26:00 CEST 2023
     */
    @Select({
        "select",
        "work_effort_measure_id, product_id, empl_position_type_id, gl_fiscal_type_enum_id, ",
        "party_id, role_type_id, we_measure_type_enum_id, we_score_range_enum_id, we_score_conv_enum_id, ",
        "we_alert_rule_enum_id, work_effort_influence_id, uom_range_id, we_other_goal_enum_id, ",
        "work_effort_id, gl_account_id, from_date, thru_date, uom_descr, comments, kpi_score_weight, ",
        "other_work_effort_id, period_type_id, we_without_perf, org_unit_role_type_id, ",
        "org_unit_id, detail_enum_id, data_source_id, current_status_id, is_posted, source, ",
        "sequence_id, uom_descr_lang, kpi_other_weight, is_invisible, comments_lang, ",
        "last_modified_by_user_login, created_by_user_login, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp",
        "from work_effort_measure"
    })
    @Results( id = "workEffortMeasureResultMap", value = {
        @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="empl_position_type_id", property="emplPositionTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_fiscal_type_enum_id", property="glFiscalTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_measure_type_enum_id", property="weMeasureTypeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_score_range_enum_id", property="weScoreRangeEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_score_conv_enum_id", property="weScoreConvEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_alert_rule_enum_id", property="weAlertRuleEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_influence_id", property="workEffortInfluenceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="uom_range_id", property="uomRangeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_other_goal_enum_id", property="weOtherGoalEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="gl_account_id", property="glAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="uom_descr", property="uomDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="kpi_score_weight", property="kpiScoreWeight", jdbcType=JdbcType.DOUBLE),
        @Result(column="other_work_effort_id", property="otherWorkEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="period_type_id", property="periodTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="we_without_perf", property="weWithoutPerf", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_unit_role_type_id", property="orgUnitRoleTypeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_unit_id", property="orgUnitId", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_enum_id", property="detailEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="data_source_id", property="dataSourceId", jdbcType=JdbcType.VARCHAR),
        @Result(column="current_status_id", property="currentStatusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.NUMERIC),
        @Result(column="uom_descr_lang", property="uomDescrLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="kpi_other_weight", property="kpiOtherWeight", jdbcType=JdbcType.DOUBLE),
        @Result(column="is_invisible", property="isInvisible", jdbcType=JdbcType.CHAR),
        @Result(column="comments_lang", property="commentsLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WorkEffortMeasure> selectAll();

    @Select({
            "select *",
            "from work_effort_measure wem",
            "where wem.work_effort_id = #{workEffortId}"
    })
    @ResultMap("workEffortMeasureResultMap")
    List<WorkEffortMeasure> getWorkEffortMeasurebyWorkEffortId(@Param("workEffortId") String workEffortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_measure
     *
     * @mbg.generated Tue Oct 24 10:26:00 CEST 2023
     */
    @Update({
        "update work_effort_measure",
        "set product_id = #{productId,jdbcType=VARCHAR},",
          "empl_position_type_id = #{emplPositionTypeId,jdbcType=VARCHAR},",
          "gl_fiscal_type_enum_id = #{glFiscalTypeEnumId,jdbcType=VARCHAR},",
          "party_id = #{partyId,jdbcType=VARCHAR},",
          "role_type_id = #{roleTypeId,jdbcType=VARCHAR},",
          "we_measure_type_enum_id = #{weMeasureTypeEnumId,jdbcType=VARCHAR},",
          "we_score_range_enum_id = #{weScoreRangeEnumId,jdbcType=VARCHAR},",
          "we_score_conv_enum_id = #{weScoreConvEnumId,jdbcType=VARCHAR},",
          "we_alert_rule_enum_id = #{weAlertRuleEnumId,jdbcType=VARCHAR},",
          "work_effort_influence_id = #{workEffortInfluenceId,jdbcType=VARCHAR},",
          "uom_range_id = #{uomRangeId,jdbcType=VARCHAR},",
          "we_other_goal_enum_id = #{weOtherGoalEnumId,jdbcType=VARCHAR},",
          "work_effort_id = #{workEffortId,jdbcType=VARCHAR},",
          "gl_account_id = #{glAccountId,jdbcType=VARCHAR},",
          "from_date = #{fromDate,jdbcType=TIMESTAMP},",
          "thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "uom_descr = #{uomDescr,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "kpi_score_weight = #{kpiScoreWeight,jdbcType=DOUBLE},",
          "other_work_effort_id = #{otherWorkEffortId,jdbcType=VARCHAR},",
          "period_type_id = #{periodTypeId,jdbcType=VARCHAR},",
          "we_without_perf = #{weWithoutPerf,jdbcType=VARCHAR},",
          "org_unit_role_type_id = #{orgUnitRoleTypeId,jdbcType=VARCHAR},",
          "org_unit_id = #{orgUnitId,jdbcType=VARCHAR},",
          "detail_enum_id = #{detailEnumId,jdbcType=VARCHAR},",
          "data_source_id = #{dataSourceId,jdbcType=VARCHAR},",
          "current_status_id = #{currentStatusId,jdbcType=VARCHAR},",
          "is_posted = #{isPosted,jdbcType=CHAR},",
          "source = #{source,jdbcType=VARCHAR},",
          "sequence_id = #{sequenceId,jdbcType=NUMERIC},",
          "uom_descr_lang = #{uomDescrLang,jdbcType=VARCHAR},",
          "kpi_other_weight = #{kpiOtherWeight,jdbcType=DOUBLE},",
          "is_invisible = #{isInvisible,jdbcType=CHAR},",
          "comments_lang = #{commentsLang,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WorkEffortMeasure row);

    @Update({
            "update work_effort_measure",
            "set",
            "we_score_range_enum_id = #{weScoreRangeEnumId,jdbcType=VARCHAR},",
            "we_score_conv_enum_id = #{weScoreConvEnumId,jdbcType=VARCHAR},",
            "uom_range_id = #{uomRangeId,jdbcType=VARCHAR},",
            "period_type_id = #{periodTypeId,jdbcType=VARCHAR},",
            "we_without_perf = #{weWithoutPerf,jdbcType=VARCHAR},",
            "we_measure_type_enum_id = #{weMeasureTypeEnumId,jdbcType=VARCHAR},",
            "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
            "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
            "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
            "where gl_account_id = #{glAccountId,jdbcType=VARCHAR}"
    })
    int updateWEMeasureFromGlAccount(WorkEffortMeasure row);

    List<WorkEffortMeasure> getWeMeasureEvalId(@Param("workEffortIdFrom") String workEffortIdFrom);

    WorkEffortMeasExUom getWorkEffortMeasureId(@Param("workEffortMeasureId") String workEffortMeasureId);

    List<WorkEffortMeasExUom> getWorkEffortMeasureList();

    @ResultType(int.class)
    int getTotale(@Param("control") boolean control, @Param("LIMIT") Integer limit, @Param("OFFSET") Integer offset, @Param("filters") Filter[] filters, @Param("filterGenericLabel") Filter[] filterGenericLabel, @Param("SORTORDER") Integer sortOrder, @Param("SORTFIELD") String sortField, @Param("ORGANIZATIONID") String organizationId, @Param("matchModeSearch") String matchModeSearch, @Param("SECONDARYLANGUAGE") Boolean secondaryLanguage);

    List<WorkEffortMeasExUom> getWorkEffortMeasureListPagination(@Param("control") boolean control, @Param("LIMIT") Integer limit, @Param("OFFSET") Integer offset, @Param("filters") Filter[] filters, @Param("filterGenericLabel") Filter[] filterGenericLabel, @Param("SORTORDER") Integer sortOrder, @Param("SORTFIELD") String sortField, @Param("ORGANIZATIONID") String organizationId, @Param("matchModeSearch") String matchModeSearch, @Param("SECONDARYLANGUAGE") Boolean secondaryLanguage);

    List<WorkEffortMeasure> getWorkEffortMeasureJoinWorkEffort(String query, boolean secondaryLang);

    List<WorkEffortMeasure> dropdownWorkEffortMeasure(String organizationId);

    List<WorkEffortMeasure> dropdownWorkEffortMeasureWEA(String organizationId);
}