package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortRevision;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface WorkEffortRevisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_revision
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    @Delete({
        "delete from work_effort_revision",
        "where work_effort_revision_id = #{workEffortRevisionId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String workEffortRevisionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_revision
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    @Insert({
        "insert into work_effort_revision (work_effort_revision_id, work_effort_type_id_ctx, ",
        "work_effort_type_id_fil, ref_date, ",
        "description, comments, ",
        "is_closed, has_acctg_trans, ",
        "is_automatic, from_date, ",
        "to_date, organization_id, ",
        "last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp)",
        "values (#{workEffortRevisionId,jdbcType=VARCHAR}, #{workEffortTypeIdCtx,jdbcType=VARCHAR}, ",
        "#{workEffortTypeIdFil,jdbcType=VARCHAR}, #{refDate,jdbcType=TIMESTAMP}, ",
        "#{description,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{isClosed,jdbcType=CHAR}, #{hasAcctgTrans,jdbcType=CHAR}, ",
        "#{isAutomatic,jdbcType=CHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{toDate,jdbcType=TIMESTAMP}, #{organizationId,jdbcType=VARCHAR}, ",
        "#{lastModifiedByUserLogin,jdbcType=VARCHAR}, #{createdByUserLogin,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP})"
    })
    int insert(WorkEffortRevision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_revision
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    @Select({
        "select",
        "work_effort_revision_id, work_effort_type_id_ctx, work_effort_type_id_fil, ref_date, ",
        "description, comments, is_closed, has_acctg_trans, is_automatic, from_date, ",
        "to_date, organization_id, last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_revision",
        "where work_effort_revision_id = #{workEffortRevisionId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="work_effort_revision_id", property="workEffortRevisionId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="work_effort_type_id_ctx", property="workEffortTypeIdCtx", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_type_id_fil", property="workEffortTypeIdFil", jdbcType=JdbcType.VARCHAR),
        @Result(column="ref_date", property="refDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_closed", property="isClosed", jdbcType=JdbcType.CHAR),
        @Result(column="has_acctg_trans", property="hasAcctgTrans", jdbcType=JdbcType.CHAR),
        @Result(column="is_automatic", property="isAutomatic", jdbcType=JdbcType.CHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="to_date", property="toDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="organization_id", property="organizationId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    WorkEffortRevision selectByPrimaryKey(String workEffortRevisionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_revision
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    @Select({
        "select",
        "work_effort_revision_id, work_effort_type_id_ctx, work_effort_type_id_fil, ref_date, ",
        "description, comments, is_closed, has_acctg_trans, is_automatic, from_date, ",
        "to_date, organization_id, last_modified_by_user_login, created_by_user_login, ",
        "last_updated_stamp, last_updated_tx_stamp, created_stamp, created_tx_stamp",
        "from work_effort_revision"
    })
    @Results( id = "workEffortRevisionResultMap", value = {
        @Result(column="work_effort_revision_id", property="workEffortRevisionId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="work_effort_type_id_ctx", property="workEffortTypeIdCtx", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_effort_type_id_fil", property="workEffortTypeIdFil", jdbcType=JdbcType.VARCHAR),
        @Result(column="ref_date", property="refDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_closed", property="isClosed", jdbcType=JdbcType.CHAR),
        @Result(column="has_acctg_trans", property="hasAcctgTrans", jdbcType=JdbcType.CHAR),
        @Result(column="is_automatic", property="isAutomatic", jdbcType=JdbcType.CHAR),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="to_date", property="toDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="organization_id", property="organizationId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WorkEffortRevision> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_revision
     *
     * @mbg.generated Thu Nov 30 11:39:09 CET 2023
     */
    @Update({
        "update work_effort_revision",
        "set work_effort_type_id_ctx = #{workEffortTypeIdCtx,jdbcType=VARCHAR},",
          "work_effort_type_id_fil = #{workEffortTypeIdFil,jdbcType=VARCHAR},",
          "ref_date = #{refDate,jdbcType=TIMESTAMP},",
          "description = #{description,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "is_closed = #{isClosed,jdbcType=CHAR},",
          "has_acctg_trans = #{hasAcctgTrans,jdbcType=CHAR},",
          "is_automatic = #{isAutomatic,jdbcType=CHAR},",
          "from_date = #{fromDate,jdbcType=TIMESTAMP},",
          "to_date = #{toDate,jdbcType=TIMESTAMP},",
          "organization_id = #{organizationId,jdbcType=VARCHAR},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}",
        "where work_effort_revision_id = #{workEffortRevisionId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WorkEffortRevision row);

    List<WorkEffortRevision> getWorkEffortRevisions(@Param("workEffortTypeId") String workEffortTypeId);
}