package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.commons.Filter;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortPartyAssignment;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortPartyAssignmentEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

@Mapper
@Repository
public interface WorkEffortPartyAssignmentMapper {

    @Delete({
        "delete from work_effort_party_assignment",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(@Param("workEffortId") String workEffortId, @Param("partyId") String partyId, @Param("roleTypeId") String roleTypeId, @Param("fromDate") Instant fromDate);

    @Delete({
            "delete from work_effort_party_assignment",
            "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}"
    })
    int deleteByWorkEffortId(@Param("workEffortId") String workEffortId);


    @Insert({
        "insert into work_effort_party_assignment (work_effort_id, party_id, ",
        "role_type_id, from_date, ",
        "thru_date, assigned_by_user_login_id, ",
        "status_id, status_date_time, ",
        "expectation_enum_id, delegate_reason_enum_id, ",
        "facility_id, comments, ",
        "must_rsvp, availability_status_id, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "role_type_weight, role_type_weight_actual, ",
        "work_effort_measure_id, is_posted, ",
        "from_date_from, work_effort_id_from, ",
        "party_id_from, role_type_id_from, ",
        "sequence_num, last_modified_by_user_login, ",
        "created_by_user_login, planned_hours, ",
        "comments_lang, end_date, ",
        "end_cause_enum_id, end_replacement_enum_id, ",
        "end_work_effort_id, end_work_effort_id_we1, ",
        "end_work_effort_id_we2, end_work_effort_id_we3)",
        "values (#{workEffortId,jdbcType=VARCHAR}, #{partyId,jdbcType=VARCHAR}, ",
        "#{roleTypeId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
        "#{thruDate,jdbcType=TIMESTAMP}, #{assignedByUserLoginId,jdbcType=VARCHAR}, ",
        "#{statusId,jdbcType=VARCHAR}, #{statusDateTime,jdbcType=TIMESTAMP}, ",
        "#{expectationEnumId,jdbcType=VARCHAR}, #{delegateReasonEnumId,jdbcType=VARCHAR}, ",
        "#{facilityId,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{mustRsvp,jdbcType=CHAR}, #{availabilityStatusId,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{roleTypeWeight,jdbcType=DOUBLE}, #{roleTypeWeightActual,jdbcType=DOUBLE}, ",
        "#{workEffortMeasureId,jdbcType=VARCHAR}, #{isPosted,jdbcType=CHAR}, ",
        "#{fromDateFrom,jdbcType=TIMESTAMP}, #{workEffortIdFrom,jdbcType=VARCHAR}, ",
        "#{partyIdFrom,jdbcType=VARCHAR}, #{roleTypeIdFrom,jdbcType=VARCHAR}, ",
        "#{sequenceNum,jdbcType=NUMERIC}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR}, #{plannedHours,jdbcType=DOUBLE}, ",
        "#{commentsLang,jdbcType=VARCHAR}, #{endDate,jdbcType=TIMESTAMP}, ",
        "#{endCauseEnumId,jdbcType=VARCHAR}, #{endReplacementEnumId,jdbcType=VARCHAR}, ",
        "#{endWorkEffortId,jdbcType=VARCHAR}, #{endWorkEffortIdWe1,jdbcType=VARCHAR}, ",
        "#{endWorkEffortIdWe2,jdbcType=VARCHAR}, #{endWorkEffortIdWe3,jdbcType=VARCHAR})"
    })
    int insert(WorkEffortPartyAssignment row);


    @Select({
        "select",
        "work_effort_id, party_id, role_type_id, from_date, thru_date, assigned_by_user_login_id, ",
        "status_id, status_date_time, expectation_enum_id, delegate_reason_enum_id, facility_id, ",
        "comments, must_rsvp, availability_status_id, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, role_type_weight, role_type_weight_actual, ",
        "work_effort_measure_id, is_posted, from_date_from, work_effort_id_from, party_id_from, ",
        "role_type_id_from, sequence_num, last_modified_by_user_login, created_by_user_login, ",
        "planned_hours, comments_lang, end_date, end_cause_enum_id, end_replacement_enum_id, ",
        "end_work_effort_id, end_work_effort_id_we1, end_work_effort_id_we2, end_work_effort_id_we3",
        "from work_effort_party_assignment",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    @Results(id = "workEffortPartyAssignment", value = {
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="assigned_by_user_login_id", property="assignedByUserLoginId", jdbcType=JdbcType.VARCHAR),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="status_date_time", property="statusDateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="expectation_enum_id", property="expectationEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="delegate_reason_enum_id", property="delegateReasonEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="facility_id", property="facilityId", jdbcType=JdbcType.VARCHAR),
        @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="must_rsvp", property="mustRsvp", jdbcType=JdbcType.CHAR),
        @Result(column="availability_status_id", property="availabilityStatusId", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="role_type_weight", property="roleTypeWeight", jdbcType=JdbcType.DOUBLE),
        @Result(column="role_type_weight_actual", property="roleTypeWeightActual", jdbcType=JdbcType.DOUBLE),
        @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
        @Result(column="from_date_from", property="fromDateFrom", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="work_effort_id_from", property="workEffortIdFrom", jdbcType=JdbcType.VARCHAR),
        @Result(column="party_id_from", property="partyIdFrom", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_type_id_from", property="roleTypeIdFrom", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_num", property="sequenceNum", jdbcType=JdbcType.NUMERIC),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="planned_hours", property="plannedHours", jdbcType=JdbcType.DOUBLE),
        @Result(column="comments_lang", property="commentsLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_cause_enum_id", property="endCauseEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_replacement_enum_id", property="endReplacementEnumId", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_work_effort_id", property="endWorkEffortId", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_work_effort_id_we1", property="endWorkEffortIdWe1", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_work_effort_id_we2", property="endWorkEffortIdWe2", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_work_effort_id_we3", property="endWorkEffortIdWe3", jdbcType=JdbcType.VARCHAR)
    })
    WorkEffortPartyAssignment selectByPrimaryKey(@Param("workEffortId") String workEffortId, @Param("roleTypeId") String roleTypeId, @Param("partyId") String partyId, @Param("fromDate") Instant fromDate);


    @Select({
        "select",
        "work_effort_id, party_id, role_type_id, from_date, thru_date, assigned_by_user_login_id, ",
        "status_id, status_date_time, expectation_enum_id, delegate_reason_enum_id, facility_id, ",
        "comments, must_rsvp, availability_status_id, last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, role_type_weight, role_type_weight_actual, ",
        "work_effort_measure_id, is_posted, from_date_from, work_effort_id_from, party_id_from, ",
        "role_type_id_from, sequence_num, last_modified_by_user_login, created_by_user_login, ",
        "planned_hours, comments_lang, end_date, end_cause_enum_id, end_replacement_enum_id, ",
        "end_work_effort_id, end_work_effort_id_we1, end_work_effort_id_we2, end_work_effort_id_we3",
        "from work_effort_party_assignment"
    })
    @ResultMap("workEffortPartyAssignment")
    List<WorkEffortPartyAssignment> selectAll();

    @Select({
            "select wepa.*, ",

            //WorkEffortView
           "wev.work_effort_id as wev_work_effort_id, wev.source_reference_id as wev_source_reference_id, wev.work_effort_name as wev_work_effort_name, wev.work_effort_name_lang as wev_work_effort_name_lang, ",
            "wev.description as wev_description, wev.description_lang as wev_description_lang, wev.estimated_start_date as wev_estimated_start_date, wev.estimated_completion_date as wev_estimated_completion_date, ",
            "wev.current_status_id as wev_current_status_id, wev.work_effort_type_id as wev_work_effort_type_id, wev.org_unit_id as wev_org_unit_id, wev.org_unit_role_type_id as wev_org_unit_role_type_id, ",
            "wev.we_assoc_type_id as wev_we_assoc_type_id, wev.is_posted as wev_is_posted, wev.work_effort_snapshot_id as wev_work_effort_snapshot_id, wev.work_effort_revision_id as wev_work_effort_revision_id, ",
            "wev.work_effort_revision_descr as wev_work_effort_revision_descr, wev.snap_shot_description as wev_snap_shot_description, wev.snap_shot_date as wev_snap_shot_date, wev.work_effort_type_period_id as wev_work_effort_type_period_id, ",
            "wev.uom_range_score_id as wev_uom_range_score_id, wev.organization_id as wev_organization_id, wev.effort_uom_id as wev_effort_uom_id, wev.product_id as wev_product_id, wev.empl_position_type_id as wev_empl_position_type_id, ",
            "wev.local_name_content_id as wev_local_name_content_id, wev.estimated_total_effort as wev_estimated_total_effort, wev.weight_kpi as wev_weight_kpi, wev.weight_review as wev_weight_review, wev.weight_sons as wev_weight_sons, ",
            "wev.weight_assoc_work_effort as wev_weight_assoc_work_effort, wev.last_correct_score_date as wev_last_correct_score_date, wev.total_enum_id_kpi as wev_total_enum_id_kpi, wev.total_enum_id_sons as wev_total_enum_id_sons, ",
            "wev.total_enum_id_assoc as wev_total_enum_id_assoc, wev.process_id as wev_process_id, wev.scheduled_start_date as wev_scheduled_start_date, wev.scheduled_completion_date as wev_scheduled_completion_date, ",
            "wev.special_terms as wev_special_terms, wev.data_soll as wev_data_soll, wev.we_type_uom_range_score_id as wev_we_type_uom_range_score_id, wev.we_type_description as wev_we_type_description, wev.we_type_description_lang as wev_we_type_description_lang, ",
            "wev.we_type_icon_id as wev_we_type_icon_id, wev.layout_type_enum_id as wev_layout_type_enum_id, wev.etch as wev_etch, wev.purpose_etch as wev_purpose_etch, wev.child_template_id as wev_child_template_id, ",
            "wev.enable_multi_year_flag as wev_enable_multi_year_flag, wev.we_status_descr as wev_we_status_descr, wev.we_status_descr_lang as wev_we_status_descr_lang, wev.we_activation as wev_we_activation, ",
            "wev.we_status_type_id as wev_we_status_type_id, wev.we_context_id as wev_we_context_id, wev.we_context_description as wev_we_context_description, wev.we_is_template as wev_we_is_template, wev.we_is_root as wev_we_is_root, ",
            "wev.we_is_in_only_one_card as wev_we_is_in_only_one_card, wev.we_hierarchy_type_id as wev_we_hierarchy_type_id, wev.we_int_org_code as wev_we_int_org_code, wev.we_int_org_descr as wev_we_int_org_descr, ",
            "wev.we_int_org_descr_lang as wev_we_int_org_descr_lang, wev.we_org_role_descr as wev_we_org_role_descr, wev.we_org_party_code as wev_we_org_party_code, wev.we_org_party_descr as wev_we_org_party_descr, ",
            "wev.we_org_party_descr_lang as wev_we_org_party_descr_lang, wev.we_type_period_id as wev_we_type_period_id, wev.we_type_period_desc as wev_we_type_period_desc, wev.we_etch as wev_we_etch, wev.we_parent_type_etch as wev_we_parent_type_etch, ",
            "wev.we_parent_etch as wev_we_parent_etch, wev.we_parent_name as wev_we_parent_name, wev.we_parent_id as wev_we_parent_id, ",

            //RoleType
            "rt.role_type_id as rt_role_type_id, rt.parent_type_id as rt_parent_type_id, rt.has_table as rt_has_table, rt.description as rt_description, rt.last_updated_stamp as rt_last_updated_stamp, rt.last_updated_tx_stamp as rt_last_updated_tx_stamp, ",
            "rt.created_stamp as rt_created_stamp, rt.created_tx_stamp as rt_created_tx_stamp, rt.short_label as rt_short_label, rt.icon_content_id as rt_icon_content_id, rt.prev_party_type_id as rt_prev_party_type_id, ",
            "rt.work_effort_type_id as rt_work_effort_type_id, rt.work_effort_assoc_type_id as rt_work_effort_assoc_type_id, rt.work_effort_period_id as rt_work_effort_period_id, rt.description_lang as rt_description_lang, ",
            "rt.short_label_lang as rt_short_label_lang, rt.last_modified_by_user_login as rt_last_modified_by_user_login, rt.created_by_user_login as rt_created_by_user_login,",

            //PartyRoleView
            "prv.parent_role_type_id as prv_parent_role_type_id, prv.parent_description as prv_parent_description, prv.parent_short_label as prv_parent_short_label, prv.parent_role_code as prv_parent_role_code, ",
            "prv.party_id as prv_party_id, prv.role_type_id as prv_role_type_id, prv.role_description as prv_role_description, prv.short_label as prv_short_label, prv.party_name as prv_party_name, prv.empl_position_type_id as prv_empl_position_type_id, ",
            "prv.status_id as prv_status_id, prv.organization_id as prv_organization_id",
            "from work_effort_party_assignment wepa",
            "inner join role_type rt",
                    "on rt.role_type_id = wepa.role_type_id",
            "inner join party_role_view prv",
                    "on prv.party_id = wepa.party_id",
            "inner join work_effort_view wev",
                    "on wev.work_effort_id = wepa.work_effort_id",
            "where wev.work_effort_snapshot_id is null",
                "and wev.organization_id = #{userPrefValue,jdbcType=VARCHAR} and prv.status_id = 'PARTY_ENABLED' and prv.role_type_id = rt.role_type_id",
            "order by wepa.work_effort_id asc"
    })
    @Results(id = "workEffortPartyAssignmentEx", value = {
            @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="party_id", property="partyId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="role_type_id", property="roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="assigned_by_user_login_id", property="assignedByUserLoginId", jdbcType=JdbcType.VARCHAR),
            @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR),
            @Result(column="status_date_time", property="statusDateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="expectation_enum_id", property="expectationEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="delegate_reason_enum_id", property="delegateReasonEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="facility_id", property="facilityId", jdbcType=JdbcType.VARCHAR),
            @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
            @Result(column="must_rsvp", property="mustRsvp", jdbcType=JdbcType.CHAR),
            @Result(column="availability_status_id", property="availabilityStatusId", jdbcType=JdbcType.VARCHAR),
            @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="role_type_weight", property="roleTypeWeight", jdbcType=JdbcType.DOUBLE),
            @Result(column="role_type_weight_actual", property="roleTypeWeightActual", jdbcType=JdbcType.DOUBLE),
            @Result(column="work_effort_measure_id", property="workEffortMeasureId", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
            @Result(column="from_date_from", property="fromDateFrom", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="work_effort_id_from", property="workEffortIdFrom", jdbcType=JdbcType.VARCHAR),
            @Result(column="party_id_from", property="partyIdFrom", jdbcType=JdbcType.VARCHAR),
            @Result(column="role_type_id_from", property="roleTypeIdFrom", jdbcType=JdbcType.VARCHAR),
            @Result(column="sequence_num", property="sequenceNum", jdbcType=JdbcType.NUMERIC),
            @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="planned_hours", property="plannedHours", jdbcType=JdbcType.DOUBLE),
            @Result(column="comments_lang", property="commentsLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="end_date", property="endDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="end_cause_enum_id", property="endCauseEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="end_replacement_enum_id", property="endReplacementEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="end_work_effort_id", property="endWorkEffortId", jdbcType=JdbcType.VARCHAR),
            @Result(column="end_work_effort_id_we1", property="endWorkEffortIdWe1", jdbcType=JdbcType.VARCHAR),
            @Result(column="end_work_effort_id_we2", property="endWorkEffortIdWe2", jdbcType=JdbcType.VARCHAR),
            @Result(column="end_work_effort_id_we3", property="endWorkEffortIdWe3", jdbcType=JdbcType.VARCHAR),

            @Result(column="wev_work_effort_id", property="workEffortView.workEffortId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_source_reference_id", property="workEffortView.sourceReferenceId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_work_effort_name", property="workEffortView.workEffortName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_work_effort_name_lang", property="workEffortView.workEffortNameLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_description", property="workEffortView.description", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_description_lang", property="workEffortView.descriptionLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_estimated_start_date", property="workEffortView.estimatedStartDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_estimated_completion_date", property="workEffortView.estimatedCompletionDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_current_status_id", property="workEffortView.currentStatusId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_work_effort_type_id", property="workEffortView.workEffortTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_org_unit_id", property="workEffortView.orgUnitId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_org_unit_role_type_id", property="workEffortView.orgUnitRoleTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_assoc_type_id", property="workEffortView.weAssocTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_is_posted", property="workEffortView.isPosted", jdbcType=JdbcType.CHAR),
            @Result(column="wev_work_effort_snapshot_id", property="workEffortView.workEffortSnapshotId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_work_effort_revision_id", property="workEffortView.workEffortRevisionId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_work_effort_revision_descr", property="workEffortView.workEffortRevisionDescr", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_snap_shot_description", property="workEffortView.snapShotDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_snap_shot_date", property="workEffortView.snapShotDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_work_effort_type_period_id", property="workEffortView.workEffortTypePeriodId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_uom_range_score_id", property="workEffortView.uomRangeScoreId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_organization_id", property="workEffortView.organizationId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_effort_uom_id", property="workEffortView.effortUomId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_product_id", property="workEffortView.productId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_empl_position_type_id", property="workEffortView.emplPositionTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_local_name_content_id", property="workEffortView.localNameContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_estimated_total_effort", property="workEffortView.estimatedTotalEffort", jdbcType=JdbcType.DOUBLE),
            @Result(column="wev_weight_kpi", property="workEffortView.weightKpi", jdbcType=JdbcType.DOUBLE),
            @Result(column="wev_weight_review", property="workEffortView.weightReview", jdbcType=JdbcType.DOUBLE),
            @Result(column="wev_weight_sons", property="workEffortView.weightSons", jdbcType=JdbcType.DOUBLE),
            @Result(column="wev_weight_assoc_work_effort", property="workEffortView.weightAssocWorkEffort", jdbcType=JdbcType.DOUBLE),
            @Result(column="wev_last_correct_score_date", property="workEffortView.lastCorrectScoreDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_total_enum_id_kpi", property="workEffortView.totalEnumIdKpi", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_total_enum_id_sons", property="workEffortView.totalEnumIdSons", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_total_enum_id_assoc", property="workEffortView.totalEnumIdAssoc", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_process_id", property="workEffortView.processId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_scheduled_start_date", property="workEffortView.scheduledStartDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_scheduled_completion_date", property="workEffortView.scheduledCompletionDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_special_terms", property="workEffortView.specialTerms", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_data_soll", property="workEffortView.dataSoll", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="wev_we_type_uom_range_score_id", property="workEffortView.weTypeUomRangeScoreId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_type_description", property="workEffortView.weTypeDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_type_description_lang", property="workEffortView.weTypeDescriptionLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_type_icon_id", property="workEffortView.weTypeIconId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_layout_type_enum_id", property="workEffortView.layoutTypeEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_etch", property="workEffortView.etch", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_purpose_etch", property="workEffortView.purposeEtch", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_child_template_id", property="workEffortView.childTemplateId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_enable_multi_year_flag", property="workEffortView.enableMultiYearFlag", jdbcType=JdbcType.CHAR),
            @Result(column="wev_we_status_descr", property="workEffortView.weStatusDescr", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_status_descr_lang", property="workEffortView.weStatusDescrLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_activation", property="workEffortView.weActivation", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_status_type_id", property="workEffortView.weStatusTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_context_id", property="workEffortView.weContextId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_context_description", property="workEffortView.weContextDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_is_template", property="workEffortView.weIsTemplate", jdbcType=JdbcType.CHAR),
            @Result(column="wev_we_is_root", property="workEffortView.weIsRoot", jdbcType=JdbcType.CHAR),
            @Result(column="wev_we_is_in_only_one_card", property="workEffortView.weIsInOnlyOneCard", jdbcType=JdbcType.CHAR),
            @Result(column="wev_we_hierarchy_type_id", property="workEffortView.weHierarchyTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_int_org_code", property="workEffortView.weIntOrgCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_int_org_descr", property="workEffortView.weIntOrgDescr", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_int_org_descr_lang", property="workEffortView.weIntOrgDescrLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_org_role_descr", property="workEffortView.weOrgRoleDescr", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_org_party_code", property="workEffortView.weOrgPartyCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_org_party_descr", property="workEffortView.weOrgPartyDescr", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_org_party_descr_lang", property="workEffortView.weOrgPartyDescrLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_type_period_id", property="workEffortView.weTypePeriodId", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_type_period_desc", property="workEffortView.weTypePeriodDesc", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_etch", property="workEffortView.weEtch", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_parent_type_etch", property="workEffortView.weParentTypeEtch", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_parent_etch", property="workEffortView.weParentEtch", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_parent_name", property="workEffortView.weParentName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wev_we_parent_id", property="workEffortView.weParentId", jdbcType=JdbcType.VARCHAR),

            @Result(column="rt_role_type_id", property="roleType.roleTypeId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="rt_parent_type_id", property="roleType.parentTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_has_table", property="roleType.hasTable", jdbcType=JdbcType.CHAR),
            @Result(column="rt_description", property="roleType.description", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_last_updated_stamp", property="roleType.lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="rt_last_updated_tx_stamp", property="roleType.lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="rt_created_stamp", property="roleType.createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="rt_created_tx_stamp", property="roleType.createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="rt_short_label", property="roleType.shortLabel", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_icon_content_id", property="roleType.iconContentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_prev_party_type_id", property="roleType.prevPartyTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_work_effort_type_id", property="roleType.workEffortTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_work_effort_assoc_type_id", property="roleType.workEffortAssocTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_work_effort_period_id", property="roleType.workEffortPeriodId", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_description_lang", property="roleType.descriptionLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_short_label_lang", property="roleType.shortLabelLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_last_modified_by_user_login", property="roleType.lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="rt_created_by_user_login", property="roleType.createdByUserLogin", jdbcType=JdbcType.VARCHAR),

            @Result(column="prv_parent_role_type_id", property="partyRoleView.parentRoleTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_parent_description", property="partyRoleView.parentDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_parent_short_label", property="partyRoleView.parentShortLabel", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_parent_role_code", property="partyRoleView.parentRoleCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_party_id", property="partyRoleView.partyId", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_role_type_id", property="partyRoleView.roleTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_role_description", property="partyRoleView.roleDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_short_label", property="partyRoleView.shortLabel", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_party_name", property="partyRoleView.partyName", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_empl_position_type_id", property="partyRoleView.emplPositionTypeId", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_status_id", property="partyRoleView.statusId", jdbcType=JdbcType.VARCHAR),
            @Result(column="prv_organization_id", property="partyRoleView.organizationId", jdbcType=JdbcType.VARCHAR)


    })
    List<WorkEffortPartyAssignmentEx> getWorkEffortPartyAssignmentList(String userPrefValue);


    @Update({
        "update work_effort_party_assignment",
        "set thru_date = #{thruDate,jdbcType=TIMESTAMP},",
          "assigned_by_user_login_id = #{assignedByUserLoginId,jdbcType=VARCHAR},",
          "status_id = #{statusId,jdbcType=VARCHAR},",
          "status_date_time = #{statusDateTime,jdbcType=TIMESTAMP},",
          "expectation_enum_id = #{expectationEnumId,jdbcType=VARCHAR},",
          "delegate_reason_enum_id = #{delegateReasonEnumId,jdbcType=VARCHAR},",
          "facility_id = #{facilityId,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "must_rsvp = #{mustRsvp,jdbcType=CHAR},",
          "availability_status_id = #{availabilityStatusId,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "role_type_weight = #{roleTypeWeight,jdbcType=DOUBLE},",
          "role_type_weight_actual = #{roleTypeWeightActual,jdbcType=DOUBLE},",
          "work_effort_measure_id = #{workEffortMeasureId,jdbcType=VARCHAR},",
          "is_posted = #{isPosted,jdbcType=CHAR},",
          "from_date_from = #{fromDateFrom,jdbcType=TIMESTAMP},",
          "work_effort_id_from = #{workEffortIdFrom,jdbcType=VARCHAR},",
          "party_id_from = #{partyIdFrom,jdbcType=VARCHAR},",
          "role_type_id_from = #{roleTypeIdFrom,jdbcType=VARCHAR},",
          "sequence_num = #{sequenceNum,jdbcType=NUMERIC},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "planned_hours = #{plannedHours,jdbcType=DOUBLE},",
          "comments_lang = #{commentsLang,jdbcType=VARCHAR},",
          "end_date = #{endDate,jdbcType=TIMESTAMP},",
          "end_cause_enum_id = #{endCauseEnumId,jdbcType=VARCHAR},",
          "end_replacement_enum_id = #{endReplacementEnumId,jdbcType=VARCHAR},",
          "end_work_effort_id = #{endWorkEffortId,jdbcType=VARCHAR},",
          "end_work_effort_id_we1 = #{endWorkEffortIdWe1,jdbcType=VARCHAR},",
          "end_work_effort_id_we2 = #{endWorkEffortIdWe2,jdbcType=VARCHAR},",
          "end_work_effort_id_we3 = #{endWorkEffortIdWe3,jdbcType=VARCHAR}",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and party_id = #{partyId,jdbcType=VARCHAR}",
          "and role_type_id = #{roleTypeId,jdbcType=VARCHAR}",
          "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(WorkEffortPartyAssignment row);

    List<WorkEffortPartyAssignmentEx> getWorkEffortPartyAssignmentListFilter(@Param("SECONDARYLANGUAGE") Boolean secondaryLanguage, @Param("filters") Filter[] filters, @Param("filterGenericLabel") Filter[] filterGenericLabel, @Param("userPrefValue") String userPrefValue, @Param("matchModeSearch") String matchModeSearch);
}