package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortTypeAttr;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface WorkEffortTypeAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_attr
     *
     * @mbg.generated Mon Nov 06 10:08:19 CET 2023
     */
    @Delete({
        "delete from work_effort_type_attr",
        "where work_effort_type_id = #{workEffortTypeId,jdbcType=VARCHAR}",
          "and attr_name = #{attrName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("workEffortTypeId") String workEffortTypeId, @Param("attrName") String attrName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_attr
     *
     * @mbg.generated Mon Nov 06 10:08:19 CET 2023
     */
    @Insert({
        "insert into work_effort_type_attr (work_effort_type_id, attr_name, ",
        "last_updated_stamp, last_updated_tx_stamp, ",
        "created_stamp, created_tx_stamp, ",
        "is_attribute, is_note, is_default, ",
        "sequence_id, period_num, ",
        "is_main, is_html, style1, ",
        "style2, style3, ",
        "is_automatic, note_id, ",
        "internal_note, is_mandatory, ",
        "content_id, attr_name_lang, ",
        "max_length, last_modified_by_user_login, ",
        "created_by_user_login)",
        "values (#{workEffortTypeId,jdbcType=VARCHAR}, #{attrName,jdbcType=VARCHAR}, ",
        "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
        "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
        "#{isAttribute,jdbcType=CHAR}, #{isNote,jdbcType=CHAR}, #{isDefault,jdbcType=CHAR}, ",
        "#{sequenceId,jdbcType=NUMERIC}, #{periodNum,jdbcType=NUMERIC}, ",
        "#{isMain,jdbcType=CHAR}, #{isHtml,jdbcType=CHAR}, #{style1,jdbcType=VARCHAR}, ",
        "#{style2,jdbcType=VARCHAR}, #{style3,jdbcType=VARCHAR}, ",
        "#{isAutomatic,jdbcType=VARCHAR}, #{noteId,jdbcType=VARCHAR}, ",
        "#{internalNote,jdbcType=CHAR}, #{isMandatory,jdbcType=CHAR}, ",
        "#{contentId,jdbcType=VARCHAR}, #{attrNameLang,jdbcType=VARCHAR}, ",
        "#{maxLength,jdbcType=NUMERIC}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(WorkEffortTypeAttr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_attr
     *
     * @mbg.generated Mon Nov 06 10:08:19 CET 2023
     */
    @Select({
        "select",
        "work_effort_type_id, attr_name, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, is_attribute, is_note, is_default, sequence_id, period_num, ",
        "is_main, is_html, style1, style2, style3, is_automatic, note_id, internal_note, ",
        "is_mandatory, content_id, attr_name_lang, max_length, last_modified_by_user_login, ",
        "created_by_user_login",
        "from work_effort_type_attr",
        "where work_effort_type_id = #{workEffortTypeId,jdbcType=VARCHAR}",
          "and attr_name = #{attrName,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="work_effort_type_id", property="workEffortTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="attr_name", property="attrName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_attribute", property="isAttribute", jdbcType=JdbcType.CHAR),
        @Result(column="is_note", property="isNote", jdbcType=JdbcType.CHAR),
        @Result(column="is_default", property="isDefault", jdbcType=JdbcType.CHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.NUMERIC),
        @Result(column="period_num", property="periodNum", jdbcType=JdbcType.NUMERIC),
        @Result(column="is_main", property="isMain", jdbcType=JdbcType.CHAR),
        @Result(column="is_html", property="isHtml", jdbcType=JdbcType.CHAR),
        @Result(column="style1", property="style1", jdbcType=JdbcType.VARCHAR),
        @Result(column="style2", property="style2", jdbcType=JdbcType.VARCHAR),
        @Result(column="style3", property="style3", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_automatic", property="isAutomatic", jdbcType=JdbcType.VARCHAR),
        @Result(column="note_id", property="noteId", jdbcType=JdbcType.VARCHAR),
        @Result(column="internal_note", property="internalNote", jdbcType=JdbcType.CHAR),
        @Result(column="is_mandatory", property="isMandatory", jdbcType=JdbcType.CHAR),
        @Result(column="content_id", property="contentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="attr_name_lang", property="attrNameLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="max_length", property="maxLength", jdbcType=JdbcType.NUMERIC),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    WorkEffortTypeAttr selectByPrimaryKey(@Param("workEffortTypeId") String workEffortTypeId, @Param("attrName") String attrName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_attr
     *
     * @mbg.generated Mon Nov 06 10:08:19 CET 2023
     */
    @Select({
        "select",
        "work_effort_type_id, attr_name, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, is_attribute, is_note, is_default, sequence_id, period_num, ",
        "is_main, is_html, style1, style2, style3, is_automatic, note_id, internal_note, ",
        "is_mandatory, content_id, attr_name_lang, max_length, last_modified_by_user_login, ",
        "created_by_user_login",
        "from work_effort_type_attr"
    })
    @Results( id = "workEffortTypeAttrResultMap", value = {
        @Result(column="work_effort_type_id", property="workEffortTypeId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="attr_name", property="attrName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_attribute", property="isAttribute", jdbcType=JdbcType.CHAR),
        @Result(column="is_note", property="isNote", jdbcType=JdbcType.CHAR),
        @Result(column="is_default", property="isDefault", jdbcType=JdbcType.CHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.NUMERIC),
        @Result(column="period_num", property="periodNum", jdbcType=JdbcType.NUMERIC),
        @Result(column="is_main", property="isMain", jdbcType=JdbcType.CHAR),
        @Result(column="is_html", property="isHtml", jdbcType=JdbcType.CHAR),
        @Result(column="style1", property="style1", jdbcType=JdbcType.VARCHAR),
        @Result(column="style2", property="style2", jdbcType=JdbcType.VARCHAR),
        @Result(column="style3", property="style3", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_automatic", property="isAutomatic", jdbcType=JdbcType.VARCHAR),
        @Result(column="note_id", property="noteId", jdbcType=JdbcType.VARCHAR),
        @Result(column="internal_note", property="internalNote", jdbcType=JdbcType.CHAR),
        @Result(column="is_mandatory", property="isMandatory", jdbcType=JdbcType.CHAR),
        @Result(column="content_id", property="contentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="attr_name_lang", property="attrNameLang", jdbcType=JdbcType.VARCHAR),
        @Result(column="max_length", property="maxLength", jdbcType=JdbcType.NUMERIC),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<WorkEffortTypeAttr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_type_attr
     *
     * @mbg.generated Mon Nov 06 10:08:19 CET 2023
     */
    @Update({
        "update work_effort_type_attr",
        "set last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "is_attribute = #{isAttribute,jdbcType=CHAR},",
          "is_note = #{isNote,jdbcType=CHAR},",
          "is_default = #{isDefault,jdbcType=CHAR},",
          "sequence_id = #{sequenceId,jdbcType=NUMERIC},",
          "period_num = #{periodNum,jdbcType=NUMERIC},",
          "is_main = #{isMain,jdbcType=CHAR},",
          "is_html = #{isHtml,jdbcType=CHAR},",
          "style1 = #{style1,jdbcType=VARCHAR},",
          "style2 = #{style2,jdbcType=VARCHAR},",
          "style3 = #{style3,jdbcType=VARCHAR},",
          "is_automatic = #{isAutomatic,jdbcType=VARCHAR},",
          "note_id = #{noteId,jdbcType=VARCHAR},",
          "internal_note = #{internalNote,jdbcType=CHAR},",
          "is_mandatory = #{isMandatory,jdbcType=CHAR},",
          "content_id = #{contentId,jdbcType=VARCHAR},",
          "attr_name_lang = #{attrNameLang,jdbcType=VARCHAR},",
          "max_length = #{maxLength,jdbcType=NUMERIC},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR}",
        "where work_effort_type_id = #{workEffortTypeId,jdbcType=VARCHAR}",
          "and attr_name = #{attrName,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WorkEffortTypeAttr row);

    List<WorkEffortTypeAttr> getWorkEffortTypeAttrList(@Param("workEffortTypeId") String workEffortTypeId);

    WorkEffortTypeAttr get(@Param("workEffortTypeId") String workEffortTypeId, @Param("attrName") String attrName);
}