package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.commons.Filter;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortAssoc;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortAssocEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

@Mapper
@Repository
public interface WorkEffortAssocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assoc
     *
     * @mbg.generated Thu Sep 28 12:04:21 CEST 2023
     */
    @Delete({
            "delete from work_effort_assoc",
            "where work_effort_id_from = #{workEffortIdFrom,jdbcType=VARCHAR}",
            "and work_effort_id_to = #{workEffortIdTo,jdbcType=VARCHAR}",
            "and work_effort_assoc_type_id = #{workEffortAssocTypeId,jdbcType=VARCHAR}",
            "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(@Param("workEffortIdFrom") String workEffortIdFrom, @Param("workEffortIdTo") String workEffortIdTo, @Param("workEffortAssocTypeId") String workEffortAssocTypeId, @Param("fromDate") Instant fromDate);

    @Delete({
            "delete from work_effort_assoc",
            "where work_effort_id_from = #{workEffortId,jdbcType=VARCHAR} or work_effort_id_to = #{workEffortId,jdbcType=VARCHAR}"
    })
    int deleteByWorkEffortId(@Param("workEffortId") String workEffortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assoc
     *
     * @mbg.generated Thu Sep 28 12:04:21 CEST 2023
     */
    @Insert({
            "insert into work_effort_assoc (work_effort_id_from, work_effort_id_to, ",
            "work_effort_assoc_type_id, from_date, ",
            "sequence_num, thru_date, ",
            "last_updated_stamp, last_updated_tx_stamp, ",
            "created_stamp, created_tx_stamp, ",
            "assoc_weight, comments, ",
            "note, is_posted, response_enum_id, ",
            "we_measure_eval_id, work_effort_revision_id, ",
            "comments_lang, last_modified_by_user_login, ",
            "created_by_user_login)",
            "values (#{workEffortIdFrom,jdbcType=VARCHAR}, #{workEffortIdTo,jdbcType=VARCHAR}, ",
            "#{workEffortAssocTypeId,jdbcType=VARCHAR}, #{fromDate,jdbcType=TIMESTAMP}, ",
            "#{sequenceNum,jdbcType=NUMERIC}, #{thruDate,jdbcType=TIMESTAMP}, ",
            "#{lastUpdatedStamp,jdbcType=TIMESTAMP}, #{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, ",
            "#{createdStamp,jdbcType=TIMESTAMP}, #{createdTxStamp,jdbcType=TIMESTAMP}, ",
            "#{assocWeight,jdbcType=DOUBLE}, #{comments,jdbcType=VARCHAR}, ",
            "#{note,jdbcType=VARCHAR}, #{isPosted,jdbcType=CHAR}, #{responseEnumId,jdbcType=VARCHAR}, ",
            "#{weMeasureEvalId,jdbcType=VARCHAR}, #{workEffortRevisionId,jdbcType=VARCHAR}, ",
            "#{commentsLang,jdbcType=VARCHAR}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
            "#{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(WorkEffortAssoc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assoc
     *
     * @mbg.generated Thu Sep 28 12:04:21 CEST 2023
     */
    @Select({
            "select",
            "work_effort_id_from, work_effort_id_to, work_effort_assoc_type_id, from_date, ",
            "sequence_num, thru_date, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
            "created_tx_stamp, assoc_weight, comments, note, is_posted, response_enum_id, ",
            "we_measure_eval_id, work_effort_revision_id, comments_lang, last_modified_by_user_login, ",
            "created_by_user_login",
            "from work_effort_assoc",
            "where work_effort_id_from = #{workEffortIdFrom,jdbcType=VARCHAR}",
            "and work_effort_id_to = #{workEffortIdTo,jdbcType=VARCHAR}",
            "and work_effort_assoc_type_id = #{workEffortAssocTypeId,jdbcType=VARCHAR}",
            "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    @Results({
            @Result(column="work_effort_id_from", property="workEffortIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="work_effort_id_to", property="workEffortIdTo", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="work_effort_assoc_type_id", property="workEffortAssocTypeId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="sequence_num", property="sequenceNum", jdbcType=JdbcType.NUMERIC),
            @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="assoc_weight", property="assocWeight", jdbcType=JdbcType.DOUBLE),
            @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
            @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
            @Result(column="response_enum_id", property="responseEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="we_measure_eval_id", property="weMeasureEvalId", jdbcType=JdbcType.VARCHAR),
            @Result(column="work_effort_revision_id", property="workEffortRevisionId", jdbcType=JdbcType.VARCHAR),
            @Result(column="comments_lang", property="commentsLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    WorkEffortAssoc selectByPrimaryKey(@Param("workEffortIdFrom") String workEffortIdFrom, @Param("workEffortIdTo") String workEffortIdTo, @Param("workEffortAssocTypeId") String workEffortAssocTypeId, @Param("fromDate") Instant fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assoc
     *
     * @mbg.generated Thu Sep 28 12:04:21 CEST 2023
     */
    @Select({
            "select",
            "work_effort_id_from, work_effort_id_to, work_effort_assoc_type_id, from_date, ",
            "sequence_num, thru_date, last_updated_stamp, last_updated_tx_stamp, created_stamp, ",
            "created_tx_stamp, assoc_weight, comments, note, is_posted, response_enum_id, ",
            "we_measure_eval_id, work_effort_revision_id, comments_lang, last_modified_by_user_login, ",
            "created_by_user_login",
            "from work_effort_assoc"
    })
    @Results({
            @Result(column="work_effort_id_from", property="workEffortIdFrom", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="work_effort_id_to", property="workEffortIdTo", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="work_effort_assoc_type_id", property="workEffortAssocTypeId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="from_date", property="fromDate", jdbcType=JdbcType.TIMESTAMP, id=true),
            @Result(column="sequence_num", property="sequenceNum", jdbcType=JdbcType.NUMERIC),
            @Result(column="thru_date", property="thruDate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="assoc_weight", property="assocWeight", jdbcType=JdbcType.DOUBLE),
            @Result(column="comments", property="comments", jdbcType=JdbcType.VARCHAR),
            @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
            @Result(column="is_posted", property="isPosted", jdbcType=JdbcType.CHAR),
            @Result(column="response_enum_id", property="responseEnumId", jdbcType=JdbcType.VARCHAR),
            @Result(column="we_measure_eval_id", property="weMeasureEvalId", jdbcType=JdbcType.VARCHAR),
            @Result(column="work_effort_revision_id", property="workEffortRevisionId", jdbcType=JdbcType.VARCHAR),
            @Result(column="comments_lang", property="commentsLang", jdbcType=JdbcType.VARCHAR),
            @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
            @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<WorkEffortAssoc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_assoc
     *
     * @mbg.generated Thu Sep 28 12:04:21 CEST 2023
     */
    @Update({
            "update work_effort_assoc",
            "set sequence_num = #{sequenceNum,jdbcType=NUMERIC},",
            "thru_date = #{thruDate,jdbcType=TIMESTAMP},",
            "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
            "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
            "assoc_weight = #{assocWeight,jdbcType=DOUBLE},",
            "comments = #{comments,jdbcType=VARCHAR},",
            "note = #{note,jdbcType=VARCHAR},",
            "is_posted = #{isPosted,jdbcType=CHAR},",
            "response_enum_id = #{responseEnumId,jdbcType=VARCHAR},",
            "we_measure_eval_id = #{weMeasureEvalId,jdbcType=VARCHAR},",
            "work_effort_revision_id = #{workEffortRevisionId,jdbcType=VARCHAR},",
            "comments_lang = #{commentsLang,jdbcType=VARCHAR},",
            "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR}",
            "where work_effort_id_from = #{workEffortIdFrom,jdbcType=VARCHAR}",
            "and work_effort_id_to = #{workEffortIdTo,jdbcType=VARCHAR}",
            "and work_effort_assoc_type_id = #{workEffortAssocTypeId,jdbcType=VARCHAR}",
            "and from_date = #{fromDate,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(WorkEffortAssoc row);

    @ResultType(int.class)
    int getTotale(@Param("control") boolean control, @Param("organizationId") String organizationId , @Param("LIMIT") Integer limit, @Param("OFFSET") Integer offset, @Param("filters") Filter[] filters,@Param("filterGenericLabel") Filter[] filterGenericLabel, @Param("SORTORDER") Integer sortOrder, @Param("SORTFIELD") String sortField, @Param("matchModeSearch") String matchModeSearch, @Param("SECONDARYLANGUAGE") Boolean secondaryLanguage);


    List<WorkEffortAssocEx> getWorkEffortAssocPagination(@Param("control") boolean control, @Param("organizationId") String organizationId , @Param("LIMIT") Integer limit, @Param("OFFSET") Integer offset, @Param("filters") Filter[] filters,@Param("filterGenericLabel") Filter[] filterGenericLabel, @Param("SORTORDER") Integer sortOrder, @Param("SORTFIELD") String sortField, @Param("matchModeSearch") String matchModeSearch, @Param("SECONDARYLANGUAGE") Boolean secondaryLanguage);
}