package it.mapsgroup.gzoom.mybatis.mapper;

import it.mapsgroup.gzoom.mybatis.dto.WorkEffortStatus;
import it.mapsgroup.gzoom.mybatis.dto.WorkEffortStatusEx;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

@Mapper
@Repository
public interface WorkEffortStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_status
     *
     * @mbg.generated Tue Jan 16 16:10:58 CET 2024
     */
    @Delete({
        "delete from work_effort_status",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and status_id = #{statusId,jdbcType=VARCHAR}",
          "and status_datetime = #{statusDatetime,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(@Param("workEffortId") String workEffortId, @Param("statusId") String statusId, @Param("statusDatetime") Instant statusDatetime);

    @Delete({
            "delete from work_effort_status",
            "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}"
    })
    int deleteAllByWorkEffortId(@Param("workEffortId") String workEffortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_status
     *
     * @mbg.generated Tue Jan 16 16:10:58 CET 2024
     */
    @Insert({
        "insert into work_effort_status (work_effort_id, status_id, ",
        "status_datetime, set_by_user_login, ",
        "reason, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, ",
        "created_tx_stamp, last_modified_by_user_login, ",
        "created_by_user_login)",
        "values (#{workEffortId,jdbcType=VARCHAR}, #{statusId,jdbcType=VARCHAR}, ",
        "#{statusDatetime,jdbcType=TIMESTAMP}, #{setByUserLogin,jdbcType=VARCHAR}, ",
        "#{reason,jdbcType=VARCHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP}, #{lastModifiedByUserLogin,jdbcType=VARCHAR}, ",
        "#{createdByUserLogin,jdbcType=VARCHAR})"
    })
    int insert(WorkEffortStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_status
     *
     * @mbg.generated Tue Jan 16 16:10:58 CET 2024
     */
    @Select({
        "select",
        "work_effort_id, status_id, status_datetime, set_by_user_login, reason, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp, last_modified_by_user_login, ",
        "created_by_user_login",
        "from work_effort_status",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and status_id = #{statusId,jdbcType=VARCHAR}",
          "and status_datetime = #{statusDatetime,jdbcType=TIMESTAMP}"
    })
    @Results({
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="status_datetime", property="statusDatetime", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="set_by_user_login", property="setByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    WorkEffortStatus selectByPrimaryKey(@Param("workEffortId") String workEffortId, @Param("statusId") String statusId, @Param("statusDatetime") Instant statusDatetime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_status
     *
     * @mbg.generated Tue Jan 16 16:10:58 CET 2024
     */
    @Select({
        "select",
        "work_effort_id, status_id, status_datetime, set_by_user_login, reason, last_updated_stamp, ",
        "last_updated_tx_stamp, created_stamp, created_tx_stamp, last_modified_by_user_login, ",
        "created_by_user_login",
        "from work_effort_status"
    })
    @Results({
        @Result(column="work_effort_id", property="workEffortId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="status_id", property="statusId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="status_datetime", property="statusDatetime", jdbcType=JdbcType.TIMESTAMP, id=true),
        @Result(column="set_by_user_login", property="setByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_updated_stamp", property="lastUpdatedStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_updated_tx_stamp", property="lastUpdatedTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_stamp", property="createdStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_tx_stamp", property="createdTxStamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_modified_by_user_login", property="lastModifiedByUserLogin", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_login", property="createdByUserLogin", jdbcType=JdbcType.VARCHAR)
    })
    List<WorkEffortStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_effort_status
     *
     * @mbg.generated Tue Jan 16 16:10:58 CET 2024
     */
    @Update({
        "update work_effort_status",
        "set set_by_user_login = #{setByUserLogin,jdbcType=VARCHAR},",
          "reason = #{reason,jdbcType=VARCHAR},",
          "last_updated_stamp = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "last_updated_tx_stamp = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "created_stamp = #{createdStamp,jdbcType=TIMESTAMP},",
          "created_tx_stamp = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "last_modified_by_user_login = #{lastModifiedByUserLogin,jdbcType=VARCHAR},",
          "created_by_user_login = #{createdByUserLogin,jdbcType=VARCHAR}",
        "where work_effort_id = #{workEffortId,jdbcType=VARCHAR}",
          "and status_id = #{statusId,jdbcType=VARCHAR}",
          "and status_datetime = #{statusDatetime,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(WorkEffortStatus row);

    List<WorkEffortStatusEx> selectWorkEffortStatusEx( @Param("workEffortId") String workEffortId);
}